### ISSUE TITLE
Collection not working  v 1.5.1

### ISSUE THREAD

**Issue by mojbenzcar** [kristijanhusak/laravel-form-builder#100]
was working find fine in older version 
https://github.com/kristijanhusak/laravel-form-builder#collection-of-child-forms

**Comment by kristijanhusak** [comment]
Can you be more precise?

Is it throwing an Exeption, doing something wrong, or something else?

**Comment by mojbenzcar** [comment]
Oh sorry .
@kristijanhusak 
It does display form specified in collection 

eg .->add('tags', 'collection', [
                'type' => 'form',
                'options' => [    // these are options for a single type
                    'class' => 'App\Forms\TagsForm',
                    'label' => false,
                ]
            ]);
TagsForm is not rendered

**Comment by kristijanhusak** [comment]
Ah yes, you are right. It's not rendered when there is no any data. Fix coming in few min. Thanks for reporting.

**Comment by kristijanhusak** [comment]
Ok, i fixed it, pull the latest release (1.5.10). Thanks for reporting.

**Comment by mojbenzcar** [comment]
@kristijanhusak Thanks for quick fix and Welcome :)
