### ISSUE TITLE
Hidden Model Attributes

### ISSUE THREAD

**Issue by MeeDNite** [kristijanhusak/laravel-form-builder#103]
Hi,
I have set some values in Model to be Hidden [from this section](http://laravel.com/docs/5.0/eloquent#converting-to-arrays-or-json) of ducumentation, like password field for User model. But by binding the model to form, these fields also get populated, which they shouldn't.
any ideas?

**Comment by kristijanhusak** [comment]
Hi,

how do you pass the model to the form class?

The `hidden` functionality works only when model is converted to json or array. Try passing model to form class like this:
```php
$model = User::find($id);
\FormBuilder::create('App\Forms\UserForm', [
    'model' => $model->toArray()
]);
```

**Comment by MeeDNite** [comment]
I works this way, but isnt the form supposed to look for model's hidden attributes?

**Comment by kristijanhusak** [comment]
It takes the model as you pass it and maps it to the form. If it's an object, it does not detect hidden attributes, just collects all data that is available on it, and in case when it's an eloquent model instance, everything is. I believe it should be left like that, converting it to array when passing it to form is not a big deal.
