### ISSUE TITLE
Select form's name is corrupted

### ISSUE THREAD

**Issue by tormit** [kristijanhusak/laravel-form-builder#104]
Select form name is rendered like this:
```html
<select class="" name="form_name[form_name[field]]">
<option>...
</select>
```

Need fix ASAP.

Seems to be caused by 5db7f4a3e0abfd719840b3d2377918207d477236.

**Comment by kristijanhusak** [comment]
Thanks, will fix it soon.

**Comment by kristijanhusak** [comment]
@tormit 
I fixed it, do a composer update. Thanks for reporting.
