### ISSUE TITLE
How to set template for the form

### ISSUE THREAD

**Issue by mrnull** [kristijanhusak/laravel-form-builder#105]
Hello!
I have a form with collection field which is subform.
I want to set custom template for this subform, but I don't understand how to do it.
All I need to do, is make for two columns, I down know, may be I can do it with some options.

**Comment by kristijanhusak** [comment]
Hi @mrnull ,

You can do it like this, without a custom template:

```php
<?php
class MainForm extends Form
{

    public function buildForm()
    {
        $this->add('fieldname', 'collection', [
            'type' => 'form',
            'options' => [
                'class' => 'App\Forms\SubForm',
                'wrapper' => ['class' => 'row']
            ]
        ])
    }
}

class SubForm extends Form
{
    public function buildForm()
    {
        $this->add('name', 'text', [
            'wrapper' => ['class' => 'form-group col-md-6']
        ])
        ->add('email', 'email', [
            'wrapper' => ['class' => 'form-group col-md-6']
        ]);
    }
}
```

**Comment by kristijanhusak** [comment]
@mrnull 
Is this working for you?

**Comment by mrnull** [comment]
@kristijanhusak 
It's looks like it works, but not correctly.
![screenshot from 2015-06-11 16 03 08](https://cloud.githubusercontent.com/assets/285154/8107641/80714916-1053-11e5-9f61-892c46185218.png)

First of all I down understand why I have "Fields" label... I have label => false in my options.

https://gist.github.com/mrnull/44dd66594627f206aaa6

**Comment by kristijanhusak** [comment]
@mrnull 
Try disabling label in the options also:
```php
            $this->add('fields', 'collection', [
                'type' => 'form',
                'label' => false,
                // 'prototype' => true,
                'options' => [
                    'label' => false,
                    'class' => 'App\Forms\FormItemForm',
                    'wrapper' => ['class' => 'row']
                ]
            ])
```

**Comment by mrnull** [comment]
Thank you, @kristijanhusak, it working fine!
