### ISSUE TITLE
Form horizontal

### ISSUE THREAD

**Issue by nicozimmermann94** [kristijanhusak/laravel-form-builder#113]
Hey,
how do I make horizontal forms? Setting 'class' => 'form-horizontal' does not do the trick, because the fields will not inlcude the grid system. Do I have to modify each field type file to include the grid system?

Cheers.

**Comment by kristijanhusak** [comment]
Hi,

If you will use it across whole project like horizontal form, you can publish the config and set the defaults there. It can be overridden at any time. More info [here](http://kristijanhusak.github.io/laravel-form-builder/custom/configuration-basics.html).
