### ISSUE TITLE
Form is not filled with model data

### ISSUE THREAD

**Issue by faheem00** [kristijanhusak/laravel-form-builder#116]
Hello, I have been using laravel form builder for quite a while now, and there has been no problem so far. But recently, a problem arised. If I attach a model with a form, the form does not fill with the model data as it did before. Consider the below controller action

```php
public function showProfile()
{
        $data['form'] = FormBuilder::create('App\Forms\ProfileForm')->setUrl(route('user.profile.post'))->setMethod('POST')->setModel(Auth::getUser());
        return view('user.profile',$data);
}
```

In it, I set the model as current user model. Here is the form itself

```php
<?php namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class ProfileForm extends Form
{
    public function buildForm()
    {
        $this->add('username', 'text')
            ->add('full_name', 'text')
            ->add('email','static')
            ->add('password', 'repeated', [
                'type' => 'password',
                'second_name' => 'password_confirmation',
                'first_options' => [
                    'attr' => ['placeholder' => 'Enter Password'],
                ],
                'second_options' => [
                    'attr' => ['placeholder' => 'Repeat Password'],
                ]
            ])
            ->add('phone_number', 'text')
            ->add('Update', 'submit', [
                'attr' => ['class' => 'btn btn-primary']
            ])
        ;
    }
}
```

I echo the form using blade, as usual

```blade
{!!form($form)!!}
```

But the form does not fill up with user data. I have tried it many ways, using different forms with different models, changing actions and controllers, to no avail. The form submission works correctly, but the data displaying using model is the problem.

Can you kindly identify the problem here? Is it a childish mistake of mine, or is there a problem in the codebase? Any help will be deeply appreciated. Thanks!

**Comment by kristijanhusak** [comment]
Hi @faheem00 ,

Did you add method on User model that is called `getUser`?

Does `Auth::getUser()` return anything? Did you check?

Is user logged in?

Proper way to get logged in user is `Auth::user()`.

Check things above and let me know if the problem still exists.

**Comment by nicozimmermann94** [comment]
Same problem here. However, it seems that select inputs work, but no text or textarea.

**Comment by kristijanhusak** [comment]
@faheem00 @nicozimmermann94 

I'll check it out. Thanks for reporting.

In the meantime, can you check if you published the vendor files with `php artisan vendor:publish` ?

If you did, check if views in `resources/views/vendor/laravel-form-builder` contains something like:
```php
$options['default_value']
```

If it does, replace `default_value` with `value`. It's mentioned in the [changelog](https://github.com/kristijanhusak/laravel-form-builder/blob/master/CHANGELOG.md)

**Comment by nicozimmermann94** [comment]
@kristijanhusak 
Thanks for the answer! I updated back to 1.6 and replacing every `default_value` to `value` in `vendor/laravel-form-builder` worked. I also did `php artisan vendor:publish` before.

**Comment by kristijanhusak** [comment]
@nicozimmermann94 great! :)

@faheem00 , only you to check it out now :)

**Comment by faheem00** [comment]
@kristijanhusak yes changing the <code>default_value</code> to <code>value</code> does work now, I can see all the model data now. Thanks for your help, much appreciate it :)

**Comment by kristijanhusak** [comment]
Great! You're welcome :)
