### ISSUE TITLE
htmlentities() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by jpggvilaca** [kristijanhusak/laravel-form-builder#117]
I have this problem while using form builder, my index.blade.php just has :
         {!! form($form) !!}

and my action on the controller is:
    public function create(FormBuilder $formBuilder)
     {
          $form = $formBuilder->create('Backend\UserForm', [
              'method' => 'POST',
              'url'    => route('admin.users.store'),
          ]);

          return view('backend.users.create', compact('form'));
      }

It doesn't even get in action 'store' so the problem is on one of these i guess? i've tried EVERYTHING and can't make this work, any tips?

**Comment by kristijanhusak** [comment]
@jpggvilaca 
Can you please give me the content of the `Backend\UserForm`? I need it so I can test this out to see what's the problem.

**Comment by jpggvilaca** [comment]
$this
            ->add('first_name', 'text')
            ->add('last_name', 'text')
            ->add('username', 'text')
            ->add('email', 'text')
            ->add('password', 'password', [
                'default_value' => function () {
                    return '';
                },
                'help_block' => [
                    'text' => 'Leave empty to keep current password',
                ],
            ])
            ->add('avatar', 'plupload', [
                'name'       => 'avatar',
                'route'      => route('admin.users.avatar', $this->model),
                'multiple'   => true,
            ])
            ->add('save', 'submit', [
                'attr' => [ 'class' => 'button primary' ]
            ])
            ->add('cancel', 'cancel', [
                'route' => route('admin.users.index')
            ]);
    }

**Comment by jpggvilaca** [comment]
and here's the full error message:

htmlentities() expects parameter 1 to be string, object given (View: /home/vagrant/sites/tekzenit/resources/views/backend/users/create.blade.php)

Thank you.

**Comment by kristijanhusak** [comment]
I see that you created some custom fields, `plupload` and `cancel`. Can you give me the content of those? Both class and view. It's probably something with that. Try temporarily commenting out those two fields to see if it's working.

**Comment by jpggvilaca** [comment]
It still throws the same error...it was everything working fine, until i removed bootstrap from the project and added foundation for apps...

**Comment by jpggvilaca** [comment]
it seems the $form is being passed as an object, and not a string, which triggers the exception for html entities. but how? i have 3 more controllers and views and im using the same method on ALL of them, for some reason, this form users doesnt work. Maybe auth problems? i dont get it

**Comment by kristijanhusak** [comment]
@jpggvilaca 
Problem is in this part:
```php
->add('password', 'password', [
    'default_value' => function () {
        return '';
    },
    'help_block' => [
        'text' => 'Leave empty to keep current password',
    ],
])
```
`default_value` is renamed to `value` from version `1.6.0` (https://github.com/kristijanhusak/laravel-form-builder/blob/master/CHANGELOG.md#160), and `default_value` is now used only as fallback value, which only accepts primitive types (string, int, etc). So renaming the `default_value` to `value` should work for you. Also, you do not need to use Closure for that , it's enough to do `value => ''`.

**Comment by jpggvilaca** [comment]
IT WORKED, thank you!!! omfg, i was on this for like 6 hours lol, thanks.

**Comment by kristijanhusak** [comment]
Just follow docs and changelog, if i change anything i write it out.
