### ISSUE TITLE
Disable all fields in form

### ISSUE THREAD

**Issue by Lykegenes** [kristijanhusak/laravel-form-builder#120]
There should be an easy way to set all fields in a form as "disabled" or "readonly", or even set their type as "static".
This could be useful if we want to only show the data to the user, or if that user doesn't have the required permissions to modify the data.

What do you think?

**Comment by kristijanhusak** [comment]
For simple form (Form with simple input types), you could do:
```php
foreach ($form->getFields() as $field) {
    $field->setOptions([
        'attr' => ['disabled' => 'disabled']
    ]);
```
It will not work for fields that are of type ParentType, so any child form, collection, choice etc will not work. I Will probably add this functionality, it's good idea.

I think converting it to static is the best solution, what do you think?

**Comment by kristijanhusak** [comment]
@Lykegenes 
I added functions `disableFields` and `enableFields` to the form class. More info in the docs [here](http://kristijanhusak.github.io/laravel-form-builder/form/methods-and-properties.html#disablefields). Thanks.
