### ISSUE TITLE
Checkbox value from model

### ISSUE THREAD

**Issue by Andy-V** [kristijanhusak/laravel-form-builder#124]
Hi,

I am trying to make a checkbox selected using an eloquent model but I can't seem to do it. I can't find any particular code to select checkboxes based on the value of a model. Is this feature in your form builder or does it need to be added?

Andy

**Comment by Andy-V** [comment]
As far as I can tell it does need to be added, I personally got things working by adding this to CheckableType:

    protected function setupValue()
        {
            parent::setupValue();
    
            if ($this->options['value'] == $this->getModelValueAttribute($this->parent->getModel(), $this->name)) {
                $this->options['checked'] = true;
            }
        }

**Comment by kristijanhusak** [comment]
Hi Andy,

Yes, it was not working properly. Now I set it like this:

1. `value` is by default set to 1. Can be changed ofc.
2. `checked` state can be changed with `checked` option in field:

    ```php
    $this->add('remember', 'checkbox', ['checked' => true]);
    ```
3. value for checkbox field in the model needs to be truthy to be checked. For example:
```php
class MyForm extends Form {
    public function buildForm()
    {
        $this->add('remember', 'checkbox');
    }
}

// Controller
$model = [
    'remember' => 1 // anything truthy will set it checked, for example: true, any positive number, etc.
];
FormBuilder::create('MyForm', ['model' => $model]);

// Will NOT be checked if:
$model = [
    'remember' => 0 // false, null,  empty array, etc.
];
``` 

At this moment it's only available on the `dev-master`. Will be working properly in some future release, which will be probably published soon. Thanks for reporting.
