### ISSUE TITLE
Data not show in edit function 

### ISSUE THREAD

**Issue by Abdulhmid** [kristijanhusak/laravel-form-builder#126]
I use this edit function  : 
public function getEdit(FormBuilder $formBuilder=null, $id="")
{
		$users = $this->model->find($id);

		$form = $formBuilder->create('App\Forms\GroupsForm')->setFormOptions([
		            		'method' => 'POST',
		            		'url' => 'admin/groups/store/'.$id,
		            		'model' => $users	
	        		]);
}
but in view form, data on my query not show,
 Anyone help me ?

**Comment by Abdulhmid** [comment]
resolved

**Comment by kristijanhusak** [comment]
Ok, then i'm closing this.
