### ISSUE TITLE
relational database support ?

### ISSUE THREAD

**Issue by rayhan0421** [kristijanhusak/laravel-form-builder#127]

**Comment by kristijanhusak** [comment]
Some explanation?

**Comment by rayhan0421** [comment]
one to many , many to one, many to many...............ORM like symfony2

**Comment by kristijanhusak** [comment]
You can do that. For example Entity type http://kristijanhusak.github.io/laravel-form-builder/field/entity.html . You have access to model, and you can handle it however you want. Read through the docs.

**Comment by rayhan0421** [comment]
thank you
