### ISSUE TITLE
Additional javascript and group

### ISSUE THREAD

**Issue by mix359** [kristijanhusak/laravel-form-builder#128]
Hi,
I've started using this code in my project and I've to thank you, because is very useful :) (I really like the "plain" possibility, to quickly create form in the controller!)

I came from drupal, where there's a big form system, and this component is similar to that logic of creating form.
Using it I've found two things that I miss and I would like to have.
The first one is a way to "attach" javascript to the form/fields: 
Let say I wanna attach a jquery ui function to one of the field. One way could be create a new field type with the javascript in it, but if I only wanna add a simple javascript check to one of the field value, at the moment I cannot in a simply way.
So my propose (that I can develop and submit to the repo), is to add an array with the javascripts code that should be rendered at the end of the form. The user can attach javascript to the form with an "addJs" or "addJavascript" method. 
One of the parameter of the method could be a boolean call "encapsulate". It this is true, the code is encapsulated in a standard jquery onReady function. An other parameter could be "add field list variable". This should add a local (if encapsulate) variable with the list of the current fields name (passed to the add method) and the autoassigned id (so I can attach to the field)
This logic can be applied to the field too: one can attach a javascript code to a single field, and is rendered after the field (with the field data, if is encapsulated)

An other idea (that i can develop) it's a container type field. It's similar to encapsulate an other form.. but you don't have to create. It's main purpose is create a container (a div for example) with his proprieties (like a css class) that contains other fields. This could be useful to create group of fields (visually or, if actived, it can make an array of field, using the nameOfTheContainer[nameOfTheField] structure)
From this field, some other could be derivated (extending it), for example we can make an accordion group, that can be closed. Or a multiple accordion/tab container, so we can make complex form.
I can develop this, but probably I've to make some little change to the other core structure to do this (I don't wanna replicate the code that add and manage a field in a form/container, so the best way is doing like in the other laravel 5 component, and make it a trait)

Let me know if you are interested and I can start (if I have time) to develop this thing.

PS: there's a standard method to create a new package that extend this with a new field type?
If for example I wanna create a new jquery ui field as a composer package, how can I add the field to the list? I have to say to the user that he have to add in his config.php file?

Thanks
Mix

**Comment by kristijanhusak** [comment]
Hi @mix359 ,

Thanks for the ideas and thorough explanation of it. Unfortunately, I cannot agree to add this kind of functionality to the package. Focus is mainly on php, and I don't want to add any JS to it. These days when "modern" javascript is available, adding inline javascript to the page is just unacceptable. All of those things that you wrote can be handled through regular javascript in separate javascript file. For example, adding a ui datepicker should be simple as this:
```javascript
// main.js
$('.datepicker').datepicker();
```

```php
class MyForm extends Form {

    public function buildForm()
    {
        $this->add('date', 'text', [
            'attr' => ['class' => 'form-control datepicker']
        ]);
    }
}
```

Or if you don't want to add class manually every time, you could create custom field type:
```php
namespace App\Forms\Fields;

class DatepickerType extends InputType {

    public function getDefaults()
    {
        $options = [
            'attr' => ['class' => 'form-control datepicker']
        ];

        return array_merge(parent::getDefaults(), $options);
    }
}
```

And then after you published config with `php artisan vendor:publish`, go to `config/laravel-form-builder.php` and add `'datepicker' => 'App\Forms\Fields\DatepickerType'` to the custom fields key.

After that, usage is simple:
```php
class MyForm extends Form {
    public function buildForm()
    {
        $this->add('date', 'datepicker')
             ->add('childForm', 'form', ['class' => 'App\Forms\ChildForm']);
    }
```

Also, if you need to create accordion with subforms, just create child forms, and render them in the view as you want:

```html
{!! form_start($form) !!}
{!! form_row($form->date) !!}
<div class="accordion">
    <p class="accordion-title">Subform 1</p>
    <div class="accordion-item">
        {!! form_row($form->childForm) !!}
    </div>
</div>
{!! form_end($form) !!}
```

**Comment by mix359** [comment]
Thanks for the answers
About the inline javascript, you're right. It could be done in another way.

For the field groups.. I've red about the subform, but I don't think is the right way to create complex or dynamic form. Yes you can create an other form with some field and incorporate using a child form field, that can graphically create a container for the field (you can add a class or an attribute), but it doesn't manage the data (you have to manually attach the data to the sub form) and cannot "nest" it as data in an array.
I'll give you an example (from a work I've done in the past), so maybe can make more clear what I need, using a sort of new fake field:
$form = \FormBuilder::plain([
			'method' => 'POST',
			'model' => $model,
			'url' => url('...')
		]);

$form->add("name", "text");
$tabs = [];
for($i=0;$i!=4;$i++) {
    $tabs[$i] = \FormBuilderTab::create('Agency '.($i+1));
    $tabs[$i]->add("name","text");
    $tabs[$i]->add("city","text");
}
$this->add("agencies","tabs",['tabs' => $tabs, 'tree' => true, 'default_tab' => 0]);

This main model have a name attribute, and a agencies attribute, that return an array of agency. An agency have a name and city attributes. (this could be a model with a one-to-many relation)
Usign the "tree" attributes, the data are returned this way:
['name' => "", 'agencies' => [['name' => "", 'city' => ""], ...]
This permit to create and manage much complex type of form dynamically.

(The idea is from the drupal form container/tabs: https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7#container)

**Comment by kristijanhusak** [comment]
Check the [collection](http://kristijanhusak.github.io/laravel-form-builder/field/collection.html) field type. You can create collection of forms or simple fields. That should satisfy this kind of need.

**Comment by mix359** [comment]
Uhm, yes I've checked all the field types, and no one can does that type of thing:
For the collection, it only accept one field type, not a group of fields of different type
I need something like the child form type, but that use the data from the main form directly and permit to return the data as a tree array.

**Comment by kristijanhusak** [comment]
It accepts form type, which is basically a different form that can contain other types, also collections or child forms.
```php
class SubForm extends Form {
    public function buildForm()
    {
        $this->add('name', 'text')
               ->add('email' , 'email');
    }
}

class MainForm extends Form {
    
    public function buildForm()
    {
        $this->add('name')
                ->add('agencies', 'collection', [
                    'type' => 'form',
                    'options' => [ 'class' => 'App/Forms/SubForm']
                 ]);
    }
}
```

**Comment by mix359** [comment]
Hi,
sorry for the delay.
Yes, using that way it can be done, but I work only for that example. I've many other example in mind that could not be done simply in this way. For example, divide the field for a model into tabs or accordion. (I've tried to think all the combination of field here, and there's no way to do some of the case I've in mind)

Moreover, using a form as container you're wasting memory with the thing related to the html form, instead of having a simple container with only the necessary methods/proprieties;

Finally, in this way, you have to manually manage the data to pass at the child form.

My idea is based on some new field types. I can make it a separate package, but I need to reuse some part of code from the form object. So the only modification in this package, would be have the part of code relative to the child in a form (add, addBefore, etc) in a trait, like Childable, so I can use it too.

I would like to integrate this new fields in this package, because they add many features that I think is really useful to create advanced form (like tabs, accordion, container, etc) and also permit to use that bootstrap component.
If it's a problem have in this repository, I would create a new one that could add this new functions.
Thanks

**Comment by kristijanhusak** [comment]
In cases where you need tabs and accordions, writing only `{!! form($form) !}}` in the view is of course not enough. Tabs and accordions are JS stuff. All you need to do is split up the form into chunks and you're all done.
There are several [form helpers](http://kristijanhusak.github.io/laravel-form-builder/form/viewhelpers.html) that helps you to separate each form, child form or whatever you need, into separate blocks. When you have collection, or anything with a child elements, you can iterate over it. Each field type accepts `value` property that will be used as the value for that field. I'm still not convinced that we need additional field types for this kind of functionality. Give me one or two examples of those situations where current codebase is not enough to achieve the goal, and i'll analyze it to see if there is some solution.
