### ISSUE TITLE
How can I generate new form class in module path

### ISSUE THREAD

**Issue by tantam** [kristijanhusak/laravel-form-builder#129]
I use this package to manage module https://github.com/pingpong-labs/modules , how can I run command and it will generate new form class in specific module path as I want because I don't want it to generate form in app folder.

Any help? 
Thanks

**Comment by tantam** [comment]
FYI, now I can create a custom command for thi, but I think it will be good, if you can create some option, so that we can put new form class and namespace wherever we want

**Comment by kristijanhusak** [comment]
Hi @tantam ,
Sure, i'll add additional options. Will let you know when it's done.

**Comment by kristijanhusak** [comment]
@tantam ,

I added `path` and `namespace` options to the command. For now it's only available on `dev-master` branch. I also added some docs for the command here http://kristijanhusak.github.io/laravel-form-builder/overview/commands.html. Please test it and see if it works fine, and then let me know so i can draft a release. Thanks.

**Comment by tantam** [comment]
OK I'll check it now
btw, many thanks :D

**Comment by tantam** [comment]
FYI, It worked perfect as I desired
Thank you very much

**Comment by kristijanhusak** [comment]
@tantam 
Great! I will draft a stable release which you can use. Thanks for idea.
