### ISSUE TITLE
Repeater field type

### ISSUE THREAD

**Issue by ahmadazimi** [kristijanhusak/laravel-form-builder#131]
Hi, I use this code in many projects and I want to thank you for this great job.

One thing that I can't find here and I think it is necessary for each form builder script is Repeater. Do
you have any plan to add this type?

**Comment by kristijanhusak** [comment]
Hi,

I'm not sure what a Repeater is. Can you give some example or more thorough explanation? Thanks.

**Comment by ahmadazimi** [comment]
Repeater or repeatable form elements, i.e. an array of input elements with add/remove capabilities.

>
The repeater field allows you to create a set of sub fields which can be repeated again and again whilst editing content!
Any type of field can be added as a sub field which allows you to create and manage very customized data with ease!
> http://www.advancedcustomfields.com/resources/repeater/

For example, you want to have one or more attachment files in your form. Your field name is ```files```. You add one repeater to form, then add one file field to it. Users can duplicate it in runtime and attach more files if needed.

```php
$repeater = $form->addRepeater([
  'max' => 10,
]);

$repeater->add('name', 'text', [
  'label' => 'Employee name',
]);

$repeater->add('family', 'text', [
  'label' => 'Employee family',
]);

$repeater->add('image', 'file', [
  'label' => 'Employee photo',
]);
```

**Comment by kristijanhusak** [comment]
There is a collection type which is used exactly for that. Check the docs http://kristijanhusak.github.io/laravel-form-builder/field/collection.html

**Comment by ahmadazimi** [comment]
Cool, But in collections, user can dynamically clone them when filling the form?

**Comment by kristijanhusak** [comment]
Yes. You have example in docs, check prototype section.

**Comment by ahmadazimi** [comment]
Thank you :-)
