### ISSUE TITLE
Set value for empty_value

### ISSUE THREAD

**Issue by ahmadazimi** [kristijanhusak/laravel-form-builder#137]
Hi there,

I found that you only get html of the option tag via empty_value in select field.

```php
$this->add('languages', 'select', [
    'choices' => ['en' => 'English', 'fr' => 'French'],
    'selected' => 'en',
    'empty_value' => '=== Select language ==='
]);
```

This would be nice if we can also pass both html and value for empty_value option in the select field:

```php
$this->add('languages', 'select', [
    'choices' => ['en' => 'English', 'fr' => 'French'],
    'selected' => 'en',
    'empty_value' => [
        'html' => '=== Select language ===',
        'value' => 0
    ]
]);
```

**Comment by kristijanhusak** [comment]
Hi,

Not sure about that. Most of the time only html is enough, no need for value. If you need to provide some value for it, just use it as a part of choices array.

**Comment by ahmadazimi** [comment]
Hmm, thank you.

I did it for my curren project ;-)

**Comment by kristijanhusak** [comment]
I just don't want to complicate the code for some rare use cases, hope You understand  :)

**Comment by ahmadazimi** [comment]
Yes, of course ;)
