### ISSUE TITLE
addData, setData, getData not work inside a buildForm

### ISSUE THREAD

**Issue by angelside** [kristijanhusak/laravel-form-builder#138]
I read "methods and properties", but I can not run data methods. Somethink is wrong or I miss somethink. I tried to run, try different ways. My last hope open an issue.

http://kristijanhusak.github.io/laravel-form-builder/form/methods-and-properties.html

First, I use a chain method like document.

```php
$form = $formBuilder->create('App\Forms\Backend\UserForm', [
	'method' => 'POST',
	'url'    => route('admin.user.store')
])->setData('is_create', true);
```

Error: **Argument 1 passed to form() must be an instance of Kris\LaravelFormBuilder\Form, null given**

Ok, different use, It seems to be working...
```php
// Create form
$form = $formBuilder->create('App\Forms\Backend\UserForm', [
	'method' => 'POST',
	'url'    => route('admin.user.store')
]);
$form->setData('is_create', true);

\Debugbar::info($form->getData()); // [ "is_create" => true ]
```
**But NOT inside form field builder.**

```php
class UserForm extends Form
{
    // Disable validation errors in the form under each field
    protected $showFieldErrors = false;

    public function buildForm()
    {
        \Debugbar::info($this->getData()); // [] // :( Where is my data
    }
}
```

I am simple try show different field

```php
if ($this->getData('is_create'))
{
	$this->add('password', 'password', [
		'label' => __('fields.user.password')
	]);
}
if ($this->getData('is_edit'))
{
	$this->add('password_new', 'password', [
		'label' => __('fields.user.password')
	]);
}
```

**Comment by angelside** [comment]
Finally I find a way from README_OLD.md
https://github.com/kristijanhusak/laravel-form-builder/blob/master/README_OLD.md

```php
$form = $formBuilder->create('App\Forms\Backend\UserForm', [
	'method' => 'POST',
	'url'    => route('admin.user.store'),
	'data'   => [ 'is_create' => true]
]);
```

**Comment by kristijanhusak** [comment]
Hi @angelside ,

Thanks for reporting. You are right, it is not working, because buildForm is called in the `create` method, and after `setData` it is not called again, that's why it is not working. I will probably make that protected, because it's not working properly outside of the class. You have 2 other options:

1. The way that you found in old docs, as 'data' key in form options.
2. Or a bit cleaner and more understandable way, to pass as a 3rd argument to `create` method:
```php
$form = $formBuilder->create('App\Forms\Backend\UserForm',
    [
        'method' => 'POST',
        'url' => route('admin.user.store')
    ],
    ['is_create' => true]
);
```

**Comment by kristijanhusak** [comment]
I added small example of using data to the docs, hope it will help You and others.
http://kristijanhusak.github.io/laravel-form-builder/form/basics.html
