### ISSUE TITLE
Form horizontal

### ISSUE THREAD

**Issue by marcellorg** [kristijanhusak/laravel-form-builder#143]
No support for horizontal form?
http://getbootstrap.com/css/#forms-horizontal

```html
div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>

```

**Comment by kristijanhusak** [comment]
There is no support by default. You can easily customize templates however you want them.
Publish package content with `php artisan vendor:publish` and find views and customize them.

More info here http://kristijanhusak.github.io/laravel-form-builder/custom/configuration-basics.html

**Comment by marcellorg** [comment]
Plan to do with support horizontal form?
I get confused with the `<div class =" col-sm-10 ">`
You have some model?

```html
<div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
 </div>
```

**Comment by kristijanhusak** [comment]
No, i will not add support for horizontal form. It's hard to fit everything for everyone, so by default there is only one solution, and you can modify it as you want.

I'm not sure why you get confused.

After package installation, run:
```
php artisan vendor:publish
```

It will add some files to your project. One will be config in `config/laravel-form-builder.php`,
and second will be views in `resources/views/vendor/laravel-form-builder`.

After that, you can modify all those views in however you want, just make sure to **not** change the logic, but you can add html however you want.
