### ISSUE TITLE
form_row 

### ISSUE THREAD

**Issue by yasir1** [kristijanhusak/laravel-form-builder#145]
I want to render form row in an other form. I am using form_row but its showing error 
```Argument 1 passed to form_row() must be an instance of Kris\LaravelFormBuilder\Fields\FormField, null given, called in F:\xampp\htdocs\laraval\one\searchmysport\storage\framework\views\560ee57438557f7b44fb679b0d05179c on line 13 and defined (View: F:\xampp\htdocs\laraval\one\searchmysport\resources\views\front\ajax\category.blade.php)```

This is my code

In controller 

```
$this->data->all_child_cat = Category::whereParent($id)->lists('cat_name', 'id');
if(count($this->data->all_child_cat)  > 0) {
			$this->data->content = 1;
			$data = (array) $this->data;

		}else{

			$this->data->form = $this->form('App\Forms\laptopForm', [
				'method' => 'POST',
				'url' => route('classified.store')
			]);



			$this->data->content = 2;
			$data = (array) $this->data;
		}
		return View::make( 'front.ajax.category', $data );
```

In view 

```{!! form_row($form->title, $options = ['attr' => ['class' => 'some-input']]); !!}```

How i can do this. Please Help me.

**Comment by kristijanhusak** [comment]
I'm not sure what you try to achieve here, and also i do not understand how you want to render form_row into another form. Can you add some more code?

Also, in the if statement, when it's true (line 3. and 4.), there is no `form` created. Are you sure you didn't forget some code there?

**Comment by kristijanhusak** [comment]
@yasir1 did you manage to set up this?

**Comment by kristijanhusak** [comment]
Closing since there is no feedback.
