### ISSUE TITLE
Select list from database in form

### ISSUE THREAD

**Issue by stojankukrika** [kristijanhusak/laravel-form-builder#146]
Hi,

TNX for that nice package.

Can we use, and how to, bind list from database, from some model into form? For example, put a select list of countries from database into select item in form. How to do that?

**Comment by kristijanhusak** [comment]
Hi,

You can do that with Entity type, here's link to that in the docs http://kristijanhusak.github.io/laravel-form-builder/field/entity.html

**Comment by stojankukrika** [comment]
Wow! Great! TNX @kristijanhusak !
