### ISSUE TITLE
Automatic prototype naming

### ISSUE THREAD

**Issue by imlunek** [kristijanhusak/laravel-form-builder#158]
Hi,

I have a suggestion related to prototype naming.

I have a form with multi-level child forms and I would like the prototype naming to be automatically as __NAME0__ for first level form, __NAME1__ for second level form, __NAME3__..... and so on.

I wanted automatic naming to be so because some child form can be at any level and I want to make the replacement of the names more dynamic.

I wish to get help on this from you.

Thanks.

**Comment by kristijanhusak** [comment]
HI,

Woah...that's really hard to achieve. I'm not sure what you mean by "can be at any level"? Can you explain it a bit more?

Do you know at what level form will be before creating it?

**Comment by imlunek** [comment]
__Suppose,__
- I have a __main_form__ with multilevel nested collections (collections inside collections).
- multilevel means 3 levels(top level form, child form and sub child form) for now.
- I have a collection named __collection_form__
- the __collection_form__ will be available in 2nd level(child form) and may be available in 3rd level(sub child form) as well

---- that's why prototype_name cannot be same for the same 2nd and 3rd level __collection_form__ form.
---- So I would like to generate prototype_name dynamically like __\_\_NAME0\_\___ for 1st level form, __\_\_NAME1\_\___ for 2nd level form and __\_\_NAME2\_\___ for 3rd level form.
---- so that the same __collection_form__ at 2nd and 3rd level with get different prototype_name as __\_\_NAME1\_\___ and  __\_\_NAME2\_\___ respectively.

If this happens I think it will be very easy to write reuseable js with minimum code without defining any specific prototype_name.

**Comment by imlunek** [comment]
I am asking for above solution because I have tried a loop to update prototype_name inside $this. It worked. prototype_name updated inside $this as I expected.

But form builder displayed updated prototype_name in 1st level only and not working with sub levels. It displays default __\_\_NAME\_\___ for sub levels.

**Comment by kristijanhusak** [comment]
I'll try to find some solution during the weekend. Can you give me some code how you set up all that in the forms class and in the view? It would be really helpful. Thanks.

**Comment by imlunek** [comment]
Its like

__Level 1__  Top Level Form
       $this
            ->add('recipientCountryBudget', 'collection', [
                'type' => 'form',
                'prototype' => true,
                'options' => [
                    'class' => 'urlTo\RecipientCountryBudgetForm',
                    'label' => false,
                ],
                'label' => false,
                'wrapper' => false
            ]);

__Level 2__ RecipientCountryBudgetForm
       $this
           ->add('narrative', 'collection', [
               'type' => 'form',
               'prototype' => true,
               'options' => [
                   'class' => 'urlTo\NarrativeForm',
                   'label' => false
               ]
           ])
           ->add('budgetLine', 'collection', [
               'type' => 'form',
               'prototype' => true,
               'options' => [
                   'class' => 'urlTo\BudgetLineForm',
                   'label' => false,
               ],
               'wrapper' => [
                   'class' => 'budgetLine',
                   'data-id' => 'budgetLine'
               ],
           ]);

__Level 3__ budgetLine
        $this
            ->add('reference', 'text')
            ->add('narrative', 'collection', [
                'type' => 'form',
                'prototype' => true,
                'options' => [
                    'class' => 'urlTo\NarrativeForm',
                    'label' => false,
                ],
                 'wrapper' => [
                   'class' => 'narrative'
                 ],
            ]);

__Narrative Form__ that could be added to 2nd level and in 3rd level as well
        $this
            ->add('narrative', 'text', ['label' => 'Title', 'rules' => 'required'])
            ->add('language', 'select', [
                'choices' => $code_arr,
                'label' => 'Language'
            ]);

And in view I have called this form "$form->recipientCountryBudget."

I think this helps you more to understand exactly what I wanted to explain.

Thanks for the reply.

**Comment by kristijanhusak** [comment]
I'm not sure I understand the problem, but I think you can just add different prototype names for each collection you are adding. So for example, in **Level 2** you can add `narrative` like this:
```php
       $this
           ->add('narrative', 'collection', [
               'type' => 'form',
               'prototype' => true,
               'prototype_name' => '__NAME1__',
               'options' => [
                   'class' => 'urlTo\NarrativeForm',
                   'label' => false
               ]
           ])
```

And in **Level 3** like this:

```php
       $this
           ->add('narrative', 'collection', [
               'type' => 'form',
               'prototype' => true,
               'prototype_name' => '__NAME2__',
               'options' => [
                   'class' => 'urlTo\NarrativeForm',
                   'label' => false
               ]
           ])
```

That should give you proper prototype name every time. Did I missed something?

**Comment by imlunek** [comment]
This way happens to be a hard-coded one and will generate problems to me because:
- I have many places to add prototype_name.
- Lets assume I do that way but we should take in mind that the same level 2 form (with narrative collection  added) may also be at level 3. In that case, in level 2 it will be __\_\_NAME1\_\___ and in level 3 it will be the same __\_\_NAME1\_\___.

That's why we need auto-naming.

**Comment by imlunek** [comment]
Hi,
I would like to know if you have something regarding this issue.

**Comment by kristijanhusak** [comment]
Hi, i wasn't near computer these days, will check it tomorrow.

**Comment by imlunek** [comment]
Hi, Have figured out anything?

**Comment by kristijanhusak** [comment]
Hi,

I tried to find some solution, but none of those worked. It requires some good portion of brainstorming/developing to add that functionality directly to the package. Also, it will cause minor BC break if added, because default prototype name is changed to `__NAME{number}__`. Can be set up to be optional though. 

This is really a rare case where something like this is needed. Since i'm short on time, i'll have to put this on hold until more people requests it, because it takes some time to add it.

For now, try to find some other solution through manual prototype naming.

**Comment by imlunek** [comment]
Hi,

Thanks for the support. For now, I have achieved it with javascript.

**Comment by kristijanhusak** [comment]
Great!
