### ISSUE TITLE
Laravalid support

### ISSUE THREAD

**Issue by joelcuevas** [kristijanhusak/laravel-form-builder#159]
It would be nice to be able to get all the rules in a form like:

```php
$rules = $form->getRules();
```
This would allow to pass the rules to other plugins as [bllim/laravalid](https://github.com/bllim/laravalid) for client side validation.

Greetings!

**Comment by kristijanhusak** [comment]
You can get all rules from form with that exact method https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Form.php#L969 . Am I missing something here?

**Comment by joelcuevas** [comment]
Ahmnm... Probably it was me who was missing something. 

You are right, the method exists and it's useful. Thank you!
