### ISSUE TITLE
Child form's set model

### ISSUE THREAD

**Issue by devthiagolino** [kristijanhusak/laravel-form-builder#162]
How to on the edit form, to set model for the child forms?

**Comment by kristijanhusak** [comment]
There are 2 posibilities.

Let's use these forms for both examples:
```php
<?php namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class AddressForm extends Form {

    public function buildForm()
    {
        $this->add('street', 'text');
    }
}

class UserForm extends Form {

    public function buildForm()
    {
        $this
            ->add('name', 'text')
            ->add('address', 'form', [
                'class' => 'App\Forms\AddressForm'
            ]);
    }
}

```

**First option (Recommended and simpler)**:

Pass from parent form as a model when creating in controller:

```php

FormBuilder::create('App\Forms\UserForm', [
    'model' => [
        'address' => Address::find($userId)
    ]
]);
```

**Second option**:

Pass as data to parent form and handle it from there:

```php
FormBuilder::create('App\Forms\UserForm', [
    'method' => 'POST'
], [
    'addressModel' => Address::find($userId)
]);
```

And then in UserForm:

```php
    public function buildForm()
    {
        $this
            ->add('name', 'text')
            ->add('address', 'form', [
                'class' => 'App\Forms\AddressForm',
                'formOptions' => ['model' => $this->getData('addressModel')]
            ]);
    }
```

Hope I helped.

**Comment by devthiagolino** [comment]
Got it. As you do when you need to use the same form in the editing action? Or do you have a form for each create and edit action?

**Comment by kristijanhusak** [comment]
I always use the same form. There is no need to create separate form for different actions.

**Comment by devthiagolino** [comment]
Could you show me an example of how you do?
I pray the following:

<code>
class ClientForm extends Form
{
  public function buildForm()
  {
      $this
      ->add('name', 'text', [
        'rules' => 'required|min:5',
        'label' => 'Cliente'
      ])
      ->add('financial', 'form', [
        'class' => $this->formBuilder->create('App\Forms\ClientFinancialForm')
      ]);
  }
}
</code>

When I'm in the editing action I change the form:

<code>
$form = $formBuilder->create($this->formClass, [
      'method' => 'put',
      'url' => route($this->route . '.update', ['id' => $id]),
      'model' => $record
    ])
      ->modify('config', 'form', [
        'class' => 'App\Forms\ClientConfigForm',
        'model' => [
          'config' => $record->config
        ]
      ]);
</code>

**Comment by kristijanhusak** [comment]
That's something i would do also. You can just change `modify()` with `add` since you are not modifying any fields in the form, just adding it (if you didn't miss some fields in the ClientForm).

**Comment by ghprod** [comment]
```php
FormBuilder::create('App\Forms\UserForm', [
    'model' => [
        'address' => Address::find($userId)
    ]
]);
```

This one works for me .. Thanks :+1:

**Comment by kristijanhusak** [comment]
Ok great, closing.
