### ISSUE TITLE
Form renderJSON

### ISSUE THREAD

**Issue by ikostic** [kristijanhusak/laravel-form-builder#163]
Hi,

i am very satisfied with package, working very nice.

I have one strange case, would like to export form configuration and attached data as JSON. I would like to create some AngularJS template system. I experimented with render options and tried to catch the form object items, but stuck. Do you have some quick idea?

Thanks,

Igor

**Comment by kristijanhusak** [comment]
Hi,

Can you give me an example of JSON output  you would like to get, also with the example Form class? Probably something can be figured out, i'm just not sure what configuration and data  you need from the form.

**Comment by ikostic** [comment]
Hi,

i was thinking to automatize form building for AngularJS in the same time i am building forms for Laravel project. I analyzed form building for AngularJS and so far i recognized http://www.forms-angular.org/ as one of best solutions. They are using JSON schema configuration for building of forms. I am wondering if we can create JSON output of created Form class via your package so we can use it later on AngularJS project.

**Comment by kristijanhusak** [comment]
Hi,

I think you can achieve something like this, but you definitely need to write some middleware that will do the "translation" of these options to js. After you create a form, you can get all fields with `$form->getFields()`, iterate over them, and for each get `$field->getOptions()`. This should have all possible options that you need. Give it a try, and let me know if i can help somehow.

**Comment by nstojanovickg** [comment]
Hi, I am trying to get child form. This is part of my code:
```
$contactForm = $formBuilder->create('App\Forms\ContactForm', [
			'model' => $contactArr
		]);

$form_fields = $contactForm ->getFields();
foreach ($form_fields as $idx => $form_field) {
...
$form_field->getForm();
}

```
I am receiving error message:
Call to undefined method Kris\\LaravelFormBuilder\\Fields\\InputType::getForm()

this is how I create field:

```
$this->add('ContactAddresses', 'form',['class' => $this->formBuilder->create('App\Forms\ContactAddressForm'), 'model' => []]);
```

Can you help me...

**Comment by kristijanhusak** [comment]
@nstojanovickg 
Does your ContactForm contain all child forms?
only `form` type has method `getForm()`.
If you need specific field from ContactForm you can get it like this:

```php
$contactForm = $formBuilder->create('App\Forms\ContactForm', [
            'model' => $contactArr
        ]);

$myChildForm = $contactForm->my_child_form;

// Or with method

$childForm = $contactForm->getField('my_child_form');

$childForm->getForm();
```

No need to loop through all fields.

**Comment by nstojanovickg** [comment]
Strange, but that works :) thanks a lot

No, not all fields are child forms. I did this before
```
if($form_field->getType() == 'form')
    $form_field->getForm();
```

And now:
```
if($form_field->getType() == 'form')
    $contactForm->getField($form_name)->getFields();
```

Thanks again
