### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by imlunek** [kristijanhusak/laravel-form-builder#165]
Is there any validation way of laravel form builder to validate a field with name __form[0]childForm[0]field__ and __form[0]childForm[1]field__ as __form.childForm.field__ while writing rules?

**Comment by kristijanhusak** [comment]
Not really. That would break validation. Why you need something like that?

**Comment by imlunek** [comment]
While validating specific fields in the nested forms with add more feature, we had to write nested foreach loop for adding rules which looks kinda ugly and not much readable.

**Comment by kristijanhusak** [comment]
@imlunek there will be new array validation in version 5.2 https://twitter.com/taylorotwell/status/659828338760925184 . Not sure how it will work, but i think it will help for problems like these.

**Comment by imlunek** [comment]
It will be lot easier if we had the array validation. Thanks for the reply.
