### ISSUE TITLE
Missing alias for laravel-form-builder

### ISSUE THREAD

**Issue by mattzuba** [kristijanhusak/laravel-form-builder#168]
In the FormBuilderServiceProvider, there's an alias for the form-helper, but not the form-builder.  This causes multiple instances of the FormBuilder to be created every time it's injected somewhere.

$this->app->singleton should also probably be used rather than bindShared (deprecated)

**Comment by kristijanhusak** [comment]
Thanks for reporting. I fixed it in the latest release (1.6.31).
