### ISSUE TITLE
Expanded, multiple choice fields.

### ISSUE THREAD

**Issue by ReactionJordan** [kristijanhusak/laravel-form-builder#169]
Hello, been trying to add a multiple checkbox field in the form builder but ran into some issues. It seems that when both multiple and expanded are true, it looks at the choices element and uses ucfirst. However this is an array so it errors out.

For example:

```
$this->add('roles', 'choice', [
	'label' => 'Roles',
	'choices' => Role::all()->lists('name', 'id'),
	'selected' => function() use($model) {
		if (empty($model)) {
			return null;
		}

		return \DB::table('role_users')->where('user_id', '=', $model->id)->lists('role_id');
	},
	'multiple' => true,
        expanded' => true
]);
```

would error out complaining that `ucfirst` cannot be done on an array.

**Comment by ReactionJordan** [comment]
Looks like although `Role::all()->lists('name', 'id')` was returning the array I was looking for, it was different then what the this package was looking for. Switching it to `\DB::table('roles')->lists('name', 'id')`. Seems to have solved it.

I don't think this is an issue maybe just me misunderstanding it.

**Comment by kristijanhusak** [comment]
From Laravel 5.1 `lists` return a collection Check docs http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0

Also, I think you should do `Role::lists('name', 'id')->all()`, because that uses Eloquent, and `Roles::all()->lists('id', 'name')` does listing with Collection.

**Comment by ReactionJordan** [comment]
I did check it and it seemed to return what I was expecting. But yeah your right, this was because of confusion on my part, so I closed it as soon as I seen it was fixed though using a different way to get the array.

Nice package by the way, keep thinking i need to make custom fields, then find out through a few settings i can get away without using one.

**Comment by kristijanhusak** [comment]
Most of the things are explained in the docs http://kristijanhusak.github.io/laravel-form-builder/
Also you can try searching through issues, many things also hide there :)
