### ISSUE TITLE
Idea of putting asterisk form required Fields.

### ISSUE THREAD

**Issue by imanghafoori1** [kristijanhusak/laravel-form-builder#173]
In case of defining the field name like : 
```
 $this->text('username *');
// or
 $this->text('username*');

```
it becomes automatically a required field.
I have done such a thing before.
How do you think ?! 
You Agree?

**Comment by kristijanhusak** [comment]
No need for that, there is an option `required` which adds an attr `required` to field and a class `required` to the label for it, [this line](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/FormField.php#L226). Asterisk can be added via css easily.

**Comment by imanghafoori1** [comment]
Note that the asterisk will not be included in the output html.
I mean this :
```
 $this->text('username *');
```
will result in this :
```
<label>username</label>
<input name='username' type='type' required />
```

the Idea is to append the '|required' to the rules sting before parsing it.

**Comment by kristijanhusak** [comment]
I don't like that idea, first parameter is strictlly name of the field, and i don't want to mess with it. Adding `required => true` to options, or `required` to rules is pretty fine.
