### ISSUE TITLE
Empty collection still displays form elements

### ISSUE THREAD

**Issue by koichirose** [kristijanhusak/laravel-form-builder#178]
I have a Post model that has a photos() collection.

If the $post doesn't have any photos, the form will still display an empty text input (caption) and an empty image.
I think this is an intended behaviour, so that users can add new photos, but I'd like to disable it.

This is because I use a button to upload new photos (with a javascript etc.), then the 'photos' form element is needed when updating an existing $post if the user wants to add a caption or delete the photo.

I know I can dynamically add the 'photos' element if the post has photos, but I was looking for something more elegant.
How can I fix it?

**Comment by kristijanhusak** [comment]
I haven't thought about that, but it's definitely required. So you basically just need to be able to set up something so it doesn't show that single collection entry that is empty by default?

**Comment by koichirose** [comment]
Yes, that's correct. Can it be done? I'd be glad to help you with testing.

Thanks

**Comment by kristijanhusak** [comment]
Yes, it can. I will do it these these days when i catch some time, and let you know to test it out. Thanks.

**Comment by koichirose** [comment]
Ok, thank you!

Here's some code anyway:
```php
<?php
//parent form
public function buildForm()
    {
                $this
                       //other fields
                       ->add('photos', 'collection', [
                                'type' => 'form',
                                'options' => [
                                        'class' =>  'App\Forms\PhotoForm',
                                        'label' => false,
                                ],
                                'label' => false,
                        ])
                        ->add('Save', 'submit', [
                                'attr' => ['class' => 'btn btn-primary']
                        ])
                        ;
    }

//photoForm
public function buildForm()
    {
                $this
                        ->add('caption', 'text', [
                                'label' => false,
                                'wrapper' => false,
                        ])
                        //need to add a <img> tag here
                        ->add('marked_for_deletion', 'checkbox', [
                                'label' => 'Delete',
                                'wrapper' => ['class' => ''],
                                'property' => 'id',
                                'name' => 'photos[deletable][]',
                        ])
                        ->add('id', 'hidden')
                        ;
    }
```

**Comment by kristijanhusak** [comment]
@koichirose 
I added it to dev-master, so try pulling that in and add `empty_row` => false to options, like this:

```php
    public function buildForm()
    {
        $this
            //other fields
            ->add('photos', 'collection', [
                'type' => 'form',
                'options' => [
                    'class' =>  'App\Forms\PhotoForm',
                    'label' => false,
                ],
                'label' => false,
                'empty_row' => false // This was added
            ])
            ->add('Save', 'submit', [
                'attr' => ['class' => 'btn btn-primary']
            ]);
    }

```

Let me know if it's working.

**Comment by koichirose** [comment]
@kristijanhusak it works flawlessly, thank you very much!
Closing this.
