### ISSUE TITLE
how to use data

### ISSUE THREAD

**Issue by amin101** [kristijanhusak/laravel-form-builder#179]
im trying to pass data from controller to form class , such as select form items ,it seems i should use data form option. how can  i send data to form?
for example how should i use 'some_dummy_data'  in form class?

<?php
$model = User::find(1);
$formOptions = [
    'method' => 'POST',
    'url' => action('AuthController@postLogin'),
    'class' => 'form-horizontal',
    'template' => 'user.form'                       // Template used for the main form layout
    'model' => $model,                              // Not passed to view, just used in form class
    'name' => 'users',                              // Not passed to view, just used in form class
    'data' => ['some_dummy_data' => 'some text'],   // Not passed to view, just used in form class
];

**Comment by kristijanhusak** [comment]
```php
class MyForm extends Form
{

    public function buildForm()
    {
        $data = $this->getData('some_dummy_data'); // "some text"
    }
}
```
