### ISSUE TITLE
Captcha snippet: using with anhskohbo/no-captch

### ISSUE THREAD

**Issue by joevallender** [kristijanhusak/laravel-form-builder#180]
Quick snippet for people search the Google or the issues for using recaptcha nocaptcha https://github.com/anhskohbo/no-captcha

    ->add('g-recaptcha-response', 'hidden', [
      'rules' => 'required|captcha'
    ])
    ->add('captcha', 'static', [
      'tag' => 'div', 
      'label' => false, 
      'value' => app('captcha')->display()
    ])

Feel free to close this, just thought it might be helpful

**Comment by kristijanhusak** [comment]
Thanks! I will add it to docs.

**Comment by njbarrett** [comment]
Thanks for this!

**Comment by audetcameron** [comment]
did this ever make it in the docs?  It was a huge help. Thanks! :)

**Comment by audetcameron** [comment]
ever have it where it actually just prints the code instead of rendering the html?
```
<div data-sitekey="mysitekeyishere" class="g-recaptcha"></div>
```
![image](https://user-images.githubusercontent.com/6738453/62877025-33e1f800-bcf4-11e9-8ff6-1c12db2c590a.png)

**Comment by audetcameron** [comment]
> ever have it where it actually just prints the code instead of rendering the html?
> 
> ```
> <div data-sitekey="mysitekeyishere" class="g-recaptcha"></div>
> ```
> 
> ![image](https://user-images.githubusercontent.com/6738453/62877025-33e1f800-bcf4-11e9-8ff6-1c12db2c590a.png)

<?php endif; ?>

fixed it by changing this line in static.php
```
    <<?= $options['tag'] ?> <?= $options['elemAttrs'] ?>><?= e($options['value']) ?></<?= $options['tag'] ?>>
```
to this
```
    <<?= $options['tag'] ?> <?= $options['elemAttrs'] ?>><?= $options['value'] ?></<?= $options['tag'] ?>>
```
