### ISSUE TITLE
ignore duplicated fields on update

### ISSUE THREAD

**Issue by amin101** [kristijanhusak/laravel-form-builder#181]
im trying to use `unique:table,column,except,idColumn` in form to ignore duplicated field on update.
but `$this->getDate()` works only on rendering form but not on recieving form data

so how could i implement something like
 `->add('title', 'text',['rules'=>'required|unique:posts,title,'.$this->getData('id')])`
?

**Comment by kristijanhusak** [comment]
`$this->getDate()` ?

Can you please paste the code you are using to achieve it?

**Comment by amin101** [comment]
this is my controller action : 
`
    public function edit($slug,FormBuilder $formBuilder)
    {

        $post = Post::where('slug',$slug)->first();

      $form = $formBuilder->create('App\Forms\CreatePostForm',[
            'method' => 'put',
            'url'=> route('post.update',['post' => $post->id ]),
            'model' => $post,
          'data' => ['id'=> $post->id]
        ]);
      return view('posts.edit',compact('form'));
    }
`

and blew is form builder class:

`
class CreatePostForm extends Form
{
    public function buildForm()
    {
       // dd($this->getData('id'));

        $this
            ->add('title', 'text',['rules'=>'required|unique:posts,title,'.$this->getData('id')])
            ->add('slug', 'text',['rules'=>'required'])
            ->add('body', 'textarea',['attr'=>['class'=>'ckeditor']])
            ->add('photo', 'text',['attr'=> ['id'=>'url','onclick'=>"openPopup()"]])
            ->add('save','submit',['attr'=>['class'=>'btn btn-primary']]);
    }
}
`

i want to ignore validating "unique" rule on title when updating a post. laravel has offer following syntax:
`unique:table,column,except,idColumn`
it  is simple if i do validation in controller as i have access to post id, but i dont know how to implement it throuth form class .

**Comment by kristijanhusak** [comment]
Just reinitialize the form in the PUT method in controller where the form is submitted, i guess it's called `update()`:

```php
public function update($slug,FormBuilder $formBuilder)
{

    $post = Post::where('slug',$slug)->first();

    $form = $formBuilder->create('App\Forms\CreatePostForm',[
        'model' => $post,
        'data' => ['id'=> $post->id]
    ]);

    if (!$form->isValid()) {
        return redirect()->back()->withErrors($form->getErrors())->withInput();
    }

    // Do saving...
}

```
