### ISSUE TITLE
Call to a member function addCustomField() on null

### ISSUE THREAD

**Issue by zxishere** [kristijanhusak/laravel-form-builder#182]
I followed the steps in laravel 5.1 for some Custom fields:
http://kristijanhusak.github.io/laravel-form-builder/custom/customfields.html 
but it looks like something went wrong:Call to a member function addCustomField() on null

i also tried still not work
```
    public function __construct()
    {
        $this->addCustomField('datetime', App\Forms\Fields\DatetimeType::class);
    }
```
is document need update or maybe my code some wrong?

**Comment by zxishere** [comment]
tryed many times, it works in buildForm function.
found in README_OLD.md

<?php namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

```
class PostForm extends Form
{
    public function buildForm()
    {
        $this->addCustomField('datetime', 'App\Forms\Fields\DatetimeType');

        $this
            ->add('title', 'text')
            ->add('created_at', 'datetime')
    }
}
```

**Comment by kristijanhusak** [comment]
@zxishere
Thanks for reporting, i'll update the docs.

You can also add it to config file that is published.
