### ISSUE TITLE
Data bind problem after update 1.6.20 to 1.6.31

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#185]
Hi,
I have problem with data bind (I use value instead default value).

I have object with data and make setModel but data are not binded. There was some serious changes? Because in doc all looks same.

It worked perfect before.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
below is result from getModel method

```
object(stdClass)[557]
  public '_id' => 
    object(MongoId)[562]
      public '$id' => string '5623d3fd6f56d7ca45ee26c9' (length=24)
  public 'group' => string '55f29bc66f56d7c94a954160' (length=24)
  public 'type' => string 'text' (length=4)
  public 'is_translate' => int 0
  public 'multiple' => int 1
  public 'search' => string 'select' (length=6)
  public 'name__pl' => string 'Częstotliwość [Hz]' (length=21)
  public 'name__en' => string '' (length=0)
  public 'label__pl' => string 'Częstotliwość [Hz]' (length=21)
  public 'label__en' => string '' (length=0)


```

data exists 

in form I have

```
$this
            ->add('_id', 'hidden')
            ->add('group','choice',['choices'=>$this->getGroups(),'extended'=>false,'label'=>trans('common.group')])
            ->addTrans('name', 'text',['label'=>trans('common.name')],false)
            ->add('is_translate', 'checkbox',['value'=>1,'label'=>trans('products.is_translate')])
            ->add('type','choice',['choices'=>$this->getTypes(),'extended'=>false,'label'=>trans('products.type')])
            ->addTrans('label', 'text',['label'=>trans('common.label')],false)
            ->add('multiple', 'checkbox',['value'=>1,'label'=>trans('products.multiple')])
            ->add('search', 'choice',['choices'=>$this->getSearch(),'extended'=>false, 'label'=>trans('products.search_type')])
            ->add('submit','submit',['label'=>trans('common.save'),'attr'=>['class'=>'btn btn-sm pull-right btn-primary']]);
```

addTrans it method which add many fields from table like name__pl, name__en from array ['en','pl'] and this fields are generated correct.

**Comment by kristijanhusak** [comment]
Hi,

I think nothing drastically changed.

Are you using custom views? Content should be same, but structure is changed (extracted to partials). Check it here https://github.com/kristijanhusak/laravel-form-builder/tree/master/src/views

Also, can you give me code where you initialize form? Did you try using `model` key instead of `setModel` ?
```php
$formBuilder->create('App\Forms\Myform', ['model' => $myModel]);
```

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
I call to this form by

```
$form = $formBuilder->create('\App\Forms\Backend\Attribute', [
            'url' => url(\App::getLocale() .
                '/backend/category/edit-attribute'), 'model' => $formData
        ]);
    
```

and 

```
{!! form($form) !!}

```
in view.

When I use key model instad setModel I have data for part fields. Name__pl name__en still is empty

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak but you are right if I remember well I had to overwrite some teplates. Probably are incompatibile with current structure.

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski try temporarily renaming folder in views to something else, so package will use default ones. If it works, than it's problem with your views.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak I used your original templates same result. Below I attach var_dump for 
name__pl (doesn't work)
label__pl (works correctly)

![zrzut ekranu 2015-11-30 o 14 01 25](https://cloud.githubusercontent.com/assets/6404533/11472180/1dcbf9f6-976b-11e5-8ed9-2c50001a6d43.png)
![zrzut ekranu 2015-11-30 o 14 04 00](https://cloud.githubusercontent.com/assets/6404533/11472199/3baaf60c-976b-11e5-850f-0578f268a67a.png)

**Comment by kristijanhusak** [comment]
That is really strange. Both dumps are almost same, and both have `value` properly.

Try dumping this in the controller:

```php
$form = $formBuilder->create('\App\Forms\Backend\Attribute', [
            'url' => url(\App::getLocale() .
                '/backend/category/edit-attribute'), 'model' => $formData
        ]);

var_dump($form->getField('name__pl')->getName())
var_dump($form->getField('name__pl')->getValue());

var_dump($form->getField('label__pl')->getName())
var_dump($form->getField('label__pl')->getValue());
```

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak result below
![zrzut ekranu 2015-11-30 o 14 18 29](https://cloud.githubusercontent.com/assets/6404533/11472496/4b385d42-976d-11e5-84ff-485886ed0f70.png)
same value....very weird

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 
`name__pl` doesn't have value, or it's wrong? According to your model those two values are also same in the db https://github.com/kristijanhusak/laravel-form-builder/issues/185#issuecomment-160608503

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak doesn't have value. I'll try something else and let you know.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak I see that problem is when I use collection.... then value is empty. I'm not overwrite collection.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
![zrzut ekranu 2015-12-01 o 06 59 48](https://cloud.githubusercontent.com/assets/6404533/11493505/73078d84-97f9-11e5-8b59-459403a86007.png)
![zrzut ekranu 2015-12-01 o 07 01 24](https://cloud.githubusercontent.com/assets/6404533/11493506/73342d08-97f9-11e5-84de-710d8e286eee.png)
![zrzut ekranu 2015-12-01 o 07 01 45](https://cloud.githubusercontent.com/assets/6404533/11493507/73357082-97f9-11e5-8457-41d849c04df1.png)


You can see variable var dump, options in text field for this field and also controller where I assign data.

This form is child

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak I attach 
![zrzut ekranu 2015-12-01 o 07 23 23](https://cloud.githubusercontent.com/assets/6404533/11493782/7e139206-97fc-11e5-9de2-2f3555f97815.png)

configuration for this field what is in my form builder.

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski you cannot use collection `text` field type. If you need to have array values, than you must use `collection` type. Can you give me full dump of your model?

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak It was short in mind. There is

```
$this->add('name', 'collection', $opt);

```

For now I removed data array and collection works. It looks like earlier data was overwrite by assigned model, not not.

It works so far but I have not checked all forms from old version. Please don't close this ticket.

Thanks, 
Jarek

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski ok, check it out thoroughly and let me know if everything is working ok.

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski did you manage to test this out properly?
