### ISSUE TITLE
File uploads, using compose method, then validator not working

### ISSUE THREAD

**Issue by btamas86** [kristijanhusak/laravel-form-builder#186]
Sorry, my English is not too good.

So, if I create a form with compose, then the validator does not work. Example:
```php
class BlogEditForm extends BaseBlogForm
{
    public function buildForm()
    {
        ...
        $this->compose(BlogImageEditForm::class);
        ...
    }
}

class BlogImageEditForm extends Form
{
    public function buildForm()
    {
        $this->addPostImage();
    }

    protected function addPostImage()
    {
        return $this->add('post_image', 'file', [
            'rules' => 'max:2048|mimes:jpg,jpeg,png,gif',
        ]);
    }
}
```

The validator object data are incorrect:
```
Validator {#688 ▼
  #data: array:19 [▼
    ...
    "post_image" => "wallp_2560x1600_53.jpg"
    ...
  ]
  #files: []
  #rules: array:8 [▼
    ...
    "post_image" => array:2 [▼
      0 => "max:2048"
      1 => "mimes:jpg,jpeg,png,gif"
    ]
  ]
}
```

But, if i change my form class to this one, then its working fine:
```php
class BlogEditForm extends BaseBlogForm
{
    public function buildForm()
    {
        ...
        $this->add('post_image', 'file', [
            'rules' => 'max:2048|mimes:jpg,jpeg,png,gif',
        ]);
        ...
    }
}
```

**Comment by kristijanhusak** [comment]
Why is validator object data incorrect? I tested it out and it works fine.

Post me the code you are using to validate the form.

**Comment by btamas86** [comment]
I use only the exact same code what im pasted here. My problem is, that if im using compose when I try to add a file field, then in the validator, the content will be a string. The problem is that the Laravel validator is waiting for a class, not a string. See:
```php
// vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1295
protected function isAValidFileInstance($value)
{
    if ($value instanceof UploadedFile && ! $value->isValid()) {
        return false;
    }

    return $value instanceof File;
}
```

But when I use the code without compose, then the field works fine because the value will be a class and it works fine.

In this example, you can see that the validator is empty after I uploaded the file.
```
Validator {#688 ▼
  #files: [] // This is empty, but I uploaded the file
}
```

**Comment by kristijanhusak** [comment]
Oh, I understand. I thought validation is not working.

Problem is that `enctype="multipart/form-data"` was not added when using compose. Pull in latest `dev-master` branch and try it out, i fixed it.

**Comment by btamas86** [comment]
Thank you so much. It's working now! :)

**Comment by dopyoman** [comment]
what's the easiest way to force add enctype="multipart/form-data" to the form? I have a custom image field and template

`class PortfolioForm extends Form {

    public function buildForm()
    {
        $this
            ->add('photo_name', 'image')
            ->add('title', 'text')
            ->add('sub_title', 'text')
            ->add('client', 'text')
            ->add('date', 'date')
            ->add('service', 'text')
            ->add('description', 'textarea', ['attr' => ['rows' => 3]])
            ->add('submit', 'submit',
                ['label' => 'Save form',
                 'attr'  => ['class' => 'btn btn-primary btn-raised']])
            ->add('clear', 'reset',
                ['label' => 'Clear form',
                 'attr'  => ['class' => 'btn btn-default btn-raised']]);
    }`

In the controller 

`public function create(FormBuilder $formBuilder)
    {
        $data['form'] = $formBuilder->create('PortfolioForm', [
            'method' => 'POST',
            'url'    => url('portfolio'),
        ]);

        return view('back.portfolios.create', compact('data'));
    }`

**Comment by kristijanhusak** [comment]
@dopyoman just add `files => true`.

```php
`public function create(FormBuilder $formBuilder)
{
$data['form'] = $formBuilder->create('PortfolioForm', [
'method' => 'POST',
'url' => url('portfolio'),
'files' => true
]);
```
