### ISSUE TITLE
Add option to create own validation rules

### ISSUE THREAD

**Issue by cisekdan** [kristijanhusak/laravel-form-builder#189]
Hello,

I think it would be great to have an option to create own validation rules without modifying the base class. It could be done by assigning a subclass of RulesParser to field.

Thanks,
cisekdan

**Comment by kristijanhusak** [comment]
Hi,

Are you talking about RulesParser, that handles the client side validation, or Laravel ones?

**Comment by kristijanhusak** [comment]
Closing since there is no response.
