### ISSUE TITLE
Request instance in form helper singleton has different Illuminate\Http\Request object

### ISSUE THREAD

**Issue by StefanPrintezis** [kristijanhusak/laravel-form-builder#192]
```php
public function testOrganizationsCreate() {
  $name = 'organisation name';
  $this->visit('/organizations/create')
          ->type($name, 'name')
          ->press('Save')
          ->seeInElement('div.organization-name h2', $name);
}
```
@GET
.formhelper.requesthash:
string(32) "0000000033956ca30000000030ec80c9"
@POST
Fformhelper.requesthash:
string(32) "0000000033956cf60000000030ec80c9" 
request:
string(32) "0000000033956cc60000000030ec80c9" <-- action store request hash (Illuminate\Http\Request $request)
app.request:
string(32) "0000000033956cc60000000030ec80c9"<-- the apps request hash

When I call the following function the getRequest gets the Request instance from the formhelper but it has a different hash and the values are not found.
Note this only happens when running phpunit.
```php
use Kris\LaravelFormBuilder\Form as BaseForm;

class Form extends BaseForm {

  public function getFieldValues() {
    $values = [];
    $request = $this->getRequest();
    foreach ($this->getFields() as $field => $type) {
      if ($request->exists($field)) {
        $values[$field] = $request->$field;
      }
    }
    return $values;
  }
}
```

**Comment by StefanPrintezis** [comment]
My temporary fix is:
$form->setRequest(app('request'));

**Comment by kristijanhusak** [comment]
We've already have that issue https://github.com/kristijanhusak/laravel-form-builder/issues/149.
manually setting the request in controller before validation should do the work.
I'll try to fix it, to avoid problems like this. Thanks for reporting.

**Comment by kristijanhusak** [comment]
@StefanPrintezis I fixed it. Pull in `dev-master` and try it out.

**Comment by StefanPrintezis** [comment]
It seems to be working correctly now. Thanks!
