### ISSUE TITLE
Incompatibility with LaravelCollective\HtmlBuilder

### ISSUE THREAD

**Issue by Lykegenes** [kristijanhusak/laravel-form-builder#197]
I get this error : 
```
Type error: Argument 2 passed to Collective\Html\HtmlBuilder::__construct() 
must implement interface Illuminate\Contracts\View\Factory, none given, called in 
/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/
FormBuilderServiceProvider.php on line 100
```

Adding the dependency myself in `Composer.json` and setting it up in `config/app.php` solves the issue.

**Comment by kristijanhusak** [comment]
It's working on dev-master, but i didn't publish stable version yet. Will do that now.

**Comment by kristijanhusak** [comment]
Do a composer update, i just publishes new version `1.6.40`. Thanks for reporting.
