### ISSUE TITLE
Injecting model to sub-forms?

### ISSUE THREAD

**Issue by Weeblewonder** [kristijanhusak/laravel-form-builder#20]
Is this possible at the moment?
Or is it sensible acheivable beyond setting a model variable on the form which is passed to the sub-form?

**Comment by Weeblewonder** [comment]
Realised theres not much need to build in more magic to try and automatically inject models based on array keys etc.

Just pass the model in as extra data to the create method and then use `getData('modelKey')` to then pass it to the child form.

**Comment by kristijanhusak** [comment]
Agree :)
