### ISSUE TITLE
After update get error

### ISSUE THREAD

**Issue by SergeyMiracle** [kristijanhusak/laravel-form-builder#203]
htmlentities() expects parameter 1 to be string, object given (View: /usr/local/var/sites/actualno/resources/themes/admin/views/block/form.blade.php)

Change log not helping

**Comment by kristijanhusak** [comment]
What version are you using?

**Comment by SergeyMiracle** [comment]
Latest version - 1.6.40, 1.6.31 works perfectly. All i done is just composer update :smiley:

**Comment by kristijanhusak** [comment]
I'll publish new version today, since it was fixed, but not tagged.

**Comment by kristijanhusak** [comment]
I published new version (1.6.41), update, test, and close issue if everything is ok. Thanks for reporting.

**Comment by SergeyMiracle** [comment]
Thx, working good :+1:
