### ISSUE TITLE
default_value not handled properly for CheckableTypes

### ISSUE THREAD

**Issue by hackel** [kristijanhusak/laravel-form-builder#204]
If I set a default_value for a checkbox field to true, and my model has attribute==false, the checkbox gets checked anyway, no matter what.  Looks like it's happening [here](../blob/master/src/Kris/LaravelFormBuilder/Fields/FormField.php#L444), but even if I remove `$value === false`, it still is getting checked.  I'm assuming this will need to be overridden in CheckableType.  I'll debug further if I get some free time this week.

Edit: Figured it out, it's also checking the value [here](../blob/master/src/Kris/LaravelFormBuilder/Fields/FormField.php#L150).  I changed it to `if (! $value && $value !== false && $defaultValue)` and that seemed to due the trick, but not sure if that is 100% backward compatible and might not trip someone up.

**Comment by kristijanhusak** [comment]
I'm working on it, thanks for reporting. Will let you know when it's finished.

**Comment by kristijanhusak** [comment]
Fixed in latest version (1.6.42). Thanks for reporting.

**Comment by hackel** [comment]
Brilliant, that solution makes even more sense.  Thanks!
