### ISSUE TITLE
Data not being passed to child form correctly

### ISSUE THREAD

**Issue by FourStacks** [kristijanhusak/laravel-form-builder#205]
Hi @kristijanhusak 

So I've been spinning my wheels on something that should be really simple and that I've done successfully on another project not problem.  It's pretty simple - I just want to pass some data to a child form but no matter what I try, the data keeps showing up as null in the child form

I've stripped back my working code to the point where I'm just copying your example in the docs so my parent form looks like this:

    class CreateReviewForm extends Form
    {
        public function buildForm()
        {

            $this->add('gender', 'form', [
                'class' => CreateReviewMetricGroupForm::class,
                'formOptions' => [],
                'data' => ['metric' => 'hello']
            ]);

        }
    }

and my child form looks like this:

    class CreateReviewMetricGroupForm extends Form
    {
        public function buildForm()
        {
            var_dump($this->getData('metric'));
        }
    }

This outputs to screen the following:

null
string 'hello' (length=5)

If I were to use this data in a field e.g:

    $this->add('test', 'text',[
        'label' => $this->getData('metric')
    ]);

This works as expected.  However if I try to pass a collection through as the data, I similarly get null in the var_dump output in the child form followed by the actual collection instance e.g.:

null
object(Illuminate\Database\Eloquent\Collection)[216]

If I try to iterate over this data it doesn't work as the data itself seems to be 'masked' by the null which preceeds it.

Interestingly if I var_dump `$this`, I get two child form instances - the first does not contain the data and the second does

I'm fairly certain I'm not doing anything too stupid but I'd be happy to be proved wrong at this point!

**Comment by kristijanhusak** [comment]
Thanks for reporting, I'm working on it. Will let you know when it's fixed.

**Comment by kristijanhusak** [comment]
Fixed in latest version (1.6.42). Thanks for reporting.
