### ISSUE TITLE
Automatic translation of labels

### ISSUE THREAD

**Issue by koenvu** [kristijanhusak/laravel-form-builder#206]
I'd like to propose (and have a discussion about) functionality for allowing automatic translation of labels. Currently (by default) the label is determined by taking the name, converting underscores to spaces and transforming the first letter to uppercase.

## My proposal:

- add a new option to `Form`: (something similar to) `language_name`
- if this option is set change the `FormHelper::formatLabel` method to (something similar to) `trans(language_name . '.' . $name)`
  - if the option is not set, the current behavior will be used

## Example

Imagine a file `resources/lang/en/contact_form.php`:

```
<?php

return [
    'first_name' => 'Your first name'
];
```

A form:

```
$plain = FormBuilder::plain(['language_name' => 'contact_form']);
$plain->add('first_name', 'text');
```

The label of the field would then be **Your first name**.

## Questions

@kristijanhusak (and others) is this something you'd want? If so, any input on the names of the options? Let me know, I'd love to create a pull request for this feature!

**Comment by kristijanhusak** [comment]
@koenvu 
I think this is a useful feature, but i avoided it for only one reason - one more dependency to inject.

I'ts not really good to just hardcode laravel `trans()` function into the package. It needs to be injected.

I would suggest injecting it into FormHelper class, and then using it where needed.

Feel free to create PR, and we will discuss on it.

**Comment by koenvu** [comment]
I was planning on injecting indeed, the `trans` was just a (bad) example :+1:

**Comment by mohsensaeedi** [comment]
I used this way:
`
use Lang;
`

then use Lang::get as below
`
->add('username', 'text', [
                'label' => Lang::get('messages.username'),
                'rules' => 'required',
])
`
