### ISSUE TITLE
Adding required class to label based on rules

### ISSUE THREAD

**Issue by koenvu** [kristijanhusak/laravel-form-builder#207]
I'd like to propose (and have a discussion about) functionality for allowing automatic addition of class 'required' to labels, based on rules provided. Most of the functionality already exists, it should just be a matter of changing one or two methods.

## My proposal:

- change `FormField::prepareOptions` to use the `RulesParser` to automatically set the `required` option for the field.
- perhaps a global or form configuration that disables the functionality (not sure if this is really necessary)?

## Current situation

```
$plain = FormBuilder::plain();
$plain->add('first_name', 'text', ['rules' => 'required|max:255', 'required' => true]);
```

To me, it seems odd that we should specify `required` twice.

## Example

A form:

```
$plain = FormBuilder::plain();
$plain->add('first_name', 'text', ['rules' => 'required|max:255']);
```

The class for the label portion of the field would then include `required`.

## Questions

@kristijanhusak (and others) is this something you'd want? Let me know, I'd love to create a pull request for this change!

**Comment by kristijanhusak** [comment]
I guess that would be a good solution. I would still like to leave regular `'required' => true` just to avoid any BC. I'm open for PR.

**Comment by kristijanhusak** [comment]
This is added thanks to @koenvu!
