### ISSUE TITLE
ChoiceType can't be required, because it returns only its children's rules

### ISSUE THREAD

**Issue by rudiedirkx** [kristijanhusak/laravel-form-builder#212]
`ChoiceType` is a `ParentType`, and `ParentType` has a `getValidationRules()` that returns only its children's rules, not its own.

That means

        $fieldRules = $this->formHelper->mergeFieldsRules($this->fields);

in `Form::validate()` doesn't contain the `ChoiceType`'s rules (i.e. 'required'), which makes the entire thing unrulable.

That's a bug, no?

My use case: I have a radiobuttons status field, and I want the user to explicitly choose a value for new entities: required and no default value.

(Debugging the Validator is not cool.)

**Comment by kristijanhusak** [comment]
I guess it's bug. Will check it out, thanks.

**Comment by kristijanhusak** [comment]
@rudiedirkx  I fixed this on dev-master, but i didn't published stable version yet. Hope it will be in few days.

**Comment by rudiedirkx** [comment]
Looks good. Btw, if you add #212 in the commit message, it's linked here. Might be interesting. You're the boss.

**Comment by kristijanhusak** [comment]
Yeah i know, but most of the time i forget. Thanks for reminding :)

**Comment by kristijanhusak** [comment]
Fixed in latest version(1.6.50). Thanks for reporting.
