### ISSUE TITLE
Disable browser required validation via clientValidationEnabled

### ISSUE THREAD

**Issue by jvdlaar** [kristijanhusak/laravel-form-builder#213]
All rules validations in the browser are disabled when you set client_validation to false. The required attribute (which is added via the required option) is not disabled when you set client_validation to false. 

We only set client_validation to false on our development environment such that we can still validate the php validations. Is it possible to not add the required attribute when you have client_validation set to false?

**Comment by kristijanhusak** [comment]
I guess that makes sense. Will mark it as bug and fix it.
If you are using latest `dev-master`, you can just remove `'required' => true` and add `required` to rules for a field, it will be properly added only if client validation is true. https://github.com/kristijanhusak/laravel-form-builder/commit/d28f0b42fdadf0ea4d25850e4e042bcc9dbe339c?w=1#diff-07eeaacc8229862925ec9456b6a427faR232 . If you are waiting for stable version, it will be soon, just to merge one pull request that i'm waiting to be finished.

**Comment by jvdlaar** [comment]
Great thank you!

**Comment by kristijanhusak** [comment]
Fixed in latest version(1.6.50). Thanks for reporting.
