### ISSUE TITLE
Request when running behat

### ISSUE THREAD

**Issue by CaporalDead** [kristijanhusak/laravel-form-builder#214]
Hi,

I'm getting some trouble with your package when I try tu submit a form using behat and mink. It seems that the request that you get with the FormHelper does not contains any data but, if I try to get the data using the facade it works, also, if I manually bind the request with the setRequest method on the form it works.

I'm still trying to understand why the FormHelper could not get the data. If you have any idea about that let me know.

**Comment by CaporalDead** [comment]
It seems that when you register the form helper singleton, the request is empty and does not fill anymore.

**Comment by kristijanhusak** [comment]
@CaporalDead what version are u using?

**Comment by CaporalDead** [comment]
5.1 lts, behat, mink and mink extension @ dev-master, laravel behat 1.0

**Comment by kristijanhusak** [comment]
What version of laravel form builder are you using? In latest version request is not pulled from form helper, it is added to form class when creating a form with FormBuilder.

**Comment by CaporalDead** [comment]
I'll try, but recently when updating from 1.6.31 to 1.6.42 was causing a lot of problems with custom elements, so version is fixed with 1.6.31.

**Comment by CaporalDead** [comment]
oOkay my bad, it works with the lastest version. I'll try to update my dependecy on my other projects and let you know if there's still bugs. I can go back on my PR about filters.
