### ISSUE TITLE
Selecting a related model

### ISSUE THREAD

**Issue by LourensThalen** [kristijanhusak/laravel-form-builder#218]
Hi, 

I just do not understand how to choose a related model (venues) in my eventForm:
```
$this->add('venues', 'select', [
    'choices' => $venues,
    'selected' => function ($data) {
        // Returns the array of short names from model relationship data
        return array_pluck($data, 'short_lang_name');
    }
    'empty_value' => '=== Select venue ==='
])
```
I can't figure out how to pass on a $venues variable from my eventController to the eventForm. The documentation is not clear enough for me to figure this out. The getData method is removed from the documentation.

I would love to pass through all the venues into the eventForm and create a dropdown from with a user can select the venue belonging to that event. 

Thank you,
Lourens

**Comment by LourensThalen** [comment]
Never mind - I found it. 
I can just use the model in the form, and use this:
`->add('location_id', 'choice', [
                'label' => 'Venue',
                'choices' => Location::all()->pluck('name', 'id')->toArray(),
            ])`

**Comment by kristijanhusak** [comment]
@LourensThalen 
You can also try Entity type http://kristijanhusak.github.io/laravel-form-builder/field/entity.html , it is mostlly used for these types of stuff.

Is this resolved? Can it be closed?
