### ISSUE TITLE
Expanded choice field with not working with laravel v5.2

### ISSUE THREAD

**Issue by chrishodgson** [kristijanhusak/laravel-form-builder#219]
Laravel 5.2
Example taken from help page: http://kristijanhusak.github.io/laravel-form-builder/field/choice.html 

Hi, 
The choice field when expanded like in the example above does not work with laravel 5.2
Works fine in v5.1

cheers
Chris

**Comment by kristijanhusak** [comment]
What exactly do not work?

If you are using `lists()` method, or as upgrade guide says `pluck`, make sure you are setting the right order of the arguments for the method call. Can you give me your part of the code that is not working, together with part where you pull the choices?

**Comment by chrishodgson** [comment]
When I display the form via the routes file (survey2) it works, whereaswhen I display it via a controller (survey1), I get error...

_FatalErrorException in Arr.php line 255:
Maximum function nesting level of '100' reached, aborting!_


```
/* routes.php 
*/
Route::group(['middleware' => ['web']], function () {

    Route::any('survey1', ['uses' => 'SurveyController@page1']);

    Route::any('survey2', function () {
        $form = FormBuilder::create('App\Forms\SurveyForm', ['method' => 'POST']);
        return view('survey', compact('form'));
    });
});

/* SurveyController.php 
*/
namespace App\Http\Controllers;
use Kris\LaravelFormBuilder\FormBuilder;

class SurveyController extends Controller
{
    public function page1(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create('App\Forms\SurveyForm', ['method' => 'POST']);
        return view('survey', compact('form'));
    }
}

/* SurveyForm.php
*/
namespace App\Forms;
use Kris\LaravelFormBuilder\Form;

class SurveyForm extends Form
{
    public function buildForm()
    {
        $this->add('languages', 'choice', [
            'choices' => ['en' => 'English', 'fr' => 'French'],
            'selected' => ['en', 'fr'],
            'expanded' => true,
            'multiple' => true
        ]);
    }
}

/* survey.blade.php
*/
@extends('app')
@section('content')
    {!! form($form) !!}
@endsection
```

**Comment by kristijanhusak** [comment]
@chrishodgson sorry for late response. Did you manage to fix it?

That error is because of the xdebug, and you will have to set it up to allow deeper nesting, especially if you are using lots of collections. 
You have explanation how to increase nesting level here https://laracasts.com/discuss/channels/general-discussion/l5-maximum-function-nesting-level-of-100-reached-aborting
