### ISSUE TITLE
Can't set "for" for label attribute

### ISSUE THREAD

**Issue by ahmadazimi** [kristijanhusak/laravel-form-builder#223]
Hi there,

I need to set a complex id to my form fields, and so I also need to override ```for``` attribute for labels. Default you use ```field name``` as ```for```:

```php
return $this->toHtmlString('<label for="' . $name . '"' . $options . '>' . $value . '</label>');
```

**BTW** 
I'm using **materializecss** framework, so I have to replace ```for``` attribute to my form field id.

Is there any chance to fix this?

**Comment by kristijanhusak** [comment]
Did you try setting the `for` attribute in `label_attr` option property? http://kristijanhusak.github.io/laravel-form-builder/field/fieldbasics.html

**Comment by ahmadazimi** [comment]
Yes, I've tested it and not working for me.
I've wondered how should it work because the code that generates label markup always use ```$name``` for ```for``` attribute in a hardcoded style:

```php
return $this->toHtmlString('<label for="' . $name . '"' . $options . '>' . $value . '</label>');
```

**Comment by kristijanhusak** [comment]
I'll check it out, thanks.

**Comment by kristijanhusak** [comment]
@ahmadazimi I checked it out, it basically set's it, but 2 times, first is from Laravel's form, and second one from the options. Later on it get's merged into one by browser (automatic fix). Why you need custom `for` attribute? In what way materializecss requires it?

**Comment by ahmadazimi** [comment]
This is the my way to use ```for```:
```php
$this->builder   = $this->plain($this->builder_options);
$label_attr['for']   = 'MY FOR ATTR';
$label_attr['class'] = 'MY FOR CLASS';
array_set($params, 'options.label_attr', $label_attr);
$this->builder->add('name', 'text', $params['options']);
```

It's interesting that the ```class``` parameter  works but ```for``` not!

**Comment by kristijanhusak** [comment]
@ahmadazimi it's set automatically by Laravel Form Class. Why you need a custom `for` attribute?

**Comment by ahmadazimi** [comment]
I'm using your form builder in a bigger form generator application. In some situation I need override ```for``` attribute.

I think the best way for me is to use javascript to change label's ```for``` attribute.

**Comment by kristijanhusak** [comment]
Yeah i guess that's the only solution, since that is not really the desired behavior. Closing.

**Comment by kristijanhusak** [comment]
@ahmadazimi 
I pushed a solution for this to `dev-master` now. You can now change `for` attribute of a label, and also an `id` of the field. Will publish a stable version when it is tested a bit more.
