### ISSUE TITLE
Can't set key to use for label name in collections

### ISSUE THREAD

**Issue by dirkpostma** [kristijanhusak/laravel-form-builder#224]
In the first example of collections, http://kristijanhusak.github.io/laravel-form-builder/field/collection.html, labels are disabled in the options. I would like to use a value of the model as label, but I can't set the key that should be used as label name. Similar to 'property'

**Comment by kristijanhusak** [comment]
That's really specific situation. I would suggest you to create a custom template and just pass it to options:

```
<?php
use Kris\LaravelFormBuilder\Form;

class PostForm extends Form
{
    public function buildForm()
    {
        $this
            ->add('title', 'text')
            ->add('body', 'textarea')
            ->add('tags', 'collection', [
                'type' => 'text',
                'property' => 'name',    // Which property to use on the tags model for value, defualts to id
                'data' => [],            // Data is automatically bound from model, here we can override it
                'options' => [    // these are options for a single 
                    'attr' => ['class' => 'tag'],
                    'template' => 'my_fields/text' // views/my_fields/text.php
                ]
            ]);
    }
}
```

Just make sure template has the same structure as the default one, and you can change the variables how you like. Hope this helps.

**Comment by kristijanhusak** [comment]
@dirkpostma did you manage to set it up ?
