### ISSUE TITLE
Hide label option for form fields

### ISSUE THREAD

**Issue by StefanPrintezis** [kristijanhusak/laravel-form-builder#226]
I'm trying to hide the label of this field. I cannot make it an empty string because the errors use the label.
I could hide it with css, but I'd rather no show it at all. I've seen the Fields/FormField render function that contains the showLabel argument. Could you make it possible to overwrite the showLabel argument by setting the value in the options? Or make the showLabel argument accessible?

```
$this->add('tests', 'choice', [
      'label' => 'foo',
      'label_show' => FALSE, <-- like this?
      'choices' => $options,
      'expanded' => TRUE,
      'multiple' => TRUE,
      'rules' => ['required', 'allowedOption'],
]);

```

**Comment by kristijanhusak** [comment]
There is several way you can tackle this issue:

* by creating a custom template
* hiding it with css (like you mentioned), which is also perfectly fine (and simpler) solution

If you really want to skip showing it at all, than just create a custom template, for example, create file in `resources/views/fields/custom_choice.php`, add content [from here](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/views/choice.php) and just delete
the label part (lines 7-9).
Then just use that custom template when rendering a choice field:
```php
$this->add('tests', 'choice', [
      'label' => 'foo',
      'choices' => $options,
      'expanded' => TRUE,
      'multiple' => TRUE,
      'rules' => ['required', 'allowedOption'],
      'template' => 'fields.custom_choice'
]);
``` 
And that should do it. Let me know if you need any more help.

**Comment by StefanPrintezis** [comment]
Why create a custom template file when all you're doing is setting the showLabel variable to false? I've currently done it with custom code by rendering the field manually and sending in the correct variables, but i'd rather set it during field definition in the options. I find creating a custom template file for just not showing the label a bit of an overkill and using css to hide it would be unprofessional in my working environment.

**Comment by kristijanhusak** [comment]
I just wrote the possible solutions at this moment. I'm open for PRs, so feel free to add that feature, and i'll gladly review it. I'm a little bit short on time.

**Comment by StefanPrintezis** [comment]
Okey, i'll give it a shot. Probably next week.

**Comment by joshhornby** [comment]
Unless I am missing something here you can just pass `'label' => false`. 

```
$this->add('tests', 'choice', [
      'label' => 'foo',
      'choices' => $options,
      'expanded' => TRUE,
      'multiple' => TRUE,
      'rules' => ['required', 'allowedOption'],
     'label' => false
]);
```

**Comment by kristijanhusak** [comment]
I'll add a `label_show` property which will fix this issue. Will let you know when it's merged in.

**Comment by StefanPrintezis** [comment]
Sounds great

**Comment by kristijanhusak** [comment]
@StefanPrintezis I added the property in the latest version (1.7.0). You can update and start using it. If it works ok, please close the issue.

**Comment by markuskoehler** [comment]
yes, works in 1.7.10
