### ISSUE TITLE
Dynamically adding forms

### ISSUE THREAD

**Issue by ZAZmaster** [kristijanhusak/laravel-form-builder#228]
Is it possible to make dynamically add form fields or the whole shape? For example there is a form of information about the organization and form of the employee, but sometimes you need to add information on the two or three employees.

```
class OrganizationForm extends Form
{
    public function buildForm()
    {
        $this
            ->add('name', 'text')
            ->add('phone', 'text')
            ->add('fax', 'text')
            ->add('legal_address', 'textarea')
            ->add('post_address', 'textarea')
            ->add('people', 'form', [
                'class' => $this->formBuilder->create('App\Forms\PeopleForm')
                'label' => false
            ]);
    }
}

class PeopleForm extends Form
{
    public function buildForm()
    {
        $this
            ->add('surname', 'text')
            ->add('firstname', 'text')
            ->add('patronymic', 'text')
            ->add('position', 'text')
            ->add('phone', 'text')
            ->add('fax', 'text')
            ->add('email', 'text');
    }
}
```

**Comment by kristijanhusak** [comment]
I'm not sure i fully understand, but this should maybe work out for you
http://kristijanhusak.github.io/laravel-form-builder/field/collection.html

**Comment by ZAZmaster** [comment]
@kristijanhusak I need to on this form the user can add more than one person in the form of organizations

**Comment by kristijanhusak** [comment]
@ZAZmaster 
Yes, Collection should work for you. It has a prototype which can allow you to dynamically add forms to the page and save it. You have example in the docs link i sent you above.

**Comment by rjosecruz** [comment]
Hi, I'm starting to use your form builder, how can I do to render the collection in line?

**Comment by kristijanhusak** [comment]
@rjosecruz just use css to style them inline.
