### ISSUE TITLE
how to style the multiple+expanded choice field

### ISSUE THREAD

**Issue by vesper8** [kristijanhusak/laravel-form-builder#230]
I'm new at using your builder and am really loving it so far.

A lot of my form fields are multiple-checkbox so I am using the choice field with expanded and multiple set to true.

Here's how I'm creating my fields

```
        foreach ($questions as $question) {

            $options = [
                'wrapper' => ['class' => 'form-group'],
                'attr' => ['class' => 'form-control'],
                'help_block' => [
                    'text' => null,
                    'tag' => 'p',
                    'attr' => ['class' => 'help-block']
                ],
                'default_value' => null,
                'label' => $question["label"],
                'label_attr' => ['class' => 'control-label', 'for' => $question["name"]],
                'errors' => ['class' => 'text-danger']
            ];

            if ($question["type"] == "choice") {
                $options['choices'] = json_decode($question["choices"], true);
                $options['multiple'] = $question["multiple"];
                $options['expanded'] = $question["expanded"];
            }
            
            $this->add(
                $question["name"],
                $question["type"],
                $options
            );
        }
```

This is creating a form-group row followed by the initial label, followed by a bunch of <label><input>. The problem is everything ends up inline. I would like to have the label on the left, followed by the checkboxes and their labels one per line aligned on the right of the "question" label.

I want to know if it's possible to do this without creating a new template that uses some kind of table for alignment.

Is it possible using just form-builder to specify that all label/rows should be contained within their own wrapper? including one big wrapper around all of them as well?

I was also wondering if there's any existing stylesheets around I can use that would save me some time for making the forms prettier and more structured.

Thanks!

**Comment by kristijanhusak** [comment]
By default, it's renders something like this

```html
<div class="form-group">
  <label for="myfield[]" class="control-label">My field</label>
  <input id="myfield_a" name="myfield[]" type="checkbox" value="a">
  <label class="control-label" for="myfield_a">Value A</label>
  <input id="myfield_b" name="myfield[]" type="checkbox" value="b">
  <label class="control-label" for="myfield_b">Value B</label>
</div>
```

You can add options for each checkbox with `choice_options` property like this:

```php
$this->add('myfield', 'choice', [
    'choices' => ['a' => 'Value A', 'b' => 'Value B'],
    'label' => 'My field',
    'choice_options' => [
        'wrapper' => ['class' => 'choice-wrapper'],
        'label_attr' => ['class' => 'label-class'],
    ],
    'expanded' => true,
    'multiple' => true,
]);
```

And it will generate this:

```html
<div class="form-group">
  <label for="myfield[]" class="control-label">My field</label>

  <div class="choice-wrapper">
    <input id="myfield_a" name="myfield[]" type="checkbox" value="a">
    <label class="label-class" for="myfield_a">Value A</label>
  </div>

  <div class="choice-wrapper">
    <input id="myfield_b" name="myfield[]" type="checkbox" value="b">
    <label class="label-class" for="myfield_b">Value B</label>
  </div>
</div>

```

By default, `wrapper` option on `choice_options` is false, so that's why there is no any wrapper in the default case.

With these options and maybe with some css tweaks you can achieve what you want without changing a template. If not, just create custom template, it's not big of a deal.

About styling, package by default uses bootstrap 3, so importing that should make many things much prettier.

**Comment by fosron** [comment]
@kristijanhusak Cool, maybe you can add this to documentation? As i did not find this there.

**Comment by kristijanhusak** [comment]
Sure, i will add it. Thanks.

**Comment by njbarrett** [comment]
@kristijanhusak thanks, I needed this also, would be great in the docs

**Comment by kristijanhusak** [comment]
It's added here http://kristijanhusak.github.io/laravel-form-builder/field/choice.html.
