### ISSUE TITLE
Use TranslatorInterface instead of Translator class

### ISSUE THREAD

**Issue by jvdlaar** [kristijanhusak/laravel-form-builder#231]
In the FormHelper class the $translator var is typehinted by the laravel Translator class. But I think it's cleaner to typehint with the interface that theTranslator is implementing, the TranslatorInterface. Then someone is able to implement their own Translator.

**Comment by kristijanhusak** [comment]
Yeah i guess that can be done. You can send a PR, or i'll change it when i catch some time.

**Comment by kristijanhusak** [comment]
I fixed it in the latest version (1.7.10). Thanks for reporting.

**Comment by jvdlaar** [comment]
Oh thanks a lot!
