### ISSUE TITLE
Laravel 5.2.32 or greater breaks form

### ISSUE THREAD

**Issue by vincehollywood** [kristijanhusak/laravel-form-builder#232]
When updating to Laravel 5.2.32 or greater, I get the following error when trying to display a form with a button. Removing the button works.

> Relationship method must return an object of type lluminate\Database\Eloquent\Relations\Relation

```
/* EditMediaForm.php */

public function buildForm()
{
     $this->add('filename', 'text')
         ->add('alt_attribute', 'text')
         ->add('save', 'submit', ['attr' => ['class' => 'btn btn-primary']]);
}
```

**Comment by kristijanhusak** [comment]
Hm, that error is really strange for something related to button. Are you attaching some model to the form?

**Comment by vincehollywood** [comment]
Yeah. It's just a standard eloquent model. If I lower the Laravel framework to 5.2.31 it works fine.

**Comment by kristijanhusak** [comment]
That's really strange. Can you provide me the model content from `$model->toArray()` ?

**Comment by vincehollywood** [comment]
```
$form = $formBuilder->create('App\Http\Forms\Backend\EditMedia',[
    'method' => 'PUT',
    'model' => $media->toArray(),
    'url' => route('admin.media.update', $media->id)
]);
```

Silly me. I didn't do the toArray(). However it's always worked just passing an object before 5.2.32.

**Comment by kristijanhusak** [comment]
It should work with object. I just need to see what your media model contains, it will help me debug the issue. Give me var_dump:

```php
var_dump($media->toArray());
```

**Comment by vincehollywood** [comment]
```
array(14) {
    ["id"] => int(2)
    ["filename"] => string(50) "13178822_10209364664818664_35521213679345507_n.jpg" 
    ["extension"] => string(3) "jpg" 
    ["mime_type"] => string(10) "image/jpeg"
    ["width"] => int(960)
    ["height"] => int(960)
    ["size"] => int(92926)
    ["source"] => string(23) "QcmV7uZD_2_Gw8NLKLm.jpg"
    ["alt_attribute"] => string(50) "13178822_10209364664818664_35521213679345507_n.jpg"
    ["album_id"] => int(2)
    ["cloned_id"] => NULL
    ["crop_data"] => NULL
    ["created_at"] => string(19) "2016-05-24 10:44:36"
    ["updated_at"] => string(19) "2016-05-24 10:44:36"
}
```

**Comment by vincehollywood** [comment]
Works:
```
$form = $formBuilder->create('App\Http\Forms\Backend\EditMedia',[
    'method' => 'PUT',
    'model' => $media->toArray(),
    'url' => route('admin.media.update', $media->id)
]);
```

Fails:
```
$form = $formBuilder->create('App\Http\Forms\Backend\EditMedia',[
    'method' => 'PUT',
    'model' => $media,
    'url' => route('admin.media.update', $media->id)
]);
```

**Comment by kristijanhusak** [comment]
Are you using any child forms, or collections inside the form? EditMedia form content would be also great to see.
Also, did you try googling the issue, maybe it's something like this:

* http://stackoverflow.com/questions/23773467/laravel-relationship-method-must-return-an-object-of-type-illuminate-database-e
* http://stackoverflow.com/questions/23546110/relationship-method-must-return-an-object-of-type-illuminate-database-eloquent-r
* https://laracasts.com/discuss/channels/eloquent/relationship-method-must-return-an-object-of-type

**Comment by vincehollywood** [comment]
```
<?php

namespace App\Http\Forms\Backend;

use Kris\LaravelFormBuilder\Form;
use App\Models\Album;

class EditMedia extends Form
{   
    protected $album;
    
    public function __construct(Album $album)
    {
        $this->album = $album;
    }
    
    public function buildForm()
    {
        $albums = $this->album->get()->lists('title', 'id')->toArray();
        
        $this->add('filename', 'text')
            ->add('alt_attribute', 'text')
            ->add('album_id', 'select', [
                'choices' => $albums,
                'empty_value' => '-- Please choose --',
                'label' => 'Album'
            ])
            ->add('save', 'submit', ['attr' => ['class' => 'btn btn-primary']]);
    }
    
}
````

If I remove the $this->add('save', 'submit'), the form works perfectly fine. Albeit I can't submit the form.

**Comment by kristijanhusak** [comment]
I'll check it out. In the meantime, can you try removing `album_id` instead of `save`, and see if it works?

**Comment by vincehollywood** [comment]
I've removed the `album_id` and I still get the error.

**Comment by kristijanhusak** [comment]
Ok thanks for your help. I'll check it out and let you know when i fix it. Until then, please use `toArray()`.

**Comment by vincehollywood** [comment]
No worries. One of my go to packages for any project. Keep up the good work!

**Comment by rikless** [comment]
May be related to https://github.com/illuminate/database/commit/2d00f24921de3efdb3d9c6f9bddea267bf2f5e35 ?

**Comment by kristijanhusak** [comment]
@rikless how that could affect anything here?

**Comment by kristijanhusak** [comment]
@vincehollywood I found the issue. It's problem with the `save` field name. 
It cannot be `save`, because i use field name to bind values to form from model, so when you pass eloquent model, and when form builder comes to `save` field, it tries to call `$model->save`, which throws error here https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L2665 .
I believe you can just use something else (for example `submit`), and set label to `Save`. I'll add a check when fields are added, and to throw exception that is much more understandable. Closing this, since it not really a bug, just usage of reserved name.
Thanks for reporting.

**Comment by kristijanhusak** [comment]
I added a check in latest version (1.7.10), so other users get informed properly.

**Comment by JamesGuthrie** [comment]
The broken behaviour with 5.2.32 is/was a bug in the framework, which I reported here: https://github.com/laravel/framework/issues/13632. It should be fixed in this commit which is in 5.2.36: https://github.com/laravel/framework/commit/8fb89c61c24af905b0b9db4d645d68a2c4a133b9. Can you revert the reserved field name check, as from 5.2.36 onwards the name is not 'reserved'.

**Comment by JamesGuthrie** [comment]
Actually it looks like I spoke too soon. Sorry. This issue https://github.com/laravel/framework/issues/13632 hasn't been fixed in 5.2.36.

**Comment by kristijanhusak** [comment]
I'll leave it until we make sure it's fixed in the latest release.

**Comment by JamesGuthrie** [comment]
The underlying issue has not and most likely will not be fixed, so I guess you can close this issue (the closed pull request for reference: https://github.com/laravel/framework/pull/13750)

**Comment by csogilvie** [comment]
Hi, @kristijanhusak - if this change is contined to be supported, can the documentation at http://kristijanhusak.github.io/laravel-form-builder/field/buttons.html please be updated as it shows a save button by default... and has caused me at least 15 minutes of frustration so far trying to work out why I was getting an error when following the documentation :)

**Comment by kristijanhusak** [comment]
@csogilvie i fixed it, thanks.
