### ISSUE TITLE
Child form field naming

### ISSUE THREAD

**Issue by sepehr** [kristijanhusak/laravel-form-builder#233]
Is there anyway to force a child form field name? By default child form field names has this format: `child_form_name[field_name]`. I need them to be simply `field_name` without the form name.

**Comment by kristijanhusak** [comment]
You can use the [Compose](http://kristijanhusak.github.io/laravel-form-builder/form/methods-and-properties.html#compose) Method on form , that will take child forms and add them to the main form, without any naming.

**Comment by sepehr** [comment]
Great! Thank you Kris.
