### ISSUE TITLE
LogicException in Model.php line 2702: Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation

### ISSUE THREAD

**Issue by msonowal** [kristijanhusak/laravel-form-builder#239]
LogicException in Model.php line 2702:
Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation

``` php
$model = Menu::findOrFail($id);
        $form = $formBuilder->create('App\Forms\MenuForm', [
            'method' => 'PUT',
            'model' => $model,
            'url' => route('admin.menus.update', $id)
        ])->add('Update', 'submit', [
                'attr' => ['class' => 'btn btn-lg btn-success col-xs-12']
        ]);
```

but If I remove the last line it works fine i.e.

```
$model = Menu::findOrFail($id);
        $form = $formBuilder->create('App\Forms\MenuForm', [
            'method' => 'PUT',
            'model' => $model,
            'url' => route('admin.menus.update', $id)
        ])
```

It is happening with latest updated version, previosuly it was working fine with my same project running version 1.6 but current version is 1.7

**Comment by kristijanhusak** [comment]
Can you just try using different name for submit btn, something like this:

```php
$model = Menu::findOrFail($id);
        $form = $formBuilder->create('App\Forms\MenuForm', [
            'method' => 'PUT',
            'model' => $model,
            'url' => route('admin.menus.update', $id)
        ])->add('Submit', 'submit', [
                'attr' => ['class' => 'btn btn-lg btn-success col-xs-12'],
                'label' => 'Update'
        ]);
```

**Comment by kristijanhusak** [comment]
@msonowal please let me know if that worked out for you.

**Comment by msonowal** [comment]
first of all thanks. It's working. but I really want to know why it was workin before and now not working I use to add buttons like that, but from now I have to use only Submit  if I want to add button right?

**Comment by kristijanhusak** [comment]
@msonowal it is related to this issue https://github.com/kristijanhusak/laravel-form-builder/issues/232

Basically none of the eloquent method names are allowed. since Eloquent class has `update()` method, it crashes with this error. Like it is mentioned in the issue #232, i added the `save` to reserved words, but i'll  do it a bit more dynamic.

**Comment by msonowal** [comment]
thank you for your reply
And one more question is there form helper for generating horizontal forms I am unable to find in the docs like below example
  ```
 <form class="form-horizontal">
<div class="form-group">
 <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
 <div class="col-sm-10">
   <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
 </div>
</div>
 <div class="form-group">
<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
<div class="col-sm-10">
<input type="password" class="form-control" id="inputPassword3" placeholder="Password">
</div>
 </div>
```

**Comment by kristijanhusak** [comment]
@msonowal there is no templates for that, there's an open issue https://github.com/kristijanhusak/laravel-form-builder/issues/175 , but i didn't have time to add that to the package. If you want create it and make a PR.
