### ISSUE TITLE
Other path for config.php

### ISSUE THREAD

**Issue by PascalKleefeld** [kristijanhusak/laravel-form-builder#240]
Hey. Is there a way to overwrite the config.php file inside the vendor/kris folder from the outside? Like e.g. in a <root>/config/form-builder folder/config.php?
Because every time i update composer the config.php will be overwritten and so it's not an update save solution i think.

**Comment by kristijanhusak** [comment]
Just publish package configuration files. You have explanation in docs here
http://kristijanhusak.github.io/laravel-form-builder/custom/configuration-basics.html
