### ISSUE TITLE
Why I need to pass array in 'model' option when creating the form

### ISSUE THREAD

**Issue by mmahrous** [kristijanhusak/laravel-form-builder#241]
I was using the package it's a good one, but after I run a composer update for some reason everything is not working after a search I figure out a solution that will make the form work but not show the data
Before
`FormBuilder::create($this->formPath, [
                'method' => $method,
                'url' => $url,
                'model' => $model,
            ], [
                $extra,
            ]);`
Now I have to add toArray() and that made a 4 month worth of work not working

**Comment by kristijanhusak** [comment]
Whats an error?

**Comment by mmahrous** [comment]
LogicException in Model.php line 2702:
Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation

**Comment by kristijanhusak** [comment]
There's already an open issue for that. https://github.com/kristijanhusak/laravel-form-builder/issues/239 closing this since it's a duplicate.

**Comment by mmahrous** [comment]
Thank you 👍
