### ISSUE TITLE
Collection, using dynamic data within attributes

### ISSUE THREAD

**Issue by paparabbit** [kristijanhusak/laravel-form-builder#242]
I have a collection field which is showing hasMany data that is passed in from the Controller.

However I need the dynamic data in the src attribute, is there a way to do this?

```
->add('images', 'collection',[
    'type' => 'static',
    'data' => $this->getData('imagenames'),
    'options' => [
        'tag' => 'img',
        'attr' => [
            'src' => '????????'
        ]
    ]
])
```

**Comment by kristijanhusak** [comment]
You cannot add an image like that, and you cannot change 'tag', only for help_block. You need custom field for this.

**Comment by kristijanhusak** [comment]
You could collection of [static type](http://kristijanhusak.github.io/laravel-form-builder/field/static.html) for this.
