### ISSUE TITLE
Pipe some form methods from ChildFormType to its Form

### ISSUE THREAD

**Issue by rudiedirkx** [kristijanhusak/laravel-form-builder#245]
Useful:

* getField()
* isValid()
* getValues(), see #246 

and maybe more. I'm having the problem where there are many 'kinds' of forms floating around: `Form`, `ChildFormType`, array of child `FormField`s. It'd be nice if they all had the same interface.

**Comment by kristijanhusak** [comment]
You can call any Form class method from child form, because of the magic method here 
https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/ChildFormType.php#L150

**Comment by rudiedirkx** [comment]
Ah, that's exactly what I wanted. I didn't search for magic call. Thanks.
