### ISSUE TITLE
Add automatic scalar/non-scalar validation

### ISSUE THREAD

**Issue by rudiedirkx** [kristijanhusak/laravel-form-builder#252]
If a field has only 1 validation rule `max:40`, the Validator will interpret that depending on the format of the user input:

* scalar means max 40 characters
* non-scalar means max 40 elements

The specific form field knows which kind it is: scalar or non-scalar. The field could tell the validator what to accept. If you have a textarea `description` without any validation, you don't want to blindly accept a multi level assoc array etc. That'll break your app somewhere. Never trust user input, right?

* `FormField::isScalar()`, returns true by default
* Override for multiple choices, child forms etc
* Every `FormField` automatically adds a 'scalar' or 'nonscalar' rule
* Extend validator with those 2 rules

It should be checked immediately after 'required', or first if optional.

Maybe it should be a config, because it might break bc for forms that (ab)use the current user input freedom.

**Comment by rudiedirkx** [comment]
ffr:

```
function boot() {
    $this->app['validator']->extend('scalar', 'Class@validateScalar');
```

**Comment by rudiedirkx** [comment]
It might be cleaner for another service/package to do this, but I wouldn't know how another service could add an extra rule for every field... It would need access to the field's type and settings.

**Comment by rudiedirkx** [comment]
How about events?

In `FormBuilder::create()`:

    \Event::fire(new FormWasCreated($form));

In `Form::makeField()`:

    \Event::fire(new FieldWasCreated($field));

Anybody could alter the form and field options then... Depending on Laravel's event speed that might be very inefficient though...

**Comment by kristijanhusak** [comment]
Validating user input is up to developer. I don't want to "hardcode" some validations in the background, that may be unwanted. Config file switch would help, but i don't think this feature is really needed.
If properly used, Laravel will never enter bad input into the database (validation + db escaping).

For events, we will continue discussion on the PR.

**Comment by rudiedirkx** [comment]
I like my user input very very strict. Like XML validation strict. No arrays where I expect strings, and vice versa. Laravel doesn't have checks for that (or anything). The form builder could have.

Bad user input won't destroy your queries, but with PHP's messed up loosely typed comparisons, who knows what `array('x') == 14` might be? All app logic before saving depends on a certain input data format too. I personally want that to be un'hackable'.

> ... Laravel will never enter bad input into the database (validation ...

Where is this validation? Do you mean form validation or model save validation?

Thanks for quick replies!

**Comment by kristijanhusak** [comment]
You can add that additional validation layer before or after the form, it does not have to be part of it.

> Where is this validation? Do you mean form validation or model save validation?

i'm saying when you try to enter for example multi level assoc field (name[test][test2]), it will properly escape it on model save level. Also, if properly used, laravel validation is pretty secure.
