### ISSUE TITLE
FatalThrowableError in UserInfoController.php line 17: Call to undefined method Kris\LaravelFormBuilder\Facades\FormBuilder::create()

### ISSUE THREAD

**Issue by msonowal** [kristijanhusak/laravel-form-builder#259]
public function create(FormBuilder $formBuilder)
      {

          $form = $formBuilder->create(convertifier\Forms\UserInfoForm::class, [
              'method' => 'POST',
              'url' => route('userinfo.store')
          ]);

          return view($this->$view_path.'create', compact('form'));
      }

It's throwing error I am using latest laravel "version": "v5.2.42",

**Comment by koenvu** [comment]
You should `use Kris\LaravelFormBuilder\FormBuilder;` instead of `use Kris\LaravelFormBuilder\Facades\FormBuilder;` from the looks of it.

**Comment by kristijanhusak** [comment]
Exactly what @koenvu said. If you want to use facade, remove the `use` part and do \FormBuilder::create().
