### ISSUE TITLE
Collection of child forms

### ISSUE THREAD

**Issue by OvalMedia** [kristijanhusak/laravel-form-builder#267]
Hi,

I have a weird issue with a collection of child forms. 

I have invoices and invoice items (1:n). Both tables have 'id' as primary key.

Invoice form:

``` php
$this
   ->add('client_id', 'hidden')
   ->add('items', 'collection', array(
                'type' => 'form',
                'label' => false,
                'options' => array(
                    'class' => \InvoiceItem::class,
                    'label' => false
                )
            ));
```

Invoice item form:

``` php
$this
            ->add('id', 'hidden')
            ->add('description', 'textarea', array(
                'label' => 'Beschreibung',
                'wrapper' => array('class' => 'form-group col-xs-12 col-md-10'),
                'attr' => array(
                    'placeholder' => 'Beschreibung',
                    'rows' => 3
                    //'class' => 'description col-xs-12 col-md-6'
                )
            ))
            ->add('price', 'text', array(
                'label' => 'Preis',
                'wrapper' => array('class' => 'form-group col-xs-6 col-md-1'),
                'attr' => array(
                    'placeholder' => 'Preis',
                    //'class' => 'description col-xs-12 col-md-6'
                )
            ))
            ->add('qty', 'text', array(
                'label' => 'Anzahl',
                'wrapper' => array('class' => 'form-group col-xs-6 col-md-1'),
                'attr' => array(
                    'placeholder' => 'Anzahl',
                    //'class' => 'description col-xs-12 col-md-6'
                )
            ))
        ;
```

I create invoices in two steps. First the basic data for an invoice will be entered and the invoice will be written to the database. In the second step I am able to enter corresponding invoice items.

Now when I open a newly created invoice the child form is being rendered with one empty invoice item already present. For each entry in the child form a hidden id field is rendered. This should not have a value when there are no invoice items yet. But instead that hidden id field has the id of the parent, which is the invoice.

When I manually enter invoice items to the database and open that invoice for editing all invoice items are rendered properly with correct ids.

Is this a bug or am I missing something here?

**Comment by kristijanhusak** [comment]
Thanks for reporting, it's a bug, id is pulled from the parent value if not provided. I'll look into it.

**Comment by SeregaSE** [comment]
I faced this problem to, Is there a solution?

**Comment by kristijanhusak** [comment]
@SeregaSE not at this moment, i didn't had time to look into this. I'll try to fix it until the end of the week.

**Comment by SeregaSE** [comment]
I got a little  fix for it. I added `'empty_row' => false` and the result is:
if a got some data, all is okey, http://skrinshoter.ru/s/110117/ARuL9kSY
if no data, just no field. http://skrinshoter.ru/s/110117/xJyQSORO

```php
->add('tags', 'collection', [
                'type' => 'form',
                'empty_row' => false,
                'options' => [   
                    'class' => 'TagForm',
                ]
            ])
```

**Comment by rudiedirkx** [comment]
I can't reproduce this anymore. It has been 2.5 years, so it might have been fixed somewhere along many commits.

The parent model is still injected in the child form for the `empty_row` item though. #520 can fix that, optionally.

I think this issue isn't an issue anymore.
