### ISSUE TITLE
No model binding for fieldtype file

### ISSUE THREAD

**Issue by lbm-services** [kristijanhusak/laravel-form-builder#269]
I have a field type 'file' and a corresponding database column with the same name.
Nothing is shown for this field if a model is assigned.
Model binding works with all other field types though.
Preview of the image would be nice as well.

**Comment by kristijanhusak** [comment]
You can split form in a view, and show image there:

```blade
{!! form_start($form) !!}
<img src="{!! $form->getModel()->photo !!}" />
{!! form_end($form) !!}
```

Or you can use Static type http://kristijanhusak.github.io/laravel-form-builder/field/static.html , but for this you will need to use custom template, so i think solution above is simpler.

**Comment by lbm-services** [comment]
Thank you for your suggestion. But it is not convenient if I want to show the preview exactly above the input file field. I tried the static field type but could not get the src attribute to be filled.
Why is there no view template for field type file btw?

My template has this:
`    ->add('preview', 'static', [
                    'tag' => 'img', // Tag to be used for holding static data,
                    'attr' => ['src' => ''], // This is the default
                ])`
And tried to set the src like this:

{!! form_row($form->preview, $options = [ 'elemAttrs' => url('images/upload' . $form->getModel()->picture1)  ]) !!}

The img tag is displayed but without src value.

**Comment by kristijanhusak** [comment]
You can use custom template for type file:

```php
->add('image', 'file', [
    'template' => 'fields.image_type' // resources/views/fields/image_type.php
]);
```

And use this template:

```php
<?php if ($showLabel && $showField): ?>
    <?php if ($options['wrapper'] !== false): ?>
    <div <?= $options['wrapperAttrs'] ?> >
    <?php endif; ?>
<?php endif; ?>

<?php if ($options['value']): ?>
<img src="{!! $options['value'] !!}" />
<?php endif; ?>

<?php if ($showLabel && $options['label'] !== false && $options['label_show']): ?>
    <?= Form::label($name, $options['label'], $options['label_attr']) ?>
<?php endif; ?>

<?php if ($showField): ?>
    <?= Form::input($type, $name, $options['value'], $options['attr']) ?>

    <?php include 'help_block.php' ?>
<?php endif; ?>

<?php include 'errors.php' ?>

<?php if ($showLabel && $showField): ?>
    <?php if ($options['wrapper'] !== false): ?>
    </div>
    <?php endif; ?>
<?php endif; ?>
```

Haven't tested it, but it should work.

**Comment by lbm-services** [comment]
Worked without $options['label_show'] and I had to comment out the two includes for help_block.php and errors.php.
Thank you for your help.

**Comment by pohkit91** [comment]
Currently I'm including the file instead of commenting out....
<?php include base_path() . '/vendor/kris/laravel-form-builder/src/views/help_block.php'; ?>
