### ISSUE TITLE
There is no _old_input in session after redirect

### ISSUE THREAD

**Issue by ahmadazimi** [kristijanhusak/laravel-form-builder#277]
Hi there,

I've faced a problem in all my forms which are using laravel-form-builder class and I've reported it in [Laravel repo](There is no _old_input in session after redirect):

In the login form which does not use laravel-form-builder, all thing okay, but in all other forms which I've used your library to creating them, when I redirect back with errors, a weird problem occurred: There is no _old_inputs key available in session.

Isi this my fault?

**Comment by kristijanhusak** [comment]
Hi,

which version are you using?
Can you try downgrading and see if it's fixed?

I'm using Session only to get stuff from it, i'm not changing/deleting anything inside it.

Just re-test with another version and let me know.

**Comment by awais300** [comment]
@ahmadazimi I have facing this strange issue. Were you able to solve it?

**Comment by celorodovalho** [comment]
@ahmadazimi I'm facing the same problem. How could you solve it?

**Comment by awais300** [comment]
@celorodovalho I was able to solve it, in my case I had to set the session driver to file in .env file. 
For example:
`SESSION_DRIVER=file`
Previously It was set to cookie. Cookies have size limit and my form was huge hence creating that issue.
