### ISSUE TITLE
Publish new version for Laravel 5.3? (lists method is deprecated)

### ISSUE THREAD

**Issue by eightyfive** [kristijanhusak/laravel-form-builder#280]
Hi,

I guess you are aware of `lists` deprecation in Laravel 5.3:
> The lists method on the Collection, query builder and Eloquent query builder objects has been renamed to pluck. The method signature remains the same.
https://laravel.com/docs/5.3/upgrade

Cause I see that in master brand, `EntityType` has been updated to match latest `Collection` API:
https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/EntityType.php#L54

As opposed to 1.8.0 branch:
https://github.com/kristijanhusak/laravel-form-builder/blob/1.8.0/src/Kris/LaravelFormBuilder/Fields/EntityType.php#L49

Do you have plan to publish on Packagist a quick new version of the package including that fix?

Thanks.

**Comment by kristijanhusak** [comment]
I just published version 1.9, with the fix included.

**Comment by eightyfive** [comment]
Thanks a lot!
