### ISSUE TITLE
Control over default "id" and "for" values

### ISSUE THREAD

**Issue by gbrock** [kristijanhusak/laravel-form-builder#285]
Using the following code:

``` php
$this->add('name', 'text');
```

...will render the following input:

``` html
<label for="name" class="control-label">Name</label>
<input class="form-control" name="name" type="text" id="name">
```

But `#name` is far too generic of an ID.  I foresee a potential collision issue, like if there are duplicates of the form on the same page.  **Is there a way to add a prefix or suffix to all automatically-generated values?**

I've been poking around but I honestly can't tell where to make such a change, if it doesn't already exist.  Here's how I'd expect to use such a feature (and how I intend to code a pull request, if I can figure it out):

---

I think my use case should be satisfiable by a configuration variable which is read when rendering:

``` php
    /** config/laravel-form-builder.php */
    'id_prefix' => 'input_',
```

It would also be useful to override the value for a specific form:

``` php
$form = FormBuilder::create(ArticleForm::class, [
    'method' => 'PUT',
    'url' => route('dashboard.article.create'),
    'id_prefix' => 'article_input_',
])
```

**Comment by kristijanhusak** [comment]
I just pushed a kind of solution to the `dev-master`. You can provide for each field a custom `id` and `for` attribute like this:

```php
$this->add('title', 'text', [
    'attr' => ['id' => 'my-custom-id'],
    'label_attr' => ['for' => 'my-custom-id']
]);
```

Just make sure you set up both to the same value if you are changing them, so it get's linked properly.
If you omit those, it will default to field name.

Hope this helps.

**Comment by kristijanhusak** [comment]
This is now added to the version 1.10.0. Thanks for reporting.
