### ISSUE TITLE
Assign a class id or some other attribute to a field

### ISSUE THREAD

**Issue by Gardezi1** [kristijanhusak/laravel-form-builder#287]
Hello guys first of all awesome package. But there is something I can't figure. I need to give some attributes to some field. How should I do it. Is there any example in which you guys have done this. If yes please direct me to that example. Thanks

**Comment by kristijanhusak** [comment]
Hello,

you can inject any attributes through `attr` option:

```php
$this->add('name', 'text', [
    'attr' => [
        'class' => 'my-class', 
        'data-custom-attribute' => 'custom attribute value'
    ]
]);
```

**Comment by Gardezi1** [comment]
I see. Well thanks for the prompt reply. Closing this issue
