### ISSUE TITLE
global attributes for labels

### ISSUE THREAD

**Issue by eness** [kristijanhusak/laravel-form-builder#290]
Hey there,

How can I set some global attributes (or override any) that will effect all types of fields? Config file would be a good choice or my class that extends Form class would be even better. For example, I would like to add `col-lg-2` class to the `<label>` tags but I don't want to add it every add() method I use. 

Is there any global pointer, array or method that would hold global options for all fields?

**Comment by kristijanhusak** [comment]
Just publish package configuration and set it up how you want. More info in the docs http://kristijanhusak.github.io/laravel-form-builder/custom/configuration-basics.html
