### ISSUE TITLE
File type array without collection

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#292]
Hi,
does it possible to use name like "attr['44232'][]" for file field type but don't use collection of file? Of course I can modify template. But when I try then I see error:
`tmlentities() expects parameter 1 to be string, array given `

im my template I use 
```
<?= Form::input($type, $name, $options['value'], $options['attr']) ?>
```
same like in original. My name parameter is `attr['44232'][]` by is string var_dump return string 'attr['44232'][]'.

When I use collection automatically I see 'attr['44232'][0]'
but I need to copy field in js and better solution is 'attr['44232'][]' when I'd like many fields control by js.

**Comment by kristijanhusak** [comment]
Hello,

collection field would be best for that http://kristijanhusak.github.io/laravel-form-builder/field/collection.html

If you use prototype, you should be able to generate additional fields without any issue, you have example in the docs. http://kristijanhusak.github.io/laravel-form-builder/field/collection.html#prototype

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak thanks
