### ISSUE TITLE
Entity bug in Laravel 5.3 + Fixed

### ISSUE THREAD

**Issue by SeregaSE** [kristijanhusak/laravel-form-builder#303]
Then i try to generate ```<select>``` from model like this  
```php
->add('author_id', 'entity', [
                 'class' => 'App\Models\Author',
                 'property' => 'name'
            ]);
```
i have this error:
**BadMethodCallException in Builder.php line 2450: Call to undefined method Illuminate\Database\Query\Builder::lists()**

To fix this, we need change createChildren() method in *laravel-form-builder\src\Kris\LaravelFormBuilder\EntityType.php*

From this:
```php
if ($queryBuilder instanceof \Closure) {
            $data = $queryBuilder($entity);
            if (is_object($data) && method_exists($data, 'lists')) {
                $data = $data->lists($value, $key);
            }
        } else {
            $data = $entity->lists($value, $key);
        }
```

To this:
```php
if ($queryBuilder instanceof \Closure) {
            $data = $queryBuilder($entity);
            if (is_object($data) && method_exists($data, 'lists')) {
                $data = $data->pluck($value, $key);
            }
        } else {
            $data = $entity->pluck($value, $key);
        }
```

**Comment by kristijanhusak** [comment]
@SeregaSE which version are you using?

**Comment by SeregaSE** [comment]
@kristijanhusak 1.6.*

**Comment by kristijanhusak** [comment]
@SeregaSE  please update to 1.9.* or later, it was fixed. https://github.com/kristijanhusak/laravel-form-builder/blob/master/CHANGELOG.md#190

**Comment by SeregaSE** [comment]
@kristijanhusak  Thanks you! I am just start work with composer and not a guru)

**Comment by kristijanhusak** [comment]
No problem :) Closing.
