### ISSUE TITLE
Confusing problem with using "entity" after sync

### ISSUE THREAD

**Issue by SebTM** [kristijanhusak/laravel-form-builder#304]
Hello,

first of all I wanna say thanks for this awesome library 👍 
I tried about two hours now how to debug this issue but I can't find the responsible part:

I've build a from with two fields, one text-field and one entity-field. If you save the form all data were saved - but in the form at the entity-field (checkboxes) the old values get still checked/the new values are missing. If you reload the page (without resending data) you will get the right result.

Field definition:
```php
->add('attributes', 'entity', [
                'class' => Attribute::class,
                'query_builder' => function (Attribute $attribute) {
                    return $attribute->orderBy('name');
                },
                'choice_options' => [
                    'wrapper' => ['class' => 'choice-wrapper'],
                ],
                'selected' => function ($data) {
                    return array_pluck($data, 'id');
                },
                'expanded' => true,
                'multiple' => true,
                'rules' => 'required',
            ]);
```

To debug I added these things to my controller:
`
var_dump('MODEL', array_pluck($model->attributes()->get(), 'id'));
var_dump('FORM_MODEL', array_pluck($form->getModel()->attributes()->get(), 'id'));
`
Both times I get the right values back!

Also I added a var_dump to the "selected"-closure and I really get the old data here. The confusing is: It also happend if I just create a complete new form-object after showing the data from model like above!

Do you have an idea how to solve it?

Best Regards!

**Comment by kristijanhusak** [comment]
How do you return to the page after those values gets messed up? Can you post controller code?

**Comment by SebTM** [comment]
Thanks for the Response - I did an example to reproduce the bug:

`
public function testUpdate($id, Request $request)
    {
        $role = Role::findOrFail($id);
        $form = FormBuilder::plain([
                'language_name' => 'cdou.role',
                'method' => 'POST',
                'model' => $role,
                'url' => route('testUpdate', ['id' => $role->id]),
            ])
            ->add('name', 'text')
            ->add('display_name', 'text')
            ->add('perms', 'entity', [
                'choice_options' => [
                    'wrapper' => ['class' => 'choice-wrapper'],
                ],
                'class' => Permission::class,
                'expanded' => true,
                'multiple' => true,
                'property' => 'display_name',
                'selected' => function ($data) {
                    return array_pluck($data, 'id');
                },
                'query_builder' => function (Permission $permission) {
                    return $permission->orderBy('display_name');
                },
            ])
            ->add('submit', 'submit');

        if ($request->isMethod('post')) {
            $form->redirectIfNotValid();

            $role->fill($form->getFieldValues());
            $role->save();

            $role->perms()->sync(Input::get('perms'));
        }

        return View::make('cdou.form', ['form' => $form]);
    }
`

From just shows "$form".

**Comment by kristijanhusak** [comment]
I think the issue appears because you don't re-fetch the model after update. 
So you do the update in this `if post` block, and return the view with the $form, that has values before saving. Basically, after the update, everything should be re-run from the beginning.
Here's few advice regarding your code, which will probably fix the issue:

* Split different requests to separate methods (move post part to another method)
* Create Form class instead of using plain, it's cleaner, especially because this form is not so small

Something like this should work out:

```php
// RoleForm.php
// Do all imports here for models
class RoleForm extends Form {
    public function buildForm()
    {
        $this
            ->add('name', 'text')
            ->add('display_name', 'text')
            ->add('perms', 'entity', [
                'choice_options' => [
                    'wrapper' => ['class' => 'choice-wrapper'],
                ],
                'class' => Permission::class,
                'expanded' => true,
                'multiple' => true,
                'property' => 'display_name',
                'selected' => function ($data) {
                    return array_pluck($data, 'id');
                },
                'query_builder' => function (Permission $permission) {
                    return $permission->orderBy('display_name');
                },
            ])
            ->add('submit', 'submit');
    }
}

// Controller.php
public function testEdit($id, Request $request)
{
    $role = Role::findOrFail($id);
    $form = FormBuilder::create(Forms\RoleForm::class, [
        'language_name' => 'cdou.role',
        'method' => 'POST',
        'model' => $role,
        'url' => route('Controller@testUpdate', ['id' => $role->id]),
    ]);

    return View::make('cdou.form', ['form' => $form]);
}

public function testUpdate($id, Request $request)
{
    $role = Role::findOrFail($id);
    $form = FormBuilder::create(Forms\RoleForm::class, [
        'language_name' => 'cdou.role',
        'method' => 'POST',
        'model' => $role,
        'url' => route('Controller@testUpdate', ['id' => $role->id]),
    ]);

    $form->redirectIfNotValid();
    $role->fill($form->getFieldValues());
    $role->save();
    $role->perms()->sync(Input::get('perms'));

    return redirect()->action('Controller@testEdit');
}

```

**Comment by SebTM** [comment]
Solved thx
