### ISSUE TITLE
Allow null in 'entity'

### ISSUE THREAD

**Issue by calina-c** [kristijanhusak/laravel-form-builder#306]
Hi! First of all thank you for the great library, I appreciate your efforts!

I was wondering if there is an option for allowing null as a selected option with the 'entity' field. It seems to get the first from the query as default, even if I add "selected" => null as an option.

Any help would be appreciated. Thank you!

**Comment by kristijanhusak** [comment]
Hi @calina-c ,

How do you structure your Entity field, as a select, or something else?

**Comment by calina-c** [comment]
Hi @kristijanhusak!

Short story: yes, select.
Long story: I apply selectize.js over it because it's a large dataset so I fetch it using autocomplete if needed. However, solving the issue with the underlying selector would probably suffice.

**Comment by kristijanhusak** [comment]
You can add `empty_value` string to options, which will be treated as an null value. More info here http://kristijanhusak.github.io/laravel-form-builder/field/select.html

**Comment by calina-c** [comment]
Thank you @kristijanhusak, I managed to solve the problem. Closing this now :)
