### ISSUE TITLE
Compatibility Laravel 5.4

### ISSUE THREAD

**Issue by reno1979** [kristijanhusak/laravel-form-builder#307]
version tested 1.10.0

On composer update, during optimize I get: 

Call to undefined method Illuminate\Session\Store::getToken()

**Comment by yopop666** [comment]
Please give me if you can configuration of this package in composer.json for laravel 5.4.

**Comment by soszin** [comment]
Kris\LaravelFormBuilder\FormHelper::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface, instance of Illuminate\Translation\Translator

FormHelper Class require TranslatorInterface but $app['translator'] return Illuminate\Translation\Translator

"return new FormHelper($app['view'], $app['translator'], $configuration);" ---> [FormBuilderServiceProvider line:45]

**Comment by reno1979** [comment]
@yopop666  Could you please elaborate on that? 

At the moment we are trying again.

**Comment by reno1979** [comment]
all seems ok now, the composer update runs like a charm. The actual form building is tested later.

**Comment by joelcuevas** [comment]
Same here. It seems that `getToken()` was renamed to just `token()` in L5.4. Hope PR #310 gets accepted soon.

**Comment by stefanbaas** [comment]
I'm a colleague of Reno1979. The composer update went well in Laravel 5.4, but when i'm using the form builder i get the same error as @soszin https://github.com/kristijanhusak/laravel-form-builder/issues/307#issuecomment-275148061

@kristijanhusak @mauricius
Can you fix this please?

**Comment by fillzadebayo** [comment]
find the html service provide file `htmlServiceProvider.php`
and change this line from
`$form = new FormBuilder($app['html'], $app['url'], $app['view'], $app['session.store']->getToken());`
to
`$form = new FormBuilder($app['html'], $app['url'], $app['view'], $app['session.store']->token());`
