### ISSUE TITLE
HtmlString not respected everywhere

### ISSUE THREAD

**Issue by rudiedirkx** [kristijanhusak/laravel-form-builder#326]
I'm not sure if it's Twig, or the form builder, or me, but my values are html encoded when I don't want that. I have a `choice` element with `HtmlString` options:

```
$this->add('professions', 'choice', [
  'label' => trans('report.taco_test.professions'),
  'choices' => $favorites_options,
  'multiple' => TRUE,
  'expanded' => TRUE,
]);
```

but the options are HTML encoded, so I see

    Bijrijder <span class="meta level">(Elementair)</span> <span class="meta country-region">- Belgi&euml; (NL)</span>

instead of

    Bijrijder (Elementair)- België (NL)

I've traced it back to my `checkbox.twig`:

```
{% if options.is_child  %}
  <label {{ options.labelAttrs|raw }}>{{ options.label }}</label>
{% else %}
  {{ form_label(name, options.label, options.label_attr) }}
{% endif %}
```

`form_label()` always works, because it uses `e()` for encoding, which respects `HtmlString`, but `{{ options.label }}` doesn't work, because it always always encodes. That's probably Twig's fault, but since `form_label()` (`Form::label()` in `checkbox.php`) always works, why isn't that used?

Then I got to debugging and tried a few more places:

* The label of a single `checkbox` field respects `HtmlString`
* The label of a `choice` field **doesn't** respect `HtmlString`
* The options labels of that `choice` field (HTML if it's `expanded`) **don't** respect `HtmlString`

**Comment by kristijanhusak** [comment]
@rudiedirkx that looks like old view structure. If you look at the new one, it uses custom macro that i create in service provider (https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/views/select.php)

**Comment by rudiedirkx** [comment]
Very newest version still doesn't seem to work:

```
$this->add('types', 'choice', [
	'label' => new HtmlString('Types <em>(36)</em>'),
	'choices' => [
		'a' => new HtmlString('Aaa <em>12</em>'),
		'b' => new HtmlString('Bbb <em>12</em>'),
		'c' => new HtmlString('Ccc <em>12</em>'),
	],
	'expanded' => true,
	'multiple' => true,
]);
```

doesn't respect `HtmlString`. All html is encoded.

`var_dump($value);` in the `customLabel` macro prints the `HtmlString` object, so maybe it's `Collective\Html`'s fault?

This is the only one that did work in my old project:

```
$this->add('private', 'checkbox', [
	'label' => new HtmlString('Private address <em>(bla)</em>'),
]);
```

but now it doesn't anymore... `var_dump($value);` in `customLabel` is the correct object. `Collective\Html`'s fault?

**Comment by rudiedirkx** [comment]
Yes, it is their fault:

```
public function entities($value)
{
    return htmlentities($value, ENT_QUOTES, 'UTF-8', false);
}
```

doesn't respect `HtmlString`. With that fixed, all scenario's work.

**Comment by rudiedirkx** [comment]
Relevant: https://github.com/LaravelCollective/html/pull/305

**Comment by Fellner96** [comment]
For the label escape:

In your AppServiceProvider:

`$form->macro('customLabel', function ($name, $value, $options = []) use ($form) {
            $escape = !isset($options['escape']);

            if (isset($options['for']) && $for = $options['for']) {
                unset($options['for']);

                return $form->label($for, $value, $options, $escape);
            }

            return $form->label($name, $value, $options, $escape);
        });`

Then you can use:
```
'label' => new HtmlString('Label <i class="fa fa-plus"></i>'),
                'label_attr' => [
                    'escape' => 'escape'
                ],
```

**Comment by rudiedirkx** [comment]
The bug is in `LaravelCollective/html`, so it should be fixed there. I'm using a patch for my projects, because they don't want to fix it.
