### ISSUE TITLE
Needed cancel type too

### ISSUE THREAD

**Issue by sitapraj** [kristijanhusak/laravel-form-builder#33]
Avaiable types are: text, email, url, tel, search, password, hidden, number, date, textarea, submit, reset, button, file, image, select, checkbox, radio, choice, form, repeated.
Needed cancel type too. To cancel the form and to redirect

**Comment by kristijanhusak** [comment]
that type of "button" is not form type, it's an anchor. Split the form in the view and add anchor where you want.
