### ISSUE TITLE
Two properties for entity type property

### ISSUE THREAD

**Issue by LourensThalen** [kristijanhusak/laravel-form-builder#333]
I'd like to use combined property for an entity selector. Now I'm using: 
```
 'property' => 'last_name',
```
but I'd like to use both first_name and last_name. I'm using a fullName() function in my User model but I can't use that one. How can I change it so it uses the fullName() function without it breaking in future updates?

Oh, and I love the form builder. Thank you.

**Comment by LourensThalen** [comment]
Never mind, this is me being stupid. Sorry, this has been fixed.

**Comment by lk77** [comment]
Hello,

same problem,
i tried closure and also tried virtual property, but it's not working.

what is your solution?

**Comment by LourensThalen** [comment]
In the User model, I added a full_name attribute-function and referenced that one. 
```
    public function getFullNameAttribute() {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }
```
This way you can use full_name as a property in your form.

**Comment by lk77** [comment]
i have 
`public function getFormatOrientationAttribute(){..}`
and
`'property' => 'format_orientation'`
and it's not working, it says Unknown column 'format_orientation' in 'field list
i don't know why

**Comment by LourensThalen** [comment]
You do get the correct model? If you change it for a different attribute everything works?

**Comment by lk77** [comment]
yes, it's the correct model, and i i set an attribute that really exist, it works.

**Comment by lk77** [comment]
I'm on 1.6.0,
i will try to update to 1.11.0.

**Comment by lk77** [comment]
my entity field is on a collection of form, perhaps it's the problem

**Comment by ericsts** [comment]
I have this same problem, without works:

Model Category
`    public function getFullNameAttribute() {
        return $this->code . ' - ' . $this->name;
    }
`

Form
`            $this->add('category_id', 'entity', [
                'label' => 'Parent Categ',
                'class' => '\PSS\Models\Category',
                'property' => 'name',
                'empty_value' => ' - blank - ',
                // 'property' => 'full_name',
            ])
`

**Comment by lorenzo-milesi** [comment]
Not working for me neither, same thing, 
works well with an existing field 
but does not with custom attribute, for instance `getCustomAttribute` on Model, and `'property' => 'custom'` :'( too bad, 
is there any workaround :) ?

**Comment by lorenzo-milesi** [comment]
Found one ! 

Here : 
1. use entity **but** use `choices` instead of `class`
2. in `choices` put your array (you can build an array with the following method : 
```php
protected function choices($model, $attribute) {
    $items = $model::all();
    $choices = [];
    foreach($items as $item) {
        $choices[$item->id] = $item->$attribute;
    }
    return $choices;
}
```
I put `protected` on it because I created a higher level class but you are not compelled to do the same, `private` is fine,

3. Just call the function with your model and your custom attribute, for instance :

```php 
$choices = $this->choices(User::class, 'full_name');
```

/!\ If your model is empty, the array will also be empty (dah !) but unfortunately `entity` field type does not seem to work with `choices` on empty arrays so be sure to redirect or do something else if you have an empty array !

Nice evening :)
