### ISSUE TITLE
Bootstrap 4 support.

### ISSUE THREAD

**Issue by jaesung2061** [kristijanhusak/laravel-form-builder#337]
Are there plans to support bootstrap 4?

**Comment by ycs77** [comment]
You can use this Bootstrap 4 template: https://github.com/ycs77/laravel-form-builder-bs4
Used after installation & publish. (Will overwrite the Laravel form builder's original config and views)

**Comment by kristijanhusak** [comment]
@ycs77 Thanks! I added link in readme https://github.com/kristijanhusak/laravel-form-builder#bootstrap-4-support

**Comment by ycs77** [comment]
Your welcome!
