### ISSUE TITLE
child form options not respected

### ISSUE THREAD

**Issue by nekromoff** [kristijanhusak/laravel-form-builder#338]
e.g. class is not set on containing element

Thus it is impossible to have e.g. inline child form wrapped in the normal parent form.

**Comment by kristijanhusak** [comment]
Please post some example code which fails to achieve what you want.

**Comment by nekromoff** [comment]
I have found the need to use wrapper, however this is poorly documented for
the child forms.

->add('Items', 'form', [
                'class' => '\App\Forms\ItemForm',
                'wrapper' => [ 'class' => 'form-inline items'],
                'label_show' => false,
            ])

**Comment by kristijanhusak** [comment]
@nekromoff did you set it up at the end?
Yeah documentation is not the best, i don't have time to write it down properly unfortunately.

**Comment by nekromoff** [comment]
Yep, you can close.

**Comment by kristijanhusak** [comment]
Ok, thanks.
