### ISSUE TITLE
Extensible RulesParser

### ISSUE THREAD

**Issue by rudiedirkx** [kristijanhusak/laravel-form-builder#340]
For some rules, the form builder automatically adds HTML validation attributes. Perfect. But not for the `regex` rule. It adds `pattern` attributes sometimes, but not for the `regex` rule. And there might be more (custom) validations that could auto-add attributes.

If you'd make the `RulesParser` extensible, anyone could add this 'rule to attribute' logic. Maybe a `createRulesParser()` method in the `FormHelper`, because the form helper is already extensible.

**Comment by barryvdh** [comment]
The reason pattern is not always added, is because it's not always the same in HTML5 as php, so can be a bit confusing.

**Comment by rudiedirkx** [comment]
Fair enough. What about making it extensible so I can choose to use JS-safe regexes only?

**Comment by barryvdh** [comment]
Makes sense to me, but not my package :)

**Comment by rudiedirkx** [comment]
Yeah Barry! What are you doing here anyway :stuck_out_tongue:

Kris is better with the PRs, so I'll do that soon.

I totally missed your link to #144 btw. Good context. Thanks for clarification.
