### ISSUE TITLE
Form Collection custom layout

### ISSUE THREAD

**Issue by Nardusgc** [kristijanhusak/laravel-form-builder#341]
Hi ,
First of thank you for this awesome package. 

I have a question regarding the rendering of collections ( please excuse me if I miss understood something)

I have the need to render my collection in a table format. So my question is is it possible currently to access a child form element as you would access a normal form element like in the example below. 
```\\Normal element
form_row($form->field_one)

\\Collection Item 
form_row($form->collection->collection_elem_one)
``` 

Or something similar? 

Thank you.

**Comment by kristijanhusak** [comment]
@Nardusgc 
You should be able to do something like this:

```php
foreach ($this->collectionField as $singleField) {
  form_row($singleField);
}
```

**Comment by Nardusgc** [comment]
@kristijanhusak 

Thank you very much for the reply, I ended up creating a custom template and passing that to the child form. Which gave me the result I wanted. 

```
->add('orderItem', 'collection', [
                'label' => false,
                'type' => 'form',
                'options' => [
                    'class' => OrderItem::class,
                    'label' => false,
                    'template' => 'templates.table',
                ]
            ])
```

**Comment by kristijanhusak** [comment]
@Nardusgc  ok great. Closing this.
