### ISSUE TITLE
Entity element with selected value $data is null

### ISSUE THREAD

**Issue by uovidiu** [kristijanhusak/laravel-form-builder#360]
Hi there,

I've spend a whole day trying to figure this out, no luck. Last resort is here.

I don't know why $data in `'selected' => function ($data)` in selected is always null.
`dd($this->model->addresses()->pluck('country_id')->toArray())` - return what It's supposed to. But ofcourse that I can't use it even if assigned to a variable because Laravel. Without dd(), when I try to assign to a variable 
```
$data = $this->model->addresses()->pluck('country_id')->toArray()
```
I get this error: **Call to undefined method Illuminate\Database\Query\Builder::addresses()**

I'm using [Laravel Address](https://github.com/Lecturize/Laravel-Addresses) to link address to a Client.

Architecture
AddressForm.php - entity type

```php

->add('street', 'text', [
    'rules' => 'required',
])

->add('country', 'entity', [
    'class' => Countries::class,
    'query_builder' => function (Countries $countries) {
	    return $countries->pluck('full_name', 'id')->toArray();
    },
    'selected' => function ($data)  {
//	$data = $this->model->addresses()->pluck('country_id')->toArray();
        return array_pluck($data, 'id', 'name');
        return $data;
    },
    'property' => 'full_name',
    'property_key' => 'id',
    'multiple' => false,
    'expanded' => false,
    'choice_options' => [
	    'wrapper' => ['class' => 'choice-wrapper'],
    ],

])
```

ClientForm.php - using collection
```php
		    ->add('company_name', 'text', [
			    'rules' => 'required|min:5',
		    ])
			
		    ->add('addresses', 'collection', [
			    'type' => 'form',
			    'property' => 'id',
			    'wrapper' => ['class'=> 'clearfix'],
			    'options' => [    // these are options for a single type
				    'class' => 'Quickwater\Forms\AddressForm',
				    'label' => false,
                ],
			    'label_show' => false,
            ])
```

ClientsController.php 
```php

	public function edit(Client $client)
	{

		$form = $this->form(ClientForm::class, [
			'language_name' => 'translations',
			'method' => 'PUT',
			'model' => $client,
			'url' => route('clients.update', ['id'=>$client->id]),
		]);

		return view('clients.edit', compact('form'));
	}

```

Thinker output when calling `$client->addresses()->first()`
```php
>>> $client->addresses()->first()
=> Lecturize\Addresses\Models\Address {#845
     id: 1,
     street: "123 Example Drive",
     city: "Vienna",
     state: "",
     post_code: "1110",
     country_id: 40,
     note: "",
     lat: null,
     lng: null,
     addressable_id: 1,
     addressable_type: "client",
     is_public: 0,
     is_primary: 1,
     is_billing: 0,
     is_service: 0,
     created_at: "2017-06-22 15:50:17",
     updated_at: "2017-06-22 15:50:17",
     deleted_at: null,
   }
```

What I'm trying to do is to use country_id  value to select the Country dropdown on edit.

**Comment by kristijanhusak** [comment]
@uovidiu try fetching the `$client` with the addressess using `with()` method (https://laravel.com/docs/5.4/eloquent-relationships#eager-loading).
```php
$client = Client::with('addresses')->get();
```
If you have child form, it expects data to exist on a model as a property, not as a method. So when you fetch with the association, you will be able to access addresses this way `$client->addresses` (note the missing braces)

**Comment by uovidiu** [comment]
I have no idea why but without 'selected' works as expected without a problem

Thank you for your response.
