### ISSUE TITLE
Default data not being set

### ISSUE THREAD

**Issue by jaesung2061** [kristijanhusak/laravel-form-builder#361]
Here is my form:

    public function buildForm()
    {
        $this
            ->add('quote', 'textarea', [
                'rules' => 'required'
            ])
            ->add('person_name', 'text', [
                'rules' => 'required'
            ])
            ->add('person_title', 'text', [
                'rules' => 'required'
            ])
            ->add('company_name', 'text', [
                'rules' => 'required'
            ]);
    }

Here is the controller:

    public function edit(Testimonial $testimonial, FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(TestimonialForm::class, [
            'method' => 'patch',
            'url' => "/admin/testimonials/$testimonial->id"
        ], $testimonial->toArray());

        return view('admin.testimonials.edit', compact('testimonial', 'form'));
    }

As you can see I'm passing `$testimonial->toArray()` as the third function expecting them to appear in value fields.

The testimonial dumped:

```
array:7 [▼
  "id" => 3
  "quote" => "Molestias est cumque magni est. Quia nisi eveniet deserunt dolore a totam. Deleniti delectus est dolore non. Quia mollitia explicabo earum aut sint illo asperna ▶"
  "person_name" => "Scarlett Predovic IV"
  "person_title" => "Prof."
  "company_name" => "Marks-Buckridge"
  "created_at" => "2017-06-23 18:35:50"
  "updated_at" => "2017-06-23 18:35:50"
]
```

**Comment by kristijanhusak** [comment]
@jaesung2061 you do not pass form data that way. You pass it as model in the 2nd argument:
```php
    $form = $formBuilder->create(TestimonialForm::class, [
        'method' => 'patch',
        'url' => "/admin/testimonials/$testimonial->id",
        'model' => $testimonial->toArray(),
    ]);
```
Third argument is data that you can access within the form class, if you need to use some checking or whatever. More info here http://kristijanhusak.github.io/laravel-form-builder/form/basics.html

**Comment by jaesung2061** [comment]
Got it, thanks.

**Comment by jaesung2061** [comment]
@kristijanhusak I also have a question about over-riding templates. Is this possible? I can't seem to find it in the readme.

**Comment by jaesung2061** [comment]
Nevermind, I found out.
