### ISSUE TITLE
Add a custom class to the form or form elements so I can have custom css changes?

### ISSUE THREAD

**Issue by rxmg-nickk** [kristijanhusak/laravel-form-builder#362]
I didn't see that in the docs but is there a way to add custom class to the form or individual elements so I can style it myself?

I may have missed it in the docs.

**Comment by kristijanhusak** [comment]
http://kristijanhusak.github.io/laravel-form-builder/form/basics.html#form-options

http://kristijanhusak.github.io/laravel-form-builder/field/fieldbasics.html

**Comment by rxmg-nickk** [comment]
Thank you and thank you for the awesome library!
