### ISSUE TITLE
How to get Value from input

### ISSUE THREAD

**Issue by alederzz** [kristijanhusak/laravel-form-builder#370]
Hi Kris, I'm trying to get the value of my field name, but I get NULL

```
$form = $formBuilder->create(UserCreate::class);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        dd($form->getField('name'));
```
or
`  dd($form->getField('name')->getValue();`
or
`  dd($form->name);`

I must say that I tried with "getFieldValues", but this does not encrypt the password:
`Post::create($form->getFieldValues());`

**Comment by kristijanhusak** [comment]
Hi @alederzz ,
`getFieldValues()` is a way to go.
Add password encryption on the model level. Something like this:

```php
class Post {
  public function setPasswordAttribute($value)
  {
    $this->attributes['password'] = mcrypt($value);
  }
```

Not sure if above code is 100% correct, since i haven't done it for some time, and i didn't check the docs.
