### ISSUE TITLE
[Laravel 4] One-to-many nested form collections

### ISSUE THREAD

**Issue by lordjancso** [kristijanhusak/laravel-form-builder#38]
Hi!
Is this possible to create nested form collections for one-to-many relationships?
Its something like 'form' form type here, but not for a single form, but with a collection of forms.
And is there any prototyping solution, just like in Symfony2's collection form type?
Thank you very much!

**Comment by kristijanhusak** [comment]
Hi,

At this moment that functionality is not supported. I'm planning to add it in the future versions. 
Will let you know when it's added :)
