### ISSUE TITLE
Reference collection item model id in unique rules

### ISSUE THREAD

**Issue by zlincoln** [kristijanhusak/laravel-form-builder#386]
```php
class ClassroomForm extends \Kris\LaravelFormBuilder\Form
{
    public function buildForm()
    {
        $this
            ->setMethod('POST')
            ->add('students', 'collection', [
                'type' => 'form',
                'options' => [
                    'class' => StudentForm::class,
                ],
            ])
            ->add('submit', 'submit');
    }
}

class StudentForm extends \Kris\LaravelFormBuilder\Form
{
    public function buildForm()
    {
        $STUDENT_ID = null; // How do I capture this value?

        $this
            ->add('id', 'hidden')
            ->add('email', 'email', [
                'rules' => [
                    'required',
                    'email',
                    (new Unique('students', 'email'))
                        ->ignore($STUDENT_ID, 'id'),
                ],
            ]);
    }
}
```
There doesn't seem to be an intuitive way to reference the individual item of a collection when defining fields in a child form. Does the library support this? If not, could you advise the best way of implementing it independently? Me and my team have been trying increasingly creative things with little success.

It would be valuable to be able to pluck values from the child item form model/request both when defining fields and when specifying options for those fields.
- Use Case for Configuring Options: Defining unique rules for bulk-updating (see above)
- Use Case for Configuring Fields: optionally adding a static field to show some extra data (eg if the model has an img, include a static field with an img tag)

**Comment by kristijanhusak** [comment]
@zlincoln Unfortunately can't think of a simple way to do this. One thing that crossed my mind is to allow using closure when defining rules, and that closure would send down the necessary information.  Something like this:
```php
     $uniqueClosure = function($value, $name) {
         return (new Unique('students', 'email'))->ignore($value, 'id');
     };
     $this
            ->add('id', 'hidden')
            ->add('email', 'email', [
                'rules' => [
                    'required',
                    'email',
                    $uniqueClosure
                ],
            ]);
```

I don't have time to do that at this moment, but if you have time to do it, i'll gladly review the PR.

**Comment by zlincoln** [comment]
Thanks for getting back to us, especially so quickly @kristijanhusak.  We may take a stab at that next week.  Closing until then..

**Comment by kristijanhusak** [comment]
I added initial version of the solution to the dev master (Commit https://github.com/kristijanhusak/laravel-form-builder/commit/b2c8b75d7a6edfe43994f7a6799ac9bdafb7cdb6). You should be able to do something like this now:

```php
     $uniqueClosure = function($name) {
         $value = $this->getRequest()->input($name);
         return (new Unique('students', 'email'))->ignore($value, 'id');
     };
     $this
            ->add('id', 'hidden')
            ->add('email', 'email', [
                'rules' => [
                    'required',
                    'email',
                    $uniqueClosure
                ],
            ]);
```

Please give it a try and let me know if it works out.
