### ISSUE TITLE
How to reference a relationship as choices for Select Field?

### ISSUE THREAD

**Issue by BrunoMCTeixeira** [kristijanhusak/laravel-form-builder#389]
I'm unable to find any documentation related to dynamic Select Fields, can someone provide an example? Thanks

**Comment by tpfuhl** [comment]
I join myself to this request. Would be great to integrate related tables via th foreign key into the main form.

**Comment by tpfuhl** [comment]
Hello Kris, I try to to create a form making use of the foreign key referencing another table ('members'), and displaying only 1 field of that  table. For the moment, I have this, but I could not figure out how to hide all but one field of the referenced table. 

```
<?php
namespace App\Forms;
use Kris\LaravelFormBuilder\Form;
class DepositsForm extends Form
{
    public function buildForm()
    {
        $this
            ->add('id', 'hidden')
            ->add('amount', 'number')
            //->add('member_id', 'number')
            ->add('member', 'form', [
                'class' => 'App\Forms\MembersForm',
                'wrapper' => ['class' => 'form-group', 'style'=>'padding:1em;border:2px solid red'],
                'formOptions' => []
            ])
            //->remove('submit')->remove('clear')
            ->add('submit', 'submit', ['label' => 'Save',  'attr' => ['class' => 'btn btn-success']])
            ->add('clear', 'reset',  ['label' => 'Reset', 'attr' => ['class' => 'btn btn-warning']])
          ;
    }
}
```

**Comment by kristijanhusak** [comment]
I'm not 100% sure what you mean by dynamic select field, but you can use Entity type and pass in query_builder closure to filter out the data. http://kristijanhusak.github.io/laravel-form-builder/field/entity.html

**Comment by tpfuhl** [comment]
This is the solution. Just one more question: I  want the selectbox show only the entry with the corresponding id, not all list items. I guess this is handled in the whereclause of the querybuilder but I do not know how to pass the Form's id:
```
 'query_builder' => function (App\Language $lang) {
            return $lang->where('id', <the Form's id>);
```
Anyhow, Thanks for your great work, Kris !

**Comment by tpfuhl** [comment]
right. perfect !
