### ISSUE TITLE
form($form) produces nothing

### ISSUE THREAD

**Issue by warlord0** [kristijanhusak/laravel-form-builder#393]
I'm obviously missing something with my limited Laravel knowledge, but when I setup the create blade view like this:

create.blade.php
```php
Form or no form?
@section('content')
    {!! form($form) !!}
@endsection
```

I get no form creation output at all.

If I `dd($form)` then I get output showing me that the `$form` object is created. But I can't figure out why I get nothing in the html output.

The routes etc. must be ok as I get to the page and see `form or no form?` but nothing else.

Any pointers much appreciated.

```text
$ composer show                                                   [±master ●]
...
kris/laravel-form-builder             1.13.0  Laravel form builder - symfon...
laravel/framework                     v5.5.25 The Laravel Framework.
```

**Comment by kristijanhusak** [comment]
If you remove form($form) part and put some static text inside the section, does that text show up in html?
Also which laravel version do you use?

**Comment by warlord0** [comment]
Wow, I'm such a doofus 👍 Maybe if I actually yield or show the section it would work. Sorry to have bothered you. Thanks for the quick response.

I look forward to making more use of this.
