### ISSUE TITLE
Choices without Key Value Pairs

### ISSUE THREAD

**Issue by warlord0** [kristijanhusak/laravel-form-builder#394]
I've created a form and I'm getting the data fed into using a collection that I pluck to an array. The key and the value are not important because it is a flat array and the key and value are the same. But I can't figure out how to use the flat array without the option being given an arbitrary number.

```php
class BuildCtrlForm extends Form
{
    public function buildForm()
    {

      $scheme = FindByFullAddress::select('SenderCode')
        ->orderBy('SenderCode')->distinct()
        ->pluck('SenderCode')->toArray();

        $this
            ->add('SenderCode', 'select', [
              'label' => 'CP Scheme',
              'choices' => $scheme,
              'empty_value' => '-- Select Scheme --'
            ])
```

This generates the html select and options:
```html
  <label for="SenderCode" class="control-label">CP Scheme</label> 
  <select class="form-control" id="SenderCode" name="SenderCode">
    <option value="" selected="selected">-- Select Scheme --</option>
    <option value="0">APHC</option>
    <option value="1">BBA</option>
    <option value="2">BESCA</option>
    <option value="3">BMCL</option>
...
  </select>
```

But what I want is the option value to be the option description too.

```html
    <option value="APHC">APHC</option>
```
Is this possible? Or do I have to create a key value pair to pass in?

**Comment by arsydb** [comment]
Try:

`
$scheme = FindByFullAddress::select('SenderCode')
        ->orderBy('SenderCode')
        ->distinct()
        ->pluck('SenderCode', 'SenderCode')
        ->toArray();
`

**Comment by warlord0** [comment]
Wonderfully simpler idea than I've used. Thank you.
