### ISSUE TITLE
Php 7.2 compatibility

### ISSUE THREAD

**Issue by therezor** [kristijanhusak/laravel-form-builder#396]
Currently package is not compatible with php 7.2
`[2017-12-15 11:41:11] local.ERROR: count(): Parameter must be an array or an object that implements Countable {"userId":1,"email":"**hidden**","exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /home/vagrant/Code/my-project-name/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Fields/CollectionType.php:101)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/home/vagrant/C...', 101, Array)
#1 /home/vagrant/Code/my-project-name/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Fields/CollectionType.php(101): count(NULL)
#2 /home/vagrant/Code/my-project-name/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Fields/ParentType.php(35): Kris\\LaravelFormBuilder\\Fields\\CollectionType->createChildren()
#3 /home/vagrant/Code/my-project-name/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Form.php(181): Kris\\LaravelFormBuilder\\Fields\\ParentType->__construct('params', 'collection', Object(App\\Forms\\Marketing\\OfferForm), Array)
#4 /home/vagrant/Code/my-project-name/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Form.php(205): Kris\\LaravelFormBuilder\\Form->makeField('params', 'collection', Array)
#5 /home/vagrant/Code/my-project-name/app/Forms/Marketing/OfferForm.php(40): Kris\\LaravelFormBuilder\\Form->add('params', 'collection', Array)
#6 /home/vagrant/Code/my-project-name/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/FormBuilder.php(65)`

**Comment by kristijanhusak** [comment]
I released version 1.14.0 with the fix for the php 7.2.

**Comment by therezor** [comment]
Thanks for the great support
