### ISSUE TITLE
validation required_without not working

### ISSUE THREAD

**Issue by mavichow** [kristijanhusak/laravel-form-builder#401]
I've created a Tags Form contain 2 fields...

Title ( required )
File ( required if 'Title' field is empty )

but **required_without:title** validaitons seems not working

```
//Tags form
public function buildForm()
{
    $this
        ->add('title', 'text', [
            'label' => 'Title',
            'rules' => 'min:5',
        ])
        ->add('file', 'file', [
            'label'    => 'Image',
            'rules'    => 'required_without:title|image',
        ]);
}
```

What if the Form added Tags form as Children Form of **Gallery form**, should the file rules modify to `'rules'    => 'required_without:title.*|image',` but the validation not working too

```
//Gallery form
public function buildForm()
{       
    $this
        ->add('tag_collections', 'collection', [
            'type'  => 'form',
            'options' => [    // these are options for a single type
                'class' => 'App\Forms\Tags',
                'label' => false,
            ]
        ]);
}
```

thanks alot!

**Comment by kristijanhusak** [comment]
Is it working if you use TagsForm as main form, and not as a children of Gallery form?

**Comment by mavichow** [comment]
Sorry, forgot to mentioned. Its not working on both form...

**Comment by kristijanhusak** [comment]
@mavichow It works properly for me when TagsForm is used as a main form.
I found some issues when it is validated as a collection of child forms, because required_without requires proper name for reference. Still working on the solution.

How are you triggering validation? Were you able to get any validation errors out of this?
