### ISSUE TITLE
Collection type empty value.

### ISSUE THREAD

**Issue by Fellner96** [kristijanhusak/laravel-form-builder#409]
Hi.
If i pass null, false, or empty array to the "data" attribute of the collection, it's show minimum 1 form of these.

Here is my code:
`
$this->add('work', 'collection', [
            'type'     => 'form',
            'property' => 'id',
            'data'     => $this->model->workHistory,
            'options'  => [
                'label'   => false,
                'class'   => $this->formBuilder->create(WorkFields::class),
                'wrapper' => ['class' => 'work-item'],
            ],
            'wrapper'  => ['class' => 'work-panel'],
        ])
`

Any idea? I will make a pull request with a fix of it.

**Comment by kristijanhusak** [comment]
Pass in `'empty_row'  => false` through options and that will remove that single row

**Comment by Fellner96** [comment]
Thanks for the fast answer. It works well! I found it afterwards in the documentation, so sorry.

**Comment by kristijanhusak** [comment]
No problem :)
