### ISSUE TITLE
DateTime Custom Field

### ISSUE THREAD

**Issue by imyque** [kristijanhusak/laravel-form-builder#41]
Hello Kristi,

Thank you for this project.

Please could you send me a sample for a datetime custom field, I really need it for my project.

Thanks

**Comment by kristijanhusak** [comment]
Hi imyque,

You can try to create it yourself, it shouldn't need much effort.

you need `<input type="datetime">` ?

**Comment by imyque** [comment]
Hi kristijanhusak, 

I took you advice, but it did take me some effort to get what I wanted, using https://github.com/smalot/bootstrap-datetimepicker. So I thought I should share it so that you can possibly include it as part of the standard fields.

Here are my codes:

**resources/views/fields/datetime.blade.php**

        <?php if ($showLabel && $showField && !$options['is_child']): ?>
        <div <?= $options['wrapperAttrs'] ?> >
            <?php endif; ?>

            <?php if ($showLabel): ?>
            <?= Form::label($name, $options['label'], $options['label_attr']) ?>
            <?php endif; ?>

            <?php if ($showField): ?>
                <div class="input-group date {{ $options['div_class'] }}" data-date="1979-09-16T05:25:07Z" data-date-format="{{ $options['dt_format'] }}" data-link-field="{{ $name }}_hidden">
                    <?= Form::input($type, $name, $options['default_value'], $options['attr']) ?>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                </div>
                <input type="hidden" id="{{ $name }}_hidden"    value="" /><br/>
            <?php endif; ?>

            <?php if ($showError && isset($errors)): ?>
            <?= $errors->first(array_get($options, 'real_name', $name), '<div '.$options['errorAttrs'].'>:message</div>') ?>
            <?php endif; ?>

            <?php if ($showLabel && $showField && !$options['is_child']): ?>
        </div>



        <script type="text/javascript" src="{{ asset('js/jquery-1.8.3.min.js') }}" charset="UTF-8"></script>
        <script type="text/javascript" src="{{ asset('js/bootstrap-datetimepicker.min.js') }}" charset="UTF-8"></script>
        <script type="text/javascript" src="{{ asset('js/locales/bootstrap-datetimepicker.uk.js') }}" charset="UTF-8"></script>


        <script type="text/javascript">
            $(".{{ $options['div_class'] }}").datetimepicker({
                format: "{{ $options['dt_format'] }}",
                showMeridian: true,
                autoclose: true,
                todayBtn: true,
                todayHighlight: true,
                minuteStep: 15,
                startDate:new Date()
            });
        </script>


        <?php endif; ?>



**app/Forms/Fields/DatetimeType.php**
        
              <?php  namespace App\Forms\Fields;
        /**
         * Created by IntelliJ IDEA.
         * User: mikhane
         * Date: 05-Feb-2015
         * Time: 4:22 PM
         */
        
        use Kris\LaravelFormBuilder\Fields\FormField;
        
        class DatetimeType extends FormField {
        
            protected function getTemplate()
            {
                // At first it tries to load config variable,
                // and if fails falls back to loading view
                // resources/views/fields/datetime.blade.php
                return 'fields.datetime';
            }
        
            public function render(array $options = [], $showLabel = true, $showField = true, $showError = true)
            {
                //$options['attr'] = [ 'readonly' => 'readonly'];
        
                return parent::render($options, $showLabel, $showField, $showError);
            }
        
        }

**config/laravel-form-builder.php**  
        .... 
        'custom_fields' => [
            'datetime' => 'App\Forms\Fields\DatetimeType'
        ]


**Usage in a Form: app/Forms/ArticleForm.php** 
I used text input type because chrome interferes with datetime type

           ->add('published_at', 'text', [
                'label' => "Publish On",
                'div_class' => 'form_datetime',
                'dt_format' => 'DD, dd MM yyyy - HH:iip',
                'attr' => [ 'readonly' => 'readonly']
            ])

**Comment by kristijanhusak** [comment]
First of all, this is a php package, which does not include any javascript in it, so if you want to create js datepicker, you need to do it yourself.

Second, your code have a huge bug in it. It will include all js (jquery, bootstrap timiepicker) each time you use this datepicker field.

Third, as i saw in the link you set, it's just enough to add class to the input and instantiate jquery plugin, so something like this:

```php
<?php
    ->add('published_at', 'text', [
	'attr' => [
	    'class' => 'datetimepicker', 
	    'data-format' => 'DD, dd MM yyyy - HH:iip'
	    'readonly' => 'readonly'
	]
    ]);
```

and include only **ONCE** your javascript in the page
```html
<!-- master.blade.php -->
...
<script type="text/javascript" src="{{ asset('js/jquery-1.8.3.min.js') }}" charset="UTF-8"></script>
<script type="text/javascript" src="{{ asset('js/bootstrap-datetimepicker.min.js') }}" charset="UTF-8"></script>
<script type="text/javascript" src="{{ asset('js/locales/bootstrap-datetimepicker.uk.js') }}" charset="UTF-8"></script>
<!-- YOUR SCRIPT -->
<script type="text/javascirpt" src="{{ asset('js/main.js') }}"></script>
</body>
</html>
```

And only instantiate datetimepicker in `js/main.js`
```js
$('.datetimepicker').each(function() {
    var $this = $(this);
    $this.datetimepicker({
	    format: $this.data('format'),
	    showMeridian: true,
	    autoclose: true,
	    todayBtn: true,
	    todayHighlight: true,
	    minuteStep: 15,
	    startDate:new Date()	    
    });	
});
```

No need to create custom views and all the stuff.

**Comment by imyque** [comment]
HI,

Thanks for the schooling. It was useful.

The reason I added the linked scripts to the  date picker view and not the
master template, is that I only want to load them when I use the date
picker. Secondly, I already have jQuery 2.1.3 on the master template that
does not work with the date picker. So a wanted to avoid potential
conflicts.

Cheers


Kind Regards,

Michael Ikhane
+234 803 481 0740
