### ISSUE TITLE
Assigning data to options in choice

### ISSUE THREAD

**Issue by DanielaSp** [kristijanhusak/laravel-form-builder#410]
Hey, is there any way I can set attributes like data to each single option in a choice?  I need each choice to have a data-category with the category of the product.
$this->add('products', 'select', [
            'choices' => [$products->pluck('name', 'id')->toArray()],
            'attr' => [
                'id' => 'search',
                'size' => 8,
                'multiple' => 'multiple',
                'name' => 'from[]',
            ],
          ])

**Comment by kristijanhusak** [comment]
Hi,

unfortunately not. Behind the scenes `Form::select` (https://laravelcollective.com/docs/5.2/html#drop-down-lists) is used, and it doesn't have such feature.

I would suggest you to create your custom view where you would generate the select options yourself and add whatever you need as attributes.

Or you can update frontend to not use the that data-category, but to rely on the option value or label.

**Comment by DanielaSp** [comment]
Ok got it, thank you!
