### ISSUE TITLE
Multiple form in one page (More errorBag)

### ISSUE THREAD

**Issue by Fellner96** [kristijanhusak/laravel-form-builder#413]
Hi.. My problem is, i have multiple form in one simple page. I override the redirectIfNotValid method 8. line from `$response = $response->withErrors($this->getErrors())->withInput();` to `$response = $response->withErrors($this->getErrors(), $bag)->withInput();`. It's working, put's the errors to the custom bag. But when the page is refresh with error bag the fields doesn't show any errors... :/

**Comment by kristijanhusak** [comment]
You could maybe structure your forms to be namespaced (have a name), so when you do anything, you can have everything in the same bag. I also think that would be easier to handle on the post action.

**Comment by Fellner96** [comment]
`protected function addErrorClass()
    {
        $errors = $this->parent->getRequest()->session()->get('errors');

        if ($errors && $errors->has($this->getNameKey())) {
            $errorClass = $this->formHelper->getConfig('defaults.wrapper_error_class');
            $wrapperClass = $this->getOption('wrapper.class');

            if ($this->getOption('wrapper') && !str_contains($wrapperClass, $errorClass)) {
                $wrapperClass .= ' ' . $errorClass;
                $this->setOption('wrapper.class', $wrapperClass);
            }
        }
    }`

This always use the default error bag!!! And i can't override it becouse every field type extends this one...

**Comment by Fellner96** [comment]
I will make a pull request, i think you dont understand my problem.

**Comment by fredbradley** [comment]
Sorry to common on an issue that's been closed for a year, but I could do with a little support. 

I've tried to use this technique, in my `ContactForm` I've added `$errorBag = 'contactForm'`, but when I view the error bags after a failed validation, it still says 'default'!?

**Comment by fredbradley** [comment]
Ignore me... fixed it - had something extra in our code that was complicating things.

**Comment by Fellner96** [comment]
Working perfect for me.

**Comment by tahafilali** [comment]
how can I handle this error ?
Thank you in advance !!
