### ISSUE TITLE
Custom validation rules

### ISSUE THREAD

**Issue by codeurfou** [kristijanhusak/laravel-form-builder#418]
Hello,

Thx for your great form builder !

When I make and try to use a Custom Rule, like https://laravel.com/docs/5.5/validation#custom-validation-rules , 
I set "new Uppercase" as rule for my form, then I get a "ErrorException (E_ERROR)
strpos() expects parameter 1 to be string, object given". (/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/RulesParser.php:566)

Doesn't your form build support custom validation rules  ?

Thx !

**Comment by kristijanhusak** [comment]
You can use closure for that situations:

```php
$this->add('name, 'text', [
  'rules' => [
    function($name) {
      return new Uppercase();
    }
  ]
]);
```

**Comment by codeurfou** [comment]
Thx a lot!

**Comment by mix359** [comment]
Excuse me if I reopen this issue, but I've a similar situation.
I'm trying to using a custom rule FiscalCode. so I've tried with the closure function like this:

$studentForm->add("fiscalCode", "text", ['label' => "Fiscal Code", 'rules' => ["required", function($text) { return new FiscalCode(); }]]);

But it return me an error from the strpos in "parseStringRule" of the RulesParser.
I'm doing something wrong?

I've checked the code, and it doesn't seam to check the type function/method for the rules in the parseRule, so it's all passed to parseStringRule, but probably I'm looking in the wrong area :)
I'm using the dev-master, so it's theoretically updated.

Thanks
Cheers
Mix

**Comment by Kharestani** [comment]
I have the same problem like @mix359 
```php
        $this->add('nationalcode', 'text', [
                'label' => 'some label here',
                'rules' => [
                    'required',
                    function($name) {
                        return new NationalID();
                    }
                ]
            ])
            ->add('address', 'textarea')
            ->add('submit', 'submit');
```

**Comment by kristijanhusak** [comment]
Can someone test this with the latest release? Thanks!

**Comment by SanderMuller** [comment]
@kristijanhusak Sorry, I just checked with the latest release and it's fixed, thanks!
