### ISSUE TITLE
Default Namespace / Prepend Form Class

### ISSUE THREAD

**Issue by Apeopex** [kristijanhusak/laravel-form-builder#42]
Similar to what the RouteServiceProvider does it would be nice to have a config option to provide a default namespace that gets prepended to the $formClass in FormBuilder::create.

In the config file you might have:
`'default_namespace' => 'App\Http\Forms'`

Then when initiating forms in controller methods you could have:
`$form = FormBuilder::create('PasswordResetRequest');`

Instead of:
`$form = FormBuilder::create('App\Http\Forms\PasswordResetRequest');`

**Comment by kristijanhusak** [comment]
Yes that would be great, but it's not possible to make Laravel change main namespace in my config file with `php artisan app:name`, so it will be confusing for usage. Would like to hear more thoughts about this from others.

Also, suggestion if you are using php 5.5, u can just import the class at the top and use
```php
<?php
use App\Http\Forms\PasswordResetRequest;

$form = FormBuilder::create(PasswordResetRequest::class);
```

**Comment by Apeopex** [comment]
If the config keeps the `default_namespace` option as blank by default, developers would continue using as is, with no confusion, by using the FQN of the form class. It could be considered more of a "power user" option for those who already understand it.

The PHP 5.5+ suggestion is something I didn't think of, thanks!

**Comment by kristijanhusak** [comment]
Yeah, i guess it will work out good that way. Will put it on the todo list, thanks :)

**Comment by kristijanhusak** [comment]
@Apeopex 
I added it, just do a composer update :)

More info in the docs here https://github.com/kristijanhusak/laravel-form-builder#changing-configuration-and-templates

**Comment by Apeopex** [comment]
Awesome!
