### ISSUE TITLE
Hydrating model

### ISSUE THREAD

**Issue by Grafikart** [kristijanhusak/laravel-form-builder#421]
I can do the PR but I want to know if it's interesting before :

## Idea

The form could hydrate model when specific methods are used (`isValid()` and `redirectIfNotValid()` for instance).

```php
$model = new Model();
$form = $this->getForm($model); // return a form
$form->redirectIfNotValid();
$model->save(); // The model would be filled with values from the form
```

## How ?

My first implementation is rather simple and doesn't handle nested form

```php
    public function hydrateModel()
    {
        $attributes = $this->getRequest()->only(array_keys($this->getFields()));
        $this->model->setRawAttributes($attributes);
    }
```

## Problems

It could cause problems if people doesn't want this behaviour so we could add an attribute in the form class, `$autohydrate` maybe ? Or having a new method `getHydratedModel()` ?

**Comment by kristijanhusak** [comment]
Method `getFieldValues()` exist on the form class, and it returns data also for nested forms.

We could add it to redirectIfNotValid with an optional flag as you suggested. I'm open for PRs.

**Comment by Grafikart** [comment]
@kristijanhusak Oh, didn't noticed this method (I'll do a PR for the documentation to add it)

What would you prefer 

- `getHydratedModel()`, returns a cloned model, with values inserted
- `hydrateModel()`, mutate the model
- implicit hydratation for the methodes with an additional parameter.

**Comment by kristijanhusak** [comment]
@Grafikart looks ok.

**Comment by Grafikart** [comment]
Closing this issue since I tried to implement it and it causes lots of problems with edge cases (UploadedFile being hydrated into models for instance)
