### ISSUE TITLE
Input group

### ISSUE THREAD

**Issue by sebastienjean76** [kristijanhusak/laravel-form-builder#425]
Hi,

Is there the possibility to add "Input group"?
Otherwise it might be a good idea to add this to laravel-form-builder :)

Sample Input group : https://getbootstrap.com/docs/4.1/components/input-group/

Thanks

**Comment by kristijanhusak** [comment]
This looks like a bootstrap 4 feature. We are still on bootstrap 3 here unfortunately.

You can use custom templates to achieve this if you really need it.

**Comment by sebastienjean76** [comment]
Thank you for your answer kristijanhusak but how can I do that?
Thanks

**Comment by kristijanhusak** [comment]
Provide the template for your field/form like in this example http://kristijanhusak.github.io/laravel-form-builder/custom/templates.html

Check the templates that are used by default here https://github.com/kristijanhusak/laravel-form-builder/tree/master/src/views and use any of those for your use case.

**Comment by sebastienjean76** [comment]
Okay I will try ;)
Thanks.

**Comment by kristijanhusak** [comment]
@ahu you are right, it exists also in v3, but i think i won't be adding support for it. Custom templates are always an option if you need them.
