### ISSUE TITLE
Value field in a view

### ISSUE THREAD

**Issue by seb-jean** [kristijanhusak/laravel-form-builder#426]
Hi,
I wanted to know how I get the value of a form field submitted in a view?
I tried
`$form->getField('name_field')->getValue()`
 but it does not work.  The value returned is the value of the field before the form is submitted.
Thank you for your help !

**Comment by FranArjona** [comment]
Just use the regular Laravel request, by injection for example, like:
```
public function store(Request $request,...)

$request->all();
```

**Comment by sebastienjean76** [comment]
No no in a view
