### ISSUE TITLE
Checkbox group

### ISSUE THREAD

**Issue by seb-jean** [kristijanhusak/laravel-form-builder#429]
Hi,

I would like to have a Field Checkbox with Grouping Label as in the photo below. How can I do ?
Group 1, Group 2 and Group 3 belong to the same field.

![vwlc4](https://user-images.githubusercontent.com/12116264/40107104-af696272-58f7-11e8-8355-0b044f511164.png)

Thanks :)

**Comment by kristijanhusak** [comment]
If all checkboxes go under the same name (for example `groups[]`), then you will have to render each field separately in view. If you want to split them by group (different name per group), you can use child forms.

**Comment by sebastienjean76** [comment]
Thank you for your answer but what do you mean to render each field separately in view ?
Thanks :)

**Comment by kristijanhusak** [comment]
In this case you cannot just do `form($form)` in a view, and get everything set up for you. 
You have to print fields manually, like explained in here http://kristijanhusak.github.io/laravel-form-builder/form/viewhelpers.html
