### ISSUE TITLE
Extend InputType

### ISSUE THREAD

**Issue by seb-jean** [kristijanhusak/laravel-form-builder#432]
Hi,
I would like extend Kris/LaravelFormBuilder/Fields/InputType.php without create a custom field.
How can I do ?
Thanks :)

**Comment by sebastienjean76** [comment]
I would like add option for input group.
With method : http://shyammakwana.me/php/laravel-override-vendor-classes.html , Do you think it's possible?

**Comment by kristijanhusak** [comment]
Can you elaborate what you exactly mean by input group?

**Comment by sebastienjean76** [comment]
Input group is bootstrap's component : https://getbootstrap.com/docs/4.1/components/input-group/

**Comment by kristijanhusak** [comment]
You can just use custom template for that, no need to change the class. http://kristijanhusak.github.io/laravel-form-builder/custom/templates.html
