### ISSUE TITLE
I get older Package version

### ISSUE THREAD

**Issue by GeoSot** [kristijanhusak/laravel-form-builder#436]
Hello and many thanks for this package. Is Great

As I was testing the package over bootstrap4 css, I couldn't make it work with the usage of _"
'field_error_class'   => '',"_  After some searching I found that my composer insists to download an older version of it.

my Laravel composer.json has  -->**"kris/laravel-form-builder": "^1.14",** but many files are not aligned with these of the repository. 

As example on my project/cendors/laravel-form-builder/src/Kris/LaravelFormBuilder/Fields/FormField.php line 529 the method **addErrorClass** is 
```
protected function addErrorClass()
    {
        $errors = $this->parent->getRequest()->session()->get('errors');

        if ($errors && $errors->has($this->getNameKey())) {
            $errorClass = $this->formHelper->getConfig('defaults.wrapper_error_class');
            $wrapperClass = $this->getOption('wrapper.class');

            if ($this->getOption('wrapper') && !str_contains($wrapperClass, $errorClass)) {
                $wrapperClass .= ' ' . $errorClass;
                $this->setOption('wrapper.class', $wrapperClass);
            }
        }
    }
```
and the [live version](https://github.com/kristijanhusak/laravel-form-builder/blob/48d970f369a5b8c6c83373f5d76e5d9b9b3d313c/src/Kris/LaravelFormBuilder/Fields/FormField.php#L531)  is much more different.

I have tried from different PCs , different networks, i have uncached composer, delete the package and reinstall it manually and by command line, but no change.

Am i doing something wrong?

**Comment by kristijanhusak** [comment]
Did you try dev-master?
There's probably some stuff on master that needs to be tagged.

**Comment by kristijanhusak** [comment]
@GeoSot I released new version, so you can update and have everything working. If it still happens, reopen this issue.
