### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mastommel** [kristijanhusak/laravel-form-builder#439]
Hey @kristijanhusak,

thanks for your work with this package! I am in need of a bugfix existing in the master branch. Could you please create a new release tag? A version containing at least the fix in e131530d90047337acce827e63b1080e8d2ff67b would be great for me.

Thanks a lot!

**Comment by kristijanhusak** [comment]
hey @mastommel , i just released version 1.15.0.

**Comment by mastommel** [comment]
Thank you!
