### ISSUE TITLE
How to stop form builder from generating labels with fields?

### ISSUE THREAD

**Issue by ahsanshabir** [kristijanhusak/laravel-form-builder#44]
Hello Kristi,

Thanks for this great package. I wanted to know if there is any way to not let the form builder create a label with every field? 

thanks

**Comment by kristijanhusak** [comment]
Hi Ahsanshabir,

Do you need that functionality for every field in the form or only for some?

**Comment by kristijanhusak** [comment]
@ahsanshabir 
You can totally disable label for a field by setting `label` option to `false`. Check [here](https://github.com/kristijanhusak/laravel-form-builder#field-customization), gender field.
