### ISSUE TITLE
Error in composer update version 1.15

### ISSUE THREAD

**Issue by LuizHenriqueBK** [kristijanhusak/laravel-form-builder#441]
Error
/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Console/FormMakeCommand.php on line 150
In FormMakeCommand.php line 150: syntax error, unexpected '?'
![image](https://user-images.githubusercontent.com/30929047/42482929-ee29a438-83c0-11e8-8840-2ca363767a4e.png)

**Comment by imTigger** [comment]
`??` (Null coalescing operator) syntax requires PHP 7.0
Maybe we should use the old syntax or bump the requirement to 7.0?

**Comment by kristijanhusak** [comment]
I released new version with the fix.
