### ISSUE TITLE
Accessing $this->getModel() in Form class do not always return model provided

### ISSUE THREAD

**Issue by imTigger** [kristijanhusak/laravel-form-builder#442]
Problem: Accessing `$this->getModel()` in Form class do not always return model provided

Affected Version: 1.15.0 (1.14.0 not affected)

Excepted Behavior: `$this->getModel()` always return Model provided
Actual Behavior: `$this->getModel()` sometimes returns input array, when `$form->isValid()` is called

This behavior seems introduced by 43346b2d9a40b0c98947691fae19137c70f96b6d and affecting version 1.15.0

How to reproduce:
1. Create a Controller that provide model to form builder

```
<?php

namespace App\Http\Controllers;

use App;

use App\Models\User;
use Kris\LaravelFormBuilder\FormBuilderTrait;
use Illuminate\Routing\Controller as BaseController;

class DebugController extends BaseController
{
    use FormBuilderTrait;

    public function handle() {
        $form = $this->form(App\Forms\UserForm::class, [
            'model' => User::whereId(1)->first()
        ]);

        $form->isValid();
    }
}

```

2. Create a Form that use `$this->getModel()`

```
<?php

namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class UserForm extends Form
{
    public function buildForm()
    {
        $method = $this->getMethod();
        $entity = $this->getModel();

        $this->add('username', 'text', [
            'label' => 'Username',
            'rules' => ['required', 'max:255', in_array($method, ['get', 'post']) ? 'unique:users' : "unique:users,username,{$entity->id}"]
        ]);
    }
}
```

3. Whoops! 
```
ErrorException (E_NOTICE)
Trying to get property 'id' of non-object
```
Because `$entity` is not an object, `$entity->id` cause error

**Comment by philhq** [comment]
I think this commit is what causing your issue:

https://github.com/kristijanhusak/laravel-form-builder/commit/43346b2d9a40b0c98947691fae19137c70f96b6d

**Comment by imTigger** [comment]
Yes, I also found out that was the cause.
But I don't quite understand the use-case of that commit. 
Can't submit PR to fix that. :/

**Comment by kristijanhusak** [comment]
I fixed it in new release. I wasn't able to find an issue where it was reported, so i removed it.
