### ISSUE TITLE
Filters not working for child form?

### ISSUE THREAD

**Issue by ryanscherler** [kristijanhusak/laravel-form-builder#448]
After a bit of testing it seems that a child forms' filters are not getting applied. Only the parent form seems to be returning filtered input (checking values via this method `$form->getFieldValues()` and also inspecting `$request->all()`. And thoughts on what I may be missing when trying to retrieve a child forms' filtered data?

**Comment by ryanscherler** [comment]
After looking into this a bit more - it seems the error isn’t with the child form - but rather that filters are not working with array response input (which is how child forms render their name / values).

**Comment by kristijanhusak** [comment]
I'll look into it, thanks.

**Comment by rudiedirkx** [comment]
Fields added like

	$this->add('lang[one]', 'select', [

also don't work with filters. I'll attempt a fix.
