### ISSUE TITLE
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by philippelamny** [kristijanhusak/laravel-form-builder#449]
We have a specific session driver and when we try to add this package, we have this below error.

In the boot method of the FormBuilderServiceProvider class, when you call "$form = $this->app['form'];",
the system makes an error because our specific session driver is not boot before.

**************** COMMAND LOG  composer update ************
@commandLog: composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing kris/laravel-form-builder (1.15.1): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Manager.php line 99:

  Driver [app_database] not supported.

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by kristijanhusak** [comment]
What session driver are you using? Is it some custom, or Laravel supports it by default?

**Comment by Splashdown** [comment]
Hum I think it is a custom session driver.
I got the same issue, to solve this, just add this to your composer.json 

` "extra": {
        "laravel": {
            "dont-discover": [
                "kris/laravel-form-builder"
            ]
        }
    },` 

and add the reference of the provider 
Kris\LaravelFormBuilder\FormBuilderServiceProvider::class
 at the end of the providers arrays in your app.php

**Comment by philippelamny** [comment]
Thank you Kris for your support and your awsome package!

Thank you Splashdown! It works!!

**Comment by kristijanhusak** [comment]
@Splashdown Thanks!

**Comment by pablovt86** [comment]
tengo este problema ayuda !!!!!
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException  : Please provide a valid cache path.

  at C:\Users\pablo vaccotti\Desktop\redSocial\vendor\laravel\framework\src\Illuminate\View\Compilers\Compiler.php:36
    32|      */
    33|     public function __construct(Filesystem $files, $cachePath)
    34|     {
    35|         if (! $cachePath) {
  > 36|             throw new InvalidArgumentException('Please provide a valid cache path.');
    37|         }
    38|
    39|         $this->files = $files;
    40|         $this->cachePath = $cachePath;

  Exception trace:

  1   Illuminate\View\Compilers\Compiler::__construct(Object(Illuminate\Filesystem\Filesystem))
      C:\Users\pablo vaccotti\Desktop\redSocial\vendor\laravel\framework\src\Illuminate\View\ViewServiceProvider.php:141

  2   Illuminate\View\ViewServiceProvider::Illuminate\View\{closure}(Object(Illuminate\Foundation\Application), [])
      C:\Users\pablo vaccotti\Desktop\redSocial\vendor\laravel\framework\src\Illuminate\Container\Container.php:799

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by rudiedirkx** [comment]
Seems like your config is missing a cache path? Or it doesn't exist, or it's not readable/writable. Only you can debug that.
