### ISSUE TITLE
[Laravel 5.0.6] Dynamic add fields

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#46]
I have problem with add field in controller

When I try add fields
```
$form = \FormBuilder::plain(
            ['method'=>'post','url'=>url(\Config::get('app.locale').'/backend/translates/save-translate')])
->add('foo','text',['label'=>'foo','wrapper'=>['class'=>'large-4']]);        
```

but

```
$form = \FormBuilder::plain(
            ['method'=>'post','url'=>url(\Config::get('app.locale').'/backend/translates/save-translate')])
        ;




        if($existTranslates->count()>0){
            foreach($existTranslates->get() as $row){
                $form->add($row->key,'text',['label'=>$row->key,'wrapper'=>['class'=>'large-4']]);
            }
        }

```
result is empty page.

BTW,
I can add data by plain or addData method. Fileds are empty after rendering.
example
```
$form = \FormBuilder::plain(
            ['method'=>'post','url'=>url(\Config::get('app.locale').'/backend/translates/save-translate')],['foo'=>'bar'])
->add('foo','text',['label'=>'foo','wrapper'=>['class'=>'large-4']]);        

```

is empty, same 

```
$form = \FormBuilder::plain(
            ['method'=>'post','url'=>url(\Config::get('app.locale').'/backend/translates/save-translate')])
->add('foo','text',['label'=>'foo','wrapper'=>['class'=>'large-4']])->addData(['foo'=>'bar']);        

```

**Comment by kristijanhusak** [comment]
What you mean `result is empty page`? Do you get any error?

What is returned by `$existTranslates` ?

Also, `addData` does not bind values to the fields, it just passes the data to the form class so you can use it inside like this:
```php
<?php 
class TestForm extends Form {
    public function buildForm()
    {
        $this->add('name', 'text', [
            'default_value' => $this->getData('foo') // 'bar'
       ]);
    }
}

**Comment by jaroslawziolkowski** [comment]
```
$existTranslates;
``` 

```
$row->key; // eg bar
```
is Eloquent ORM object with data (8 records)
I mean that 
```
form($form) 
```
in view.
result is empty without errors.

What method should I use to bind data in controller?

**Comment by kristijanhusak** [comment]
I'm really not sure why you get no errors, try debugging.

I just updated to version `1.3` which allows [Collection](https://github.com/kristijanhusak/laravel-form-builder#collection) type. I would suggest using that.

If you want to stick with your solution, you can bind data this way:
```php
<?php
<?php
if ($existTranslates->count()>0) {
    foreach($existTranslates->get() as $row) {
        $form->add($row->key, 'text', [
            'label'=>$row->key,
            'default_value' => $row->value // Not sure what is value on the $row
            'wrapper'=>['class'=>'large-4']
        ]);
    }
}
```

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
Thanks for update.
I updated to 1.3.

It works fine. But my problem was not in version. In my array was duplicate value for "name" attribute.

BTW, How can I debug similar situation? Because FormBuilder not throw warning, only not show form.

**Comment by kristijanhusak** [comment]
Well, maybe try dumping complete form in the view with `dd($form)` and see what happens.
It should throw [this exception](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Form.php#L500) when you try to add field with same name. Really strange it didn't throw it. I'll test it and let you know.

**Comment by kristijanhusak** [comment]
I tested it, and i get the exception that should occur as i wrote above.
I added additional checks to the latest version, do a composer update. If it does not update anything, just clear cache like this : `rm -rf ~/.composer/cache/kris`, remove vendors folder and do a composer update. Hope this helps.

**Comment by jaroslawziolkowski** [comment]
Ok I see this errors. Thank you for help.

**Comment by kristijanhusak** [comment]
No problem :)
