### ISSUE TITLE
Is there conditional logic?

### ISSUE THREAD

**Issue by KPOCT** [kristijanhusak/laravel-form-builder#461]
Is it possible to show/hide/enable/disable _some_field_1_ if _some_condition_ of _some_field_2_ is true/false?

**Comment by kristijanhusak** [comment]
You could do something like this, if that's what you mean:

```php
<?php

class MyForm extends Form {
	public function buildForm() {
		$this->add('name', 'text');

		if ($this->getModel()->showAddress) {
			$this->add('address', 'text');
		}
	}
}
```

**Comment by KPOCT** [comment]
Thanks for your reply.
I meant something like conditional logic in WordPress ACF.
But I think I'm a bit wrong because goals of ACF and laravel-form-builder is really different.
