### ISSUE TITLE
Access to data inside the form of a collection field

### ISSUE THREAD

**Issue by robinvalk** [kristijanhusak/laravel-form-builder#465]
Hi,

I'm struggling to get the relation's data inside the form of a collection field. I would like to set the label with the group name and per characteristic (the sub relation) define some dynamic field values in the subForm of the subForm. Hope that makes sence 😂 

Setting the label I managed to do via a custom template. That's the weird part of it imo, in the view I do have access to the data.

Field decleration:
```php
$this->add('characteristicGroups', 'collection', [
    'type' => 'form',
    'label_show' => false,
    'data' => $characteristicsGroupedByGroupName->map(function ($characteristics, $groupName) {
        return [
            'name' => $groupName,
            'characteristics' => $characteristics
        ];
    }),
    'options' => [
        'label' => false,
        'class' => CharacteristicGroupForm::class,
        'template' => 'admin.form-templates.book.characteristic-group',
    ],
])
```

When I `dd($this->getData());` inside the `CharacteristicGroupForm` class I get an empty array. The `$this->getModel()` method returns the "root" model. And in the `$this->getOptions()` there is unfortunatelly nothing to be found regarding the data.

Subform class:
```php
<?php

namespace App\Forms\Book;

use Kris\LaravelFormBuilder\Form;

class CharacteristicGroupForm extends Form
{
    public function buildForm()
    {
        dd($this->getData(), $this->getModel());

        $this->add('characteristics', 'collection', [
            'type' => 'form',
            'label_show' => false,
            'data' => $this->getData('characteristics'),
            'options' => [
                'class' => CharacteristicForm::class,
                'label' => false,
            ],
        ]);
    }
}
```

I can't seem to find anything regarding this in the docs. Is this a bug or am I missing something essential?

**Comment by kristijanhusak** [comment]
What's your data structure?

You shouldn't do any manual mapping of data if you structure is correct. Just passing in the model should do the trick.

For this case it looks like you need to have array of arrays, because you nest one collection into the other.

**Comment by robinvalk** [comment]
I do have the form working. But I still want to access that data inside the subforms, which doesn't seem to work.

Using the data I can choose the correct field type(s) for the entry. I basically have a key value structure where certain fields should have something like a select of checkbox field instead of a standard text field.
