### ISSUE TITLE
[Laravel 5][version 1.3] Wrapper not work when label is false

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#48]
When you add

```
\FormBuilder::plain()->add('foo','text',['wrapper'=>['class'=>'bar']]);
```
all works fine,
but after change to:
```
\FormBuilder::plain()->add('foo','text',['wrapper'=>['class'=>'bar'],'label'=>false]);
```
wrapper is not render.

Of course, it's possible to fix by set nbsp for label. But then label still exist.

**Comment by kristijanhusak** [comment]
Yes, you are right. I fixed it, do a composer update.

Just notice that i updated most od the view files, so if you published and created custom check last commit.
