### ISSUE TITLE
Q: Form with eloquent Model - Changes filled?

### ISSUE THREAD

**Issue by nea** [kristijanhusak/laravel-form-builder#482]
Hi there

I am creating a form 
`$form = $this->form(...`
and am attaching a model with
`'model'  => $user`
The data from the model is shown and all is good.

But after a submit, how do I update the model? Is it updated automatically? Do I have to do something like: `$user->fill($form->getFieldValues());`

This is the only thing I wasn't able to find in the docs or on Google. Sorry about that ^^'

Thanks a lot in advance

**Comment by kristijanhusak** [comment]
Hi,

You have to manually update the model. You can get values from form with `$form->getFieldValues()`.

**Comment by nea** [comment]
Ok, thought the same. Thanks for the clarification.
