### ISSUE TITLE
Cannot display html as button label anymore

### ISSUE THREAD

**Issue by waiylgeek** [kristijanhusak/laravel-form-builder#487]
Hello,

I have run composer update earlier and I suddenly discovered that the package is no longer supporting HTML as button labels.

![screen shot 2019-02-16 at 9 42 44 pm](https://user-images.githubusercontent.com/4692358/52905006-776b1600-322b-11e9-9bc3-9cf9a4ef1769.png)

How can I please avoid that from happening? I cannot just update all the buttons in my web app.

Thank you so much!

**Comment by kristijanhusak** [comment]
What field type are you using for a button?

**Comment by waiylgeek** [comment]
Submit:

`$this->add('submit', 'submit');`

**Comment by kristijanhusak** [comment]
How did you set it, as value?

**Comment by waiylgeek** [comment]
Here's a screenshot

<img width="753" alt="screen shot 2019-02-21 at 12 41 00 am" src="https://user-images.githubusercontent.com/4692358/53132856-0a2bed80-3569-11e9-9af9-05cfb2e746ee.png">

**Comment by rudiedirkx** [comment]
@waiylgeek Did you override `button.php`? Our dist `button.php` calls `Form::button()` with the unescaped/unencoded label, so it should be fine. What's in your `button.php` and `Form::button()`?

**Comment by waiylgeek** [comment]
@rudiedirkx I did not change the `button.php` file. Here it is:

<img width="1054" alt="Screen Shot 2019-03-30 at 4 15 14 AM" src="https://user-images.githubusercontent.com/4692358/55270712-85886980-52a2-11e9-8736-7ecc0779ec75.png">

**Comment by rudiedirkx** [comment]
I can't debug your project from here, so I can't find the reason. HTML in the label should work.

You'll have to debug it yourself. I'd start with a `dump($value)` in laravelcollective/html's `FormBuilder::button()` (called through `Form::button()` in the php view). `$value` is the button label.

**Comment by mikeerickson** [comment]
@waiylgeek if you want to try and create a reproducible demo using a bare laravel project, please do so and post link to repo.  Hard to debug blind as @rudiedirkx mentioned above

**Comment by mikeerickson** [comment]
We have a better chance of helping if we can see a reproducible example, especially with the delays between responses.

**Comment by waiylgeek** [comment]
After testing on a fresh new project the issue seems to disappear. I think I have another package installed that interferes. Thanks for the help.
