### ISSUE TITLE
[Laravel 5 ][version1.3.1] Can't populate fields from other different class/array

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#49]
@kristijanhusak 
I have class with fields:

When I'd like fill fields from eloquent model, it's no problem. User model and all works.

But, when I want bind values to fields in controller from other source, it big problem.

Not work:
use stdClass as model property
use array as model property
use array [field_name=>value] in third create function argument.

examples:
newTranslate form
```
public function buildForm()
    {
        $this
            ->add('section', 'hidden')
            ->add('submit', 'submit',['attr'=>['class'=>'tiny secondary'],'label'=>trans('translate.add_new_translate')]);
    }
```
controller code
```
$model = new stdClass();
$model->section = 'bar';
$newForm = \FormBuilder::create('App\Forms\Backend\NewTranslate',[
            'method'=>'post',
            'url'=>url(\Config::get('app.locale').'/backend/translates/create'),
'model'=>$model // not work

        ]);
```

```

$model = ['section'=>'bar'];

$newForm = \FormBuilder::create('App\Forms\Backend\NewTranslate',[
            'method'=>'post',
            'url'=>url(\Config::get('app.locale').'/backend/translates/create'),
'model'=>$model // not work

        ]);
```
and

```

$model = ['section'=>'bar'];

$newForm = \FormBuilder::create('App\Forms\Backend\NewTranslate',[
            'method'=>'post',
            'url'=>url(\Config::get('app.locale').'/backend/translates/create'),


        ],$model); // also not work
```
In every case value is empty.

How can I resolve this problem. Because, add to every form function to fill default value it make no sense.

Perfect solution will be, possible use array/stdClass as model or accept array from third argument in FormBuilder::create function

-----------------------------
EDIT:
Of course I can use on FormBuilder class:
->getField('section')->setOptions(['default_value'=>'bar');

but for many fields it's not comfortable.

**Comment by kristijanhusak** [comment]
Do you get an Exception or just an empty form?

**Comment by jaroslawziolkowski** [comment]
I see exception if I use stdClass as model
```
Undefined property: stdClass::$exists
```
and this is show on line 2 in my view (it's not form() call)

when I use array as model
```
Trying to get property of non-object 
```
when I use array as third create parameter of course without error. Show form but with empty value

**Comment by kristijanhusak** [comment]
I fixed it. Do `composer update`.

Third parameter is used just to pass data to the form class, and then use it inside with `$this->getData($key)`. It does not use those values for form value binding.

Thanks for reporting.

**Comment by jaroslawziolkowski** [comment]
I did update.
But still I don't understand what should I use to bind data in controller.

**Comment by kristijanhusak** [comment]
You should be able to use anything you tried, stdClass, Array, Laravel Collection or Eloquent model.

**Comment by jaroslawziolkowski** [comment]
I have same problem after update. 
Below is sample of my code (with debug). My library version is 1.3.2

```
<?php namespace App\Forms\Backend;

use Kris\LaravelFormBuilder\Form;

class NewTranslate extends Form
{
    public function buildForm()
    {
        $this
            ->add('section', 'hidden')
            ->add('submit', 'submit',['attr'=>['class'=>'tiny secondary'],'label'=>trans('translate.add_new_translate')]);
    }
}
```
In Controller
```
$newForm = \FormBuilder::create('App\Forms\Backend\NewTranslate',[
            'method'=>'post',
            'url'=>url(\Config::get('app.locale').'/backend/translates/create'),
            'model'=>['section'=>'ddd'],

        ]);
dd($newForm->renderForm());
```
result
```
ErrorException in form.php line 2: Trying to get property of non-object
```

or in controller:

```
        $model = new \StdClass();
        $model->section = 'ddd';

        $newForm = \FormBuilder::create('App\Forms\Backend\NewTranslate',[
            'method'=>'post',
            'url'=>url(\Config::get('app.locale').'/backend/translates/create'),
            'model'=>$model,

        ]);
        dd($newForm->renderForm());
```
result
```
ErrorException in form.php line 2: Undefined property: stdClass::$exists
```

without "rnderForm" and use view I see same error, but in view file on line 2.

**Comment by kristijanhusak** [comment]
Did you publish the views before? In the 1.3.2 i updated the form.php view to skip checking `$model->exists`. If you did publish, then just go into your published `form.php` and remove that part.

**Comment by jaroslawziolkowski** [comment]
Yes I did. Published views to my application vendor.... I have 1.3.2 version.
I removed dd and tried on view.

```
$model = new \StdClass();
        $model->section = 'ddd';

        $newForm = \FormBuilder::create('App\Forms\Backend\NewTranslate',[
            'method'=>'post',
            'url'=>url(\Config::get('app.locale').'/backend/translates/create'),
            'model'=>$model,

        ]);
```
in view

```
{!! form($newForm !!}
```
```
ErrorException in form.php line 2: Undefined property: stdClass::$exists (View: /var.../resources/views/.../translate.blade.php)
```

**Comment by kristijanhusak** [comment]
If you are not changing anything in those views there is no need to publish them, it will use default from vendor package.

Glad I helped :-)
