### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire() in Laravel 5.8

### ISSUE THREAD

**Issue by nekromoff** [kristijanhusak/laravel-form-builder#492]
issue with the latest compatibility

**Comment by kristijanhusak** [comment]
I can't find changelog for this. Why it is undefined?

**Comment by nekromoff** [comment]
https://laravel.com/docs/5.8/upgrade

deprecated and removed

Events The fire Method

*Likelihood Of Impact: Low*

The fire method (which was deprecated in Laravel 5.4) of the Illuminate/
Events/Dispatcher class has been removed
<https://github.com/laravel/framework/pull/26392>. You should use the
dispatch method instead.

**Comment by kristijanhusak** [comment]
I released new version where this is fixed.

**Comment by viktormaar** [comment]
The fix is not compatible anymore with Laravel 5.2, altough the composer will install this version:
`Call to undefined method Illuminate\Events\Dispatcher::dispatch()`

**Comment by mikeerickson** [comment]
@viktormaar @kristijanhusak Moving forward, we are going to have to drop backwards compatability at some level.  Seeing as 5.2 is quite old at this point, I am thinking that we tag the the 1.16 version to support older versions (those prior to 5.8).  Moving forward, 1.20 (and now working on 1.30) we are going to support 5.8 and beyond.

**Comment by mikeerickson** [comment]
Further, since Laravel 5.5 is the current LTS, I think it would behove us to move forward with only support LTS versions (we do have tagged versions to support older Laravel)  

https://laravel-news.com/category/laravel-5.5

**Comment by latifasaee** [comment]
I have the same problem after updating to Laravel from 5.7 to 5.8. This error pops up  when I want to deploy my app on forge. How to fix this error? please help!

```
In LaratrustHasEvents.php line 46:
                                                                 
  Call to undefined method Illuminate\Events\Dispatcher::fire() 
```

**Comment by mikeerickson** [comment]
@latifasaee 

> I have the same problem after updating to Laravel from 5.7 to 5.8. This error pops up when I want to deploy my app on forge. How to fix this error? please help!
> 
> ```
> In LaratrustHasEvents.php line 46:
>                                                                  
>   Call to undefined method Illuminate\Events\Dispatcher::fire() 
> ```

We dont have a file with name you supplied 

```
In LaratrustHasEvents.php line 46:
```

**Comment by mikeerickson** [comment]
@latifasaee In short, when you see an error like this with Laravel 5.8, the call

```
Call to undefined method Illuminate\Events\Dispatcher::fire() 
```

needs to be changed to

```
Call to undefined method Illuminate\Events\Dispatcher::dispatch() 
```

In versions prior to Laravel 5.7, this method classname was `fire` but with Laravel 5.8, it is now `dispatch`

**Comment by Tdemos** [comment]
@latifasaee thanks guy, you helped me a lot!

**Comment by GePapp** [comment]
Laravel 5.8 & Laratrust if you get an error:
Call to undefined method Illuminate\Events\Dispatcher
::fire()
In versions prior to Laravel 5.7, this method class name was fire but with Laravel 5.8, it is now dispatch.

Replace fire with dispatch in \Your Project\vendor\santigarcor\laratrust\src\Traits\LaratrustHasEvents.php
from
protected function fireLaratrustEvent($event, array $payload)
    {
        if (! isset(static::$dispatcher)) {
            return true;
        }

        return static::$dispatcher->fire(
            "laratrust.{$event}: ".static::class,
            $payload
        );
    }
to
protected function fireLaratrustEvent($event, array $payload)
    {
        if (! isset(static::$dispatcher)) {
            return true;
        }

        return static::$dispatcher->dispatch(
            "laratrust.{$event}: ".static::class,
            $payload
        );
    }

**Comment by rosnaib11** [comment]
I'm using /oauth/token from passport API and I also got this error after I upgrade from 5.6. The /oauth/token calling the `Illuminate\Events\Dispatcher::fire()` by default how can I replace it?

**Comment by sonywibisono** [comment]
You have to upgrade your passport to newest version, i.e ^7.0 on your composer.json

**Comment by qqlixiangabc** [comment]
'In versions prior to Laravel 5.7, this method classname was fire but with Laravel 5.8, it is now dispatch....',Thanks a lot.

**Comment by abuoop** [comment]
how could I find this file Module.php inside my project : 

In Module.php line 267:

  Call to undefined method Illuminate\Events\Dispatcher::fire()

**Comment by qhhc** [comment]
> how could I find this file Module.php inside my project :
> 
> In Module.php line 267:
> 
> Call to undefined method Illuminate\Events\Dispatcher::fire()


Modify IlluminateEventsDispatcher::fire() to IlluminateEvents\Dispatcher::dispatch() and try it. It should be possible.

**Comment by arabhossain** [comment]
I've been facing the same problem, this way I solved the issue 
File: vendor/laravel/passport/src/Bridge/RefreshTokenRepository.php
From the persistNewRefreshToken function
    /**
     * {@inheritdoc}
     */
    public function persistNewRefreshToken(RefreshTokenEntityInterface $refreshTokenEntity)
    {

        $this->database->table('oauth_refresh_tokens')->insert([
            'id' => $id = $refreshTokenEntity->getIdentifier(),
            'access_token_id' => $accessTokenId = $refreshTokenEntity->getAccessToken()->getIdentifier(),
            'revoked' => false,
            'expires_at' => $refreshTokenEntity->getExpiryDateTime(),
        ]);

        **$this->events->fire(new RefreshTokenCreated($id, $accessTokenId));**
    }

To
    /**
     * {@inheritdoc}
     */
    public function persistNewRefreshToken(RefreshTokenEntityInterface $refreshTokenEntity)
    {

        $this->database->table('oauth_refresh_tokens')->insert([
            'id' => $id = $refreshTokenEntity->getIdentifier(),
            'access_token_id' => $accessTokenId = $refreshTokenEntity->getAccessToken()->getIdentifier(),
            'revoked' => false,
            'expires_at' => $refreshTokenEntity->getExpiryDateTime(),
        ]);

        **$this->events->dispatch(new RefreshTokenCreated($id, $accessTokenId));**
    }

**Comment by kosta006** [comment]
> 
> 
> how could I find this file Module.php inside my project :
> 
> In Module.php line 267:
> 
> Call to undefined method Illuminate\Events\Dispatcher::fire()

I also cant find this file. Do i have to change vendor files perhaps?

**Comment by latifasaee** [comment]
@kosta006 you can't change vendor file. Maybe you are using some other packages in your project. Try to update them to support Laravel 5.8.

**Comment by arabhossain** [comment]
Laravel passport repo should have this file ("laravel/framework": "^5.8.0"). 
I'm using phpstorm, so maybe this could be a reason I can edit them.

**Comment by arabhossain** [comment]
> > how could I find this file Module.php inside my project :
> > In Module.php line 267:
> > Call to undefined method Illuminate\Events\Dispatcher::fire()
> 
> I also cant find this file. Do i have to change vendor files perhaps?

Maybe you can give it a try with searching **$this->events->fire(** to all over the project, hopefully you would get this.

>

**Comment by mohaimenkhalid** [comment]
> I've been facing the same problem, this way I solved the issue
> File: vendor/laravel/passport/src/Bridge/RefreshTokenRepository.php
> From the persistNewRefreshToken function
> /**
> * {@inheritdoc}
> */
> public function persistNewRefreshToken(RefreshTokenEntityInterface $refreshTokenEntity)
> {
> 
> ```
>     $this->database->table('oauth_refresh_tokens')->insert([
>         'id' => $id = $refreshTokenEntity->getIdentifier(),
>         'access_token_id' => $accessTokenId = $refreshTokenEntity->getAccessToken()->getIdentifier(),
>         'revoked' => false,
>         'expires_at' => $refreshTokenEntity->getExpiryDateTime(),
>     ]);
> 
>     $this->events->fire(new RefreshTokenCreated($id, $accessTokenId));
> }
> ```
> 
> To
> /**
> * {@inheritdoc}
> */
> public function persistNewRefreshToken(RefreshTokenEntityInterface $refreshTokenEntity)
> {
> 
> ```
>     $this->database->table('oauth_refresh_tokens')->insert([
>         'id' => $id = $refreshTokenEntity->getIdentifier(),
>         'access_token_id' => $accessTokenId = $refreshTokenEntity->getAccessToken()->getIdentifier(),
>         'revoked' => false,
>         'expires_at' => $refreshTokenEntity->getExpiryDateTime(),
>     ]);
> 
>     $this->events->dispatch(new RefreshTokenCreated($id, $accessTokenId));
> }
> ```

It Works .. thanks bro
