### ISSUE TITLE
Access the choice with getField function

### ISSUE THREAD

**Issue by bm2ilabs** [kristijanhusak/laravel-form-builder#506]
Hello , Thank you sooo much for this package its a time saver , i have a case where the choices has different style , like selecting plan in the hosting . i wonder if there is a possibility if you can  access the option using the getField function like when you do 

```php
$form->getField('choice.child1')
```

**Comment by kristijanhusak** [comment]
You should be able to do something like this:

```php
$form->getField('choice')->getChildren(0);
```

Choice field has array of fields as children, so you can access it by index.

**Comment by bm2ilabs** [comment]
Thank you for fast response , i use getChild as well , But my case is somewhat unique , i need to access the field by its value , so for example if i have a free plan i want to get the radio corresponding the option and put it inside a div with a style i endup using this little helper i just created .

```php
function getChildField(ChoiceType $choice, $value) {
    $fields = $choice->getChildren();
    foreach ($fields as $field) {
        if($field->getOption('value') == $value) {
            return $field;
        }
    }

    return false;
}
```

**Comment by kristijanhusak** [comment]
Yeah that's the best way to do it. There's no easier way as far as i know.

**Comment by bm2ilabs** [comment]
Thank you.
