### ISSUE TITLE
[Question] how to access the errors messages

### ISSUE THREAD

**Issue by bm2ilabs** [kristijanhusak/laravel-form-builder#508]
Hello . I was wondering if there is a possibility to get all errors messages from the form builder, something like 

```php
$form->getValidationErrorsMessages();
```

**Comment by kristijanhusak** [comment]
You can access MessageBag through validator:

```php
$form->getValidator()->getMessageBag()
```
From there it should be straightforward.

**Comment by bm2ilabs** [comment]
Thank you
