### ISSUE TITLE
Disabled field then get null value

### ISSUE THREAD

**Issue by romainSaya** [kristijanhusak/laravel-form-builder#509]
Hello,

If i **disable** a field in a form, when i get the value via getFieldValues(), i get **null value** for this disabled field. 
I should get the real value or the field should not be returned. 

In form :
```
$this->alert_manager->setOptions(['attr' => ['disabled' => 'disabled']]);
```
In controller :
```
$form = $this->getForm($model);
$form->redirectIfNotValid();
dd($form->getFieldValues());
```

result : 
```
array:3 [▼
  "alert_manager" => null
  "type" => "evalpro"
  "send_alert_before" => "3"
]
```

did i do something wrong ?

Thanks

**Comment by rudiedirkx** [comment]
Disabled form elements don't send a value. That's how browsers work. If the browser doesn't send a value, the form builder can't return it. `getFieldValues(false)` won't return the confusing `null`.

Note: disabling a field in HTML, won't make it unsubmittable. The user can cheat and send the value anyway, and `getFieldValues()` will return it. If you want an unsubmittable form field just for display, use the 'static' type.

**Comment by romainSaya** [comment]
Thanks, i'm going to explore that : getFieldValues($with_null = false)

**Comment by rudiedirkx** [comment]
For security (if that's why it's `disabled`), you want to use `'static'`. Never trust user input. The form builder can help you with that.
