### ISSUE TITLE
GetValidator function always return null

### ISSUE THREAD

**Issue by bm2ilabs** [kristijanhusak/laravel-form-builder#510]
Hello , i am getting this weird issue related to getValidator object , it's always return null.

the Form class has rules and i am able to get the getRules . but i try 

```php
$form->getValidator();
```
it return null

```php
 $form = $this->form($this->formBuilder, [
            'method' => 'POST',
            'id' => 'form',
            'route' => 'admin.crud.store'
        ]);

dd($form->getValidator());
```

**Comment by kristijanhusak** [comment]
You need to call `$form->validate()` first to do the validation and initialize the validator. It's not created on initialization.

**Comment by bm2ilabs** [comment]
Oh i didn't notice this is mention in the documentation , Thank you for the response
