### ISSUE TITLE
Collection of more than 10 subforms badly supported

### ISSUE THREAD

**Issue by ELtd** [kristijanhusak/laravel-form-builder#511]
Hi,

Subforms containing more than 10 elements are badly supported because of this regex.

https://github.com/kristijanhusak/laravel-form-builder/blob/5a3a1c539cdd0e1a534882b46ea4c1d47ae4f4b2/src/Kris/LaravelFormBuilder/Form.php#L1056

To fix, replace \d by \d+.

Thanks

**Comment by rudiedirkx** [comment]
Good catch! Good debugging too =)

Fixed.
