### ISSUE TITLE
Can not add scr attr to static field

### ISSUE THREAD

**Issue by Mpreyzner** [kristijanhusak/laravel-form-builder#516]
Use case: I have a form with image field and because of image field restrictions data can't be loaded there, considering that we have to show end user that there is some image already and show it hopefully.

I've added FileForm with 3 fields, one is hidden for img_url, second normal image field and third static field (snippet at the end).

For some reason src attr isn't there in the html. 

I'd expect it to appear as usual.

Is this a bug or intentional field constraint?

```php
        $fieldName = $this->getCurrentFieldName();
        $value = $this->getValue();
        $this
            ->add("{$fieldName}_hidden" , 'text', ['rules' => 'required',
                 'attr' => ['style' => 'display:hidden'],

            ])
            ->add(
                $fieldName,
                'file',
                ['label' => 'File']
            );

        if ($value) {
            $this->add(
                'preview',
                'static',
                [
                    'tag' => 'img',
                    'attr' => ['class' => 'form-control-static', 'src' => $value]
                ]
            );
        }
```

**Comment by kristijanhusak** [comment]
@Mpreyzner where this code lives?
Also, does `$value` return anything?

**Comment by Mpreyzner** [comment]
> @Mpreyzner where this code lives?
> Also, does `$value` return anything?
It is subform, that is used in main form
```php
            ->add(
                'picture',
                'form',
                [
                    'class' => FileForm::class,
                    'rules' => 'required',
                    'help_block' => [
                        'text' => 'minimum 400px/400px',
                        'tag' => 'p',
                        'attr' => ['class' => 'help-block'],
                    ],
                ]
            )
```
Value does return, just as a sanity check I've used some random img url and results is still the same.

**Comment by kristijanhusak** [comment]
@Mpreyzner can you give me exact dump of the $value?

**Comment by Mpreyzner** [comment]
For testing purposes I've used some image from google.
```php
        $value = 'https://cdn.vox-cdn.com/thumbor/AX7FqhqX3IOHrvzzNstp9EwMvEE=/0x114:585x559/920x613/filters:focal(248x297:340x389):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/57272301/Screen_Shot_2017_10_23_at_10.16.32_AM.0.png';
```

**Comment by rudiedirkx** [comment]
Works fine for me. The output `<img>` is a bit weird though. I don't think any browser would object, but it's still weird to see an `</img>` closing tag.

```
<img class="form-control-static" id="address[current_picture]" src="/_files/small/address/ab_1.jpg" ></img>
```

What I would do instead is:

```
$this->add('current_picture', 'static', [
	'value' => new HtmlString('<img src="bla" />'),
]);
```

but both should work fine. Are you sure the output HTML doesn't include a `src` attr? Could you look at the raw output HTML and copy it here? It should at least have an `</img>` closing tag.

**Comment by rudiedirkx** [comment]
@kristijanhusak You're just assigning everything to me now? =) M'kay. And you're on the beach with a cocktail somewhere?

**Comment by kristijanhusak** [comment]
@rudiedirkx i wish :-D i know that you know well around static type and that you used it a lot.
