### ISSUE TITLE
getFieldValues return only first item of form collection

### ISSUE THREAD

**Issue by JamesHemery** [kristijanhusak/laravel-form-builder#517]
When I use getFieldValues() to obtain the values of a form collection, it returns only the first collection item.

In my case, I have an EntriesForm class that contain a collection field (type form) that references the EntryForm class. When i submit EntriesForm with many values, getFieldValues() return only the first collection item.. However request()->all() return correctly the collection items.

**Result of getFieldValues():**
```php
array:1 [
  "entries" => array:1 [
    0 => array:1 [
      "name" => "test"
    ]
  ]
]
```

**Result of request()->all():**
```php
array:1 [
  "entries" => array:2 [
    0 => array:1 [
      "name" => "test"
    ]
    1 => array:1 [
      "name" => "test2"
    ]
  ]
]
```

**Reproduce:**
```php
class EntriesForm extends Form
{
    public function buildForm()
    {
        parent::buildForm();
        $this
            ->add('entries', 'collection', [
                'type' => 'form',
                'options' => [
                    'class' => EntryForm::class,
                    'label' => false
                ]
            ])
            ->add('submit', 'submit', ['label' => 'Save']);
    }
}
```

```php
class EntryForm extends Form
{
    public function buildForm()
    {
        parent::buildForm();
        $this
            ->add('name', Field::TEXT, [
                'rules' => 'required'
            ]);
    }
}
```

```php
class RegisterController extends Controller
{
    public function index(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(EntriesForm::class, [
            'url' => route('store'),
            'method' => 'POST'
        ]);

        return view('index', compact('form'));
    }

    public function store(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(EntriesForm::class);
        dump(request()->all());
        dd($form->getFieldValues());
    }
}
```

**Comment by rudiedirkx** [comment]
Which values are accepted and returned depends on the form build.

If you build the form with a model with a collection with 4 elements, 4 or 5 elements are accepted (depending on `empty_row`).

If you build the form with option `prefer_input=true`, all POST input is used for validation, and returned.

If only 1 element is returned, your form is probably `empty_row=true, prefer_input=false` (the default). If you change `prefer_input=true`, all input is validated and returned.

**Comment by JamesHemery** [comment]
@rudiedirkx I see, thank you for these precisions.

**Comment by rudiedirkx** [comment]
Does this solve your case?

**Comment by JamesHemery** [comment]
@rudiedirkx Sorry I did not see your question, yes by setting data with an empty array when configuring the field it works.

**Comment by pooriamo** [comment]
@rudiedirkx `prefer_input` isn't documented anywhere!

**Comment by rudiedirkx** [comment]
@pooriamo PR for updating the docs are very welcome: https://github.com/kristijanhusak/laravel-form-builder/blob/gh-pages/_posts/2015-05-24-collection.md
