### ISSUE TITLE
Form::select selected not working

### ISSUE THREAD

**Issue by ahmadazimi** [kristijanhusak/laravel-form-builder#52]
Hi,

I'm trying to use this form builder in my project. Everything is fine except this one:

when I navigate to edit page, noo select field is selected!
I investigated in your code and I found something wrong: In views/select.php you cast $options['selected'] as an array:

`<?= Form::select($name, (array)$emptyVal + $options['choices'], (array)$options['selected'], $options['attr']) ?>`

But in Laravel default formbuilder in getValueAttribute function, it checks:
`if ( ! is_null($value)) return $value;`

So an empty array never is null and select field never show selected value in the edit screen. By changing your above code to this one: (removing array casting for selected)

`<?= Form::select($name, (array)$emptyVal + $options['choices'], $options['selected'], $options['attr']) ?>`

everything goes fine!

Is this a bug?

**Comment by kristijanhusak** [comment]
I noticed that bug several versions before. It was updated, check [here](https://github.com/kristijanhusak/laravel-form-builder/commit/2dddb85f33618e5621038a01801f9b3641fcaf6e#diff-55ef8c21a55e5372c70274ace8ec30ea).

So you probably need a composer update, and if you published views before, you need to do that again, or fix this bug manually in published views.

**Comment by ahmadazimi** [comment]
Thank you,
I had updated the composer, but I didn't publish vendor.
Now everything works fine.
