### ISSUE TITLE
Can I add Collection prototype from php?

### ISSUE THREAD

**Issue by Mpreyzner** [kristijanhusak/laravel-form-builder#522]
So I've tried calling prototype(), but I cannot add child element to collection after it has been already created.

Is there any way to generate prototype for collection from php?

**Comment by rudiedirkx** [comment]
The prototype is for creating dynamic collection elements with JS. Why are you adding more collection elements later? If the prototype is created once, you can get it with `prototype()`, but its only function is for making dyanmic HTML in JS.
