### ISSUE TITLE
possibility to set default method as post

### ISSUE THREAD

**Issue by jva91** [kristijanhusak/laravel-form-builder#524]
Is there a way to set all the forms default to method='POST'. Now i always set method => post to every form otherwise it would be a GET request. 

It would be nice if there is a default setting for this.

**Comment by rudiedirkx** [comment]
Not really. You could use the `AfterFormCreation` event... I'd like a simpler way too. Maybe some `config/laravel-form-builder` config with default options. Wanna PR?

**Comment by jva91** [comment]
I made a pull request.

**Comment by rudiedirkx** [comment]
Excellent. Further commo there.
