### ISSUE TITLE
How to access related one information

### ISSUE THREAD

**Issue by mikeerickson** [kristijanhusak/laravel-form-builder#53]
Created a form as follows, doesnt want to pull in the Company information, suggestions?

<pre>

<?php namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class ContactForm extends Form
{
	public function buildForm()
	{
		$this
			->add('active', 'checkbox', ['label' => 'Active'])
			->add('salutation', 'text', ['label' => 'Salutation:'])
			->add('company.name', 'text', ['label' => 'Company:'])
			->add('company.country', 'text', ['label' => 'Country:'])
			->add('first_name', 'text', ['label' => 'First Name:'])
			->add('last_name', 'text', ['label' => 'Last Name:'])
			->add('email', 'text', ['label' => 'EMail:'])
			->add('phone', 'text', ['label' => 'Phone:'])
			->add('Save', 'submit', [
				'attr' => ['class' => 'btn btn-primary']
			]);
	}
}

</pre>

**Comment by kristijanhusak** [comment]
Try using `company[name]` and `company[country]`, and also pull relationship data in your model
`Model::with('company')->findOrFail($id)`
I tried using dot notation in plain laravel form, and it did not work for me, only with `[ ]`. In Laravel 4 if i remember well, it was possible to use dot notation, but for some reason in Laravel 5 it's not working.

**Comment by mikeerickson** [comment]
Hey Kris

Thanks for recommendations, I will give it a try.   I know the model data is there (I have dumped that) so perhaps the xxx[yyy] format will do the trick.   I know that L4 did support dot notation so that is why I tried it.

Thanks again!

**Comment by kristijanhusak** [comment]
You're welcome :)
