### ISSUE TITLE
[Question] create section into form

### ISSUE THREAD

**Issue by LPABelgium** [kristijanhusak/laravel-form-builder#530]
Hi,
First, thanks @kristijanhusak for this package ;)

I wish to know if there is a way to visually create a sort of "sections" into the form?
I mean some structure like that:

** Coordinates (section) **
- address (field)
- zip (field)
- city (field)

** Personal datas (section) **
- first name (field)
- last name (field)

etc.

HTML tag for section could be a BS .jumbotron with head tags.

Does it exist right now? Or there's a way to achive this?

**Comment by LPABelgium** [comment]
mmm ... perhaps I could do that by creating a "section" custom fields with BS jumbotron structure...

**Comment by rudiedirkx** [comment]
I'd love to see that code! I miss sections too sometimes. I just override the `form.php` and add `<fieldset>`, but I'd like to make sections in the form class.

**Comment by LPABelgium** [comment]
@rudiedirkx  Hi Rudie,
I simply used a "Section" custom field with BS4.3 html tags to use a Jumbotron class.
```
<div class="row mt-5">
    <div class="col-12">
        <div {!! $options['wrapperAttrs'] !!}>
            <h4 class="text-uppercase m-0">{!! $options['label'] !!}</h4>
        </div>
    </div>
</div>
```
Work fine for what I wanted to have. It's easier than to use `fieldset` tags

For `fieldset` I don't really know how you could do this, with the same way as the `form.php` ? Or maybe you could create a custom field with a "open fieldset" and another one with "closed fieldset" ? It should work as well with perhaps more control on what into it

**Comment by rudiedirkx** [comment]
Ooh, you're only creating a field, not a field wrapper (like a fieldset)? If you want a single self-containing field, yes, make a custom field with custom template. I was looking for a field wrapper, like a fieldset, to put 4 address fields in, or the profile picture field:

- name
- email
- address: (fieldset)
    - street
    - zipcode
    - city
- profile picture: (fieldset)
    - upload new
    - delete old

Adding fieldsets around fields in form.php works well enough.

**Comment by LPABelgium** [comment]
Yes, it's enough for my purpose and the design for this kind of forms. I accord you that's the simpliest way to achieve this.

If I had to add fieldset, perhaps add this as a form or field attribute, passed to form.php to construct it. I didn't dive into the code right now, just want to structure the form like that :
![Capture d’écran 2019-05-27 à 13 24 23](https://user-images.githubusercontent.com/11231179/58416714-c4f4eb80-8082-11e9-83fb-95e9176da19a.jpg)

"Permissions d'utilisation" is wrapped in a BS4 jumbotron wrapper, like this I could structure the form, and give more information about this section to the user. "Permissions d'utilisation" is a <h4>, could had some other <p> tags for more information or anything else (like refer to a PDF documentation). More flexible and userfriendly than a fielset but it's just my own opinion about that ;)
