### ISSUE TITLE
Some fields of my form are not being populated although I am passing the values to the form's model 

### ISSUE THREAD

**Issue by nerdroid23** [kristijanhusak/laravel-form-builder#532]
**Fields**
```php
[
  "tipo_persona" => SelectType {
    #name: "company[tipo_persona]"
    #type: "select"
  }
  "razon_social" => InputType {
    #name: "company[razon_social]"
    #type: "text"
  }
  "rfc" => InputType {
    #name: "company[rfc]"
    #type: "text"
  }
  "address" => ChildFormType {
    #form: AddressForm
    #name: "company[address]"
    #type: "form"
  }
  "nombre_contacto" => InputType {
    #name: "company[nombre_contacto]"
    #type: "text"
  }
  "correo" => InputType {
    #name: "company[correo]"
    #type: "email"
  }
  "telefono" => InputType {
    #name: "company[telefono]"
    #type: "tel"
  }
  "otros_datos" => CheckableType {
    #name: "company[otros_datos]"
    #type: "checkbox"
  }
  "invoice" => ChildFormType {
    #name: "company[invoice]"
    #type: "form"
  }
]
```

**Model**
```json
{
    "company": {
        "tipo_persona": "0",
        "razon_social": "Flores and Leonard Associates",
        "rfc": "Ramos and Rodgers Inc"
    },
    "company.address": {
        "calle": "Arnold and Riggs Inc",
        "num_ext": "18",
        "num_int": "Pate Cleveland Inc",
        "colonia": "Allison Robles Associates",
        "ciudad": "Avila and Finley Associates",
        "estado": "VER",
        "codigo_postal": "91815"
    },
    "company.nombre_contacto": "Ross and Valenzuela LLC",
    "company.correo": "nuzeqi@mailinator.com",
    "company.telefono": "2589275002",
    "company.otros_datos": "1",
    "company.invoice": {
        "tipo_persona": "0",
        "razon_social": "Wade and Delaney LLC",
        "rfc": "Green and Mcclure Trading"
    },
    "company.invoice.address": {
        "calle": "Nielsen Day Co",
        "num_ext": "77",
        "num_int": "Case Lloyd Plc",
        "colonia": "Simon and Travis LLC",
        "ciudad": "Jennings and Church Plc",
        "estado": "ZAC",
        "codigo_postal": "96871"
    }
}
```

**Comment by nerdroid23** [comment]
The fields that are not getting populated are the followings:
`
company[razon_social]
company[invoice][address]
`

**Comment by rudiedirkx** [comment]
Don't copy var-dumper's output =) That doesn't work as plain text. If it's relevant, replace it. I can't read this.

How do you build the form? E.g.

    $form = $formBuilder->create(MyForm::class, ['model' => $data]);

**Comment by nerdroid23** [comment]
Hi, I updated the output.

This is the chunk of code I use to create the form

```php
use FormBuilderTrait;

public function show()
{
    $form = $this->form(CompanyForm::class, [
        'method' => 'POST',
        'url' => route('contratar.paso-1.process'),
        'model' => [
        'company' => Session::get('company.info'),
        'company.address' => Session::get('company.address'),
        'company.nombre_contacto' => Session::get('user.nombre'),
        'company.correo' => Session::get('user.correo'),
        'company.telefono' => Session::get('user.telefono'),
        'company.otros_datos' => Session::get('company.otros_datos'),
        'company.invoice' => Session::get('invoice.info'),
        'company.invoice.address' => Session::get('invoice.address'),
        ],
    ]); return $form->getModel();

    return view('auth.register.paso-1', compact('form'));
}
```

**Comment by rudiedirkx** [comment]
`'model'` should be an array like in the original post: not a single 1-dimensional list, but nested as necessary:

```
'model' => [
    'company' => [
        'info' => Session::get('company.info'),
        'address' => Session::get('company.address'),
        'nombre_contacto' => Session::get('user.nombre'),
        'correo' => Session::get('user.correo'),
        'telefono' => Session::get('user.telefono'),
        'otros_datos' => Session::get('company.otros_datos'),
        'invoice' => [
            'info' => Session::get('invoice.info'),
            'address' => Session::get('invoice.address'),
        ],
    ],
],
```

or something. Assuming the sub forms are sub forms.

**Comment by rudiedirkx** [comment]
Oh, wait, they're not sub forms: `#name: "company[correo]"`. In that case the default value might not work... The form builder wasn't really made for field names like that to nest. It works sometimes, but not all of it. It's better to use real sub forms:

```
$this->add('invoice', 'form', [
    'class' => CompanyInvoiceForm::class,
]);
```

etc. See the docs for more options.

**Comment by nerdroid23** [comment]
This is the `buildForm()` function of the `CompanyForm` class

```php
public function buildForm()
{
 $this
 ->compose(
	'App\Forms\CompanyInfoForm'
 )
 ->add('address', 'form', [
	'class' => 'App\Forms\AddressForm',
 ])
 ->add('nombre_contacto', 'text', [
	'rules' => 'required|string',
	'label' => 'Nombre de Contacto',
	'required' => true,
 ])
 ->add('correo', 'email', [
	'rules' => 'required|email|unique:users,email',
	'label' => 'Correo Electrónico',
	'required' => true,
 ])
 ->add('telefono', 'tel', [
	'rules' => 'required|digits:10',
	'label' => 'Teléfono',
	'required' => true,
 ])
 ->add('otros_datos', 'checkbox', [
	'rules' => 'sometimes|boolean',
	'wrapper' => ['class' => 'custom-control custom-checkbox'],
	'attr' => [
	   'class' => 'custom-control-input js-checked',
	   'data-toggle' => 'collapse',
	   'data-target' => '#new_rfc',
	   'id' => 'otro_rfc',
	],
	'label' => 'Deseo utilizar otros datos para facturación',
	'label_attr' => [
	   'class' => 'custom-control-label',
	   'for' => 'otro_rfc',
	],
	'required' => false,
 ])
 ->add('invoice', 'form', [
	'class' => 'App\Forms\InvoiceForm',
 ]);
}
```

**Comment by nerdroid23** [comment]
> `'model'` should be an array like in the original post: not a single 1-dimensional list, but nested as necessary:
> 
> ```
> 'model' => [
>     'company' => [
>         'info' => Session::get('company.info'),
>         'address' => Session::get('company.address'),
>         'nombre_contacto' => Session::get('user.nombre'),
>         'correo' => Session::get('user.correo'),
>         'telefono' => Session::get('user.telefono'),
>         'otros_datos' => Session::get('company.otros_datos'),
>         'invoice' => [
>             'info' => Session::get('invoice.info'),
>             'address' => Session::get('invoice.address'),
>         ],
>     ],
> ],
> ```
> 
> or something. Assuming the sub forms are sub forms.

I will give this a try and see how it goes

**Comment by nerdroid23** [comment]
> Oh, wait, they're not sub forms: `#name: "company[correo]"`. In that case the default value might not work... The form builder wasn't really made for field names like that to nest. It works sometimes, but not all of it. It's better to use real sub forms:
> 
> ```
> $this->add('invoice', 'form', [
>     'class' => CompanyInvoiceForm::class,
> ]);
> ```
> 
> etc. See the docs for more options.

`#name: "company[correo]"` works completely fine, the fields that are not being populated are `company[razon_social]` and `company[invoice][address]`

**Comment by rudiedirkx** [comment]
They are real sub forms! Then the nested 'model' array should work fine.

If the parent form has a name (`setName()`, not class name), the entire model data should be wrapped in that name. That might be your issue.

We'll get there!

**Comment by nerdroid23** [comment]
> `'model'` should be an array like in the original post: not a single 1-dimensional list, but nested as necessary:
> 
> ```
> 'model' => [
>     'company' => [
>         'info' => Session::get('company.info'),
>         'address' => Session::get('company.address'),
>         'nombre_contacto' => Session::get('user.nombre'),
>         'correo' => Session::get('user.correo'),
>         'telefono' => Session::get('user.telefono'),
>         'otros_datos' => Session::get('company.otros_datos'),
>         'invoice' => [
>             'info' => Session::get('invoice.info'),
>             'address' => Session::get('invoice.address'),
>         ],
>     ],
> ],
> ```
> 
> or something. Assuming the sub forms are sub forms.

hey @rudiedirkx thanks for your help, I figured it out! The solution you proposed was part of the solution.

My mistake was that I that I had used `$this->compose(Form::class)` instead of `$this->add('name', 'form', ['class' => Form::class])`

And I also set the `$name` property on the forms.

Thanks again, we got there! 🙌
