### ISSUE TITLE
validation through ajax

### ISSUE THREAD

**Issue by TsePakKwan** [kristijanhusak/laravel-form-builder#533]
Hi @kristijanhusak 
I want to use laravel-form-builder validation through ajax.
Can you help me how to use laravel-form-builder validation on Controller?

**Comment by rudiedirkx** [comment]
What should the ajax response do? Make a JS `alert()`? Highlight the error fields? Add a single validation message above the form? There's no one normal/good way. There are many. Like there are many ways to show validation messages without ajax. It's up to the developer to make one work.

What do you have? What happens now?

If you need general ajax/form help, you should ask on StackOverflow.

**Comment by TsePakKwan** [comment]
> What should the ajax response do? Make a JS `alert()`? Highlight the error fields? Add a single validation message above the form? There's no one normal/good way. There are many. Like there are many ways to show validation messages without ajax. It's up to the developer to make one work.
> 
> What do you have? What happens now?
> 
> If you need general ajax/form help, you should ask on StackOverflow.

thank you @rudiedirkx 
I have solved the problem  by myself (overwrite Form class function validate on my Form class).

My problem is that I have a single form that already has a page in use, but the same form content on other pages needs to be submitted and verified through AJAX.
