### ISSUE TITLE
File validation server-side

### ISSUE THREAD

**Issue by Jack94son** [kristijanhusak/laravel-form-builder#538]
Hi, I had an issue regarding the file validation.

I got to upload file with max size: 1.5MB and only accept PDF/JPEG. And I got this:
```
public static $rules        = [
        'photo' => 'required|size:15000|mimes:pdf,jpeg,jpg';
    ];
```

I uploaded a pdf file with 8KB and I got the error of "Please upload photo with type pdf,jpef,jpg".
Besides, I tried to upload file with size 20,000KB and I got the error of "Please upload photo with file size minimum 15000 characters."

So there 2 questions:
1. Why the error still showing even the file type is correct?
2. Can I change the error message or which validation should I use for file size checking?

**Comment by kristijanhusak** [comment]
When you remove validation does you file successfully uploads?

Did you try adding `file` rule before the size? https://laravel.com/docs/5.8/validation#rule-file

**Comment by Jack94son** [comment]
`public static $rules        = [
        'photo' => 'required';
    ];`
Above is the working version. Without the validation of size and type my file is successfully uploaded.

`public static $rules        = [
        'photo' => 'required|file|size:15000|mimes:pdf,jpeg,jpg';
    ];`
If I add `file` rule, I will have error of "The photo must be a file."

Here is the buildform:

```
$this->add('photo', 'file', [
                'label'      => '<p class="mb-0"><b><u>Photo</u></b></p>',
                'validation' => 'required',
                'mimes'      => 'pdf,jpg,jpeg',
                'max'       => '15000',
                'view'       => 'files',
                'help' => '<small>Accepted file types: PDF/JPEG<br/>Maximum File Size: 1.5MB</small>'
            ])
```
