### ISSUE TITLE
Default value in text inputs

### ISSUE THREAD

**Issue by aktiWeb** [kristijanhusak/laravel-form-builder#54]
Hi,

im trying to set a default value into a text input. But it won't work and i can't get the reason why...

Part of the form class:
```
public function buildForm() {
    $this->add('myfield', 'text', ['label' => 'My field']);
```

Part of the controller class:
```
$form = $formBuilder->create(
    'Forms\MyForm',
    ['method' => 'POST'],
    ['myfield' => 'Default text for my field']);
```
The form will be rendered but with empty fields. The only way to put some data into it was to use "default_value" inside the form class. But this can't be the way...

Many thanks for any kind of hints!

**Comment by kristijanhusak** [comment]
Hi,
You can do it this way:
```php
<?php
public function buildForm() {
    $this->add('myfield', 'text', [
        'label' => 'My field',
        'default_value' => $this->getData('myfield') // Defaults to null if not passed
    ]);
```

Third param for FormBuilder's `create()` method is data that can be used in form class with `$this->getData('key')`, which is in your situation `myfield`.

**Comment by kristijanhusak** [comment]
There are also several other solutions. For example, creating simple array model:
```php
<?php
$model = ['myfield' => 'data for field'];
$form = $formBuilder->create(
    'Forms\MyForm',
    ['method' => 'POST', 'model' => $model]
);
```
This way you do not have to set `default_value` in the field, it will be binded through Laravels form model binding.

Another way is to set this in view if you want. If you split form in views with `form_row()`, you can do this:
```php
form_row($form->myfield, ['default_value' => 'data for field']);
```

Hope i helped.

**Comment by aktiWeb** [comment]
Thanks for your very fast answers.

Imagine i have to render a non-model-based form with 20 fields and any of the fields must be pre-filled with custom values. In this case i really have put the values into the form using 
```
'default_value' => $this->getData('myfield')
```
for each single field?

**Comment by kristijanhusak** [comment]
Well, data needs to be put somewhere, you just need to select simplest way. 
Even if your form is non-model-based, you can use simple array to simulate a model, just to bind values to the form, so i believe that simplest option is to create array model, and pass it in, and it will be binded automatically, so you **do not** have to do this:
```php
'default_value' => $this->getData('myfield')
```

Form:
```php
    $this
        ->add('myfield1', 'text', [
            'label' => 'My field 1'
        ])
        ->add('myfield2', 'text', [
            'label' => 'My field 2'
        ])
        ->add('myfield3', 'text', [
            'label' => 'My field 3'
        ])
        ->add('myfield4', 'text', [
            'label' => 'My field 4'
        ])
```

Controller:
```php
$model = [
    'myfield1' => 'data for field1',
    'myfield2' => 'data for field2',
    'myfield3' => 'data for field3',
    'myfield4' => 'data for field4',
];
$form = $formBuilder->create(
    'Forms\MyForm',
    ['method' => 'POST', 'model' => $model]
);
```

**Comment by aktiWeb** [comment]
Allright! Thats the way!
I didn't know that i can use an array as $model.

Thanks again.

**Comment by kristijanhusak** [comment]
You're welcome :)

**Comment by Milindp24** [comment]
So, how can I set the value for the input field array.
Example:

$this->add('description[hi]', Field::TEXTAREA, ['label' => 'Description (HINDI)', 'wrapper' => ['class' => 'form-group col-md-6']]);

**Comment by rudiedirkx** [comment]
`default_value`
