### ISSUE TITLE
Validation inside if($this->getData('my_field)

### ISSUE THREAD

**Issue by audetcameron** [kristijanhusak/laravel-form-builder#541]
Is there support for validation inside if blocks?
Example: I use a checkout form. 
Sometimes items are free any payment is not required

```
if ($this->getData('payment_required')) {
	$this->add('credit_card', 'text', [
		'wrapper' => [
			'class' => 'form-item',
		],
		'label' => 'Card Number',
		'rules' => 'required',
	]);
}
```

However, the rule / validation isn't working.  
Is there a better approach to using one form, but hiding fields when they are not needed?

**Comment by rudiedirkx** [comment]
That should work... If the field exists, it's validated. The IF statement is the tricky bit though. How does the form know a field/validation is needed. Does the POST request create the form with data `payment_required`? If so, it should add the field, and validate it.

Another way might be conditional validation rules, like `required_with` or `required_if` etc. You could make custom validation rules that are even smarter and more conditional, checking (during validation) other form values and fields. So the field always exists, but it's not always validated. That would simplify the form config (no `if data(payment_required)`) and creation (no data passing).
