### ISSUE TITLE
CollectionType does not work with oldInput if it has only one key and it is not 0

### ISSUE THREAD

**Issue by kmbt** [kristijanhusak/laravel-form-builder#542]
Hi
I have a case, in which I have spiced up the form with some JS to add/remove rows from field collection. 
There is a problem when `CollectionType` field has only one field, but its index is not 0. The following line prevents `$oldInput` from being accepted and the rendered 0-th row does not get its value nor validation message since it does not have a matching index:

https://github.com/kristijanhusak/laravel-form-builder/blob/ed22adc0cfc06b06d0fa3e0b94ed44f44f681399/src/Kris/LaravelFormBuilder/Fields/CollectionType.php#L108

What I would suggest is to extend the check, possibly in a fashion of:
```
if ($oldInput && (count($oldInput) > 1 || array_key_first($oldInput) !== 0)) {
```
or maybe just simplify it:
```
if ($oldInput) {
```
, provided that it does not break things.

**Comment by rudiedirkx** [comment]
If you use JS to shape the input, you should set the `prefer_input` option to `true`, which will take the POST data as input instead of the form's default value or old input.

**Comment by rudiedirkx** [comment]
To debug which attributes (fields) will be validated, before doing the validation in POST, `dd($form->getAllAttributes())`. It will give a full list of all validator attributes, incl. collections and subforms.

**Comment by kmbt** [comment]
Than you for your suggestions. I am using the the `prefer_input` option set to `true`. After the form is submitted i take the data out by means of `$form->getFieldValues()` and validate it by a validator acquired through `Illuminate\Support\Facades\Validator::make()`. On failure i throw an `lluminate\Validation\ValidationException` which makes Laravel return to previous controller and redisplay the form with validation errors.

Everything works properly, except for the aforementioned issue with collection fields. I have run the `CollectionType::createChildren()` through the debugger from which I have gathered that to display old data and validation errors, child fields must have indices matching the ones in `$oldInput`. That will not happen if `$oldInput` is an array with one key and the key is not `0`. Such situation takes place if I remove a [0]-th field using javascript before submitting the form while having only one (ie. [1]-st) left. In every other case it works. The check `count($oldInput) > 1`  simply does not let `$data` to get value of `$oldInput`, which is necessary for the rendered field to have a proper index.

**Comment by rudiedirkx** [comment]
I've never had problems with that condition, so I'm not convinced. What do you see if you `dd($form->getAllAttributes())` in POST before validating? With `prefer_input`, it should list all inputs, no matter the keys/indexes.

Why do you first get the data out, and then validate manually? The form can do all that: `$form->isValid()` or `$form->redirectIfNotValid()`. After that, use `getFieldValues()` to get the validated values.

**Comment by kmbt** [comment]
If I add a [1]-st row in JS and remove the [0]-th , `dd($form->getAllAttributes())` gives:

```
  "my_field" => array:1 [▼
    1 => null
]
```
If the field has errors (for instance `my_field.*` is required) the validation message will not show in spite of the validation error returned to the form because the form will try to fetch error for the [0]-th row, and there is none. The error is associated with the [1]-st row.

The reason I am validating manually is the fact, that my validation process is very complex (and dependent on input, and some other external data) and that I expect to reuse the validator in an API. I could probably generate the rules and pass them to `$form->validate()`, however I do not think that the chosen method of validation is the cause of this problem.

**Comment by rudiedirkx** [comment]
Your collection field is `my_field` without any validations? The `getAllAttributes()` looks odd... If I remove item `0` and add an item `2` with JS, my attributes dump is:

```
Array
(
    [0] => log
    [1] => translations.1.from
    [2] => translations.1.to
    [3] => translations.2.from
    [4] => translations.2.to
)
```

It's a numerical array of ALL validated attributes, not indexed by field.

If your form after redirect doesn't show all the input fields, your validation doesn't remember input data correctly. Could you try the normal form builder validation?

I usually submit forms like this with Ajax, so the form never unloads, and the redirect doesn't have to remember data. That introduces other problems of course (displaying errors), but it's mostly easier IMO.

**Comment by zlanich** [comment]
I can add to this, as I'm having the same issue:

_* Screenshots below_

My use case is saving Mailing Addresses to a User. If the user has no addresses, and I'm not using the `'empty_row' => true` (related, I believe), and I add a new address, fail validation, `$oldInput` is there, but this section of code causes it to be ignored completely:
```php
// Needs to have more than 1 item because 1 is rendered by default.
// This overrides current request in situations when validation fails.
if ($oldInput && count($oldInput) > 1) {
    $data = $oldInput;
}
```
For now, I'm overriding this and checking if `'empty_row' => false` and use `0` instead of `1`, which solves my problem for now, but I haven't looked into what other side affects this might have.

Let me know if you need any more information.

![addresses_ui](https://user-images.githubusercontent.com/1522665/74072765-e9f17a80-49d5-11ea-9fde-467f05394419.png)
![xdebug_addresses](https://user-images.githubusercontent.com/1522665/74072766-e9f17a80-49d5-11ea-8592-f00e5515a0c8.png)

**Comment by rudiedirkx** [comment]
If you're not `empty_row`, how do you add a new address? With JS? Then you need `prefer_input`. Without it, the form only validates the input from the GET form (so no 'new address').

Why is CollectionType in your `App` namespace? What's different?

**Comment by rudiedirkx** [comment]
And also, you must create the form in the POST action with the same date as in the GET action. If you don't, the POST form will think it has different fields. That matters less with `prefer_input` on, but still. If you make the GET form with a `model`, you must use the same `model` in the POST form. I can't reproduce this bug, so I THINK you're doing something wrong.
