### ISSUE TITLE
[want help] Collection Validation 'required_if'

### ISSUE THREAD

**Issue by TsePakKwan** [kristijanhusak/laravel-form-builder#543]
laravel-form-builder : 1.20.0
Laravel : 5.7.28
I have relation table, just like below.

Table : carType (Collection : has many car)
field : id, name, status
Table : car
field : id, carType_id, name, status

I try to set below Form, 
status is hidden field , throw my js to change value to 0 or 1 and add Collection,
CarTypeForm normally pass validation.
but CarForm 'required_if' abnormal validation 
already try rule 
 'required_if:car.*.status,0' and  'required_if:status,0'
 but both when car.status = 0 ,null name Field  can passed valid.
Any idea?

```
class CarTypeForm extends Form {

	public function buildForm() {

		$this->add('name', Field::TEXT, ['rules' => 'required_if:status,0']);
		$this->add('status', Field::HIDDEN);

		$this->add('car', 'collection', [
			'type' => 'form',
			'options' => [
				'prefer_input' => true,
				'class' => 'App\Forms\CarForm',
				'label' => false,
			]
		]);
		$this->add('submit', Field:: BUTTON_SUBMIT);
	}

}

class CarForm extends Form {

	public function buildForm() {
		$this->add('name', Field::TEXT, ['rules' => 'required_if:car.*.status,0']);
		$this->add('status', Field::HIDDEN);
	}

}
```

**Comment by rudiedirkx** [comment]
Yeeaah, that doesn't work very well. There is an issue about that somewhere, but it's not easy to fix. I've fixed this in my own app (for `required_with`, same problem) by using the `AfterCollectingFieldRules` event:

	$app['events']->listen(AfterCollectingFieldRules::class, function(AfterCollectingFieldRules $event) {
		$formHelper = $this->app['laravel-form-helper'];

		$ruler = $event->getRules();
		$fieldName = $formHelper->transformToDotSyntax($event->getField()->getName());
		if (strpos($fieldName, '.') === false) {
			return;
		}

		$prefix = preg_replace('#\.[^\.]+$#', '.', $fieldName);
		$rules = $ruler->getFieldRules();

		foreach ($rules as $i => &$rule) {
			if (preg_match('#^(required_with):(.+)$#', $rule, $match)) {
				$rule = $match[1] . ':' . $prefix . $match[2];
			}
			unset($rule);
		}

		$ruler->setFieldRules($rules);
	});

It alters all `required_with` rules at the last second, to contain field/form context. You might have to adjust it some to work for `required_if`.

**Comment by TsePakKwan** [comment]
> Yeeaah, that doesn't work very well. There is an issue about that somewhere, but it's not easy to fix. I've fixed this in my own app (for `required_with`, same problem) by using the `AfterCollectingFieldRules` event:
> 
> ```
> $this->app['events']->listen(AfterCollectingFieldRules::class, function(AfterCollectingFieldRules $event) {
> 	$formHelper = $this->app['laravel-form-helper'];
> 
> 	$ruler = $event->getRules();
> 	$fieldName = $formHelper->transformToDotSyntax($event->getField()->getName());
> 	if (strpos($fieldName, '.') === false) {
> 		return;
> 	}
> 
> 	$prefix = preg_replace('#\.[^\.]+$#', '.', $fieldName);
> 	$rules = $ruler->getFieldRules();
> 
> 	foreach ($rules as $i => &$rule) {
> 		if (preg_match('#^(required_with):(.+)$#', $rule, $match)) {
> 			$rule = $match[1] . ':' . $prefix . $match[2];
> 		}
> 		unset($rule);
> 	}
> 
> 	$ruler->setFieldRules($rules);
> });
> ```
> 
> (In a service provider.) It alters all `required_with` rules at the last second, to contain field/form context. You might have to adjust it some to work for `required_if`.

@rudiedirkx  thank a lot, 
but I cannot find relate doc on
https://kristijanhusak.github.io/laravel-form-builder/
Could you explain in detail how to use AfterCollectingFieldRules?
I try to copy your code to CarForm > buildForm method,
then show error 'Call to a member function listen() on null'

**Comment by rudiedirkx** [comment]
`AfterCollectingFieldRules` isn't documented yet, sorry. Feel free to!

This code starts in a service provider, like `AppServiceProvider` (or what's it called?, the one that Laravel gives you). `$this->app['events']` is the global `events` service in the app container. The form builder triggers a `AfterCollectingFieldRules` event just before validating a field. You can add/remove/validation rules depending on anything/context. In this case, it slightly changes the `required_with` rule if it's in a field in a subform.

**Comment by TsePakKwan** [comment]
@rudiedirkx 
Sorry, I don't quite understand what you mean. 
Do you mean add events listen to App\Providers\EventServiceProvider ?
Then how to setup rules?
just like as below?
```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Event;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Kris\LaravelFormBuilder\Events\AfterCollectingFieldRules;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
			AfterCollectingFieldRules::class,
        ],
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        //
    }
}

```

**Comment by rudiedirkx** [comment]
No. In `EventServiceProvider` is fine, but add my code to `boot()` after `parent::boot()`. Service providers have a `$this->app`, and `$this->app['events']` should be available in `boot()`.

**Comment by TsePakKwan** [comment]
@rudiedirkx 
Do you mean as below code?
But I don't know value `$match`, Where does this value come from?
I try below code , but not success my rules,

```

<?php

namespace App\Providers;

use Illuminate\Support\Facades\Event;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

use Kris\LaravelFormBuilder\Events\AfterCollectingFieldRules;

class EventServiceProvider extends ServiceProvider {

	/**
	 * The event listener mappings for the application.
	 *
	 * @var array
	 */
	protected $listen = [
		Registered::class => [
			SendEmailVerificationNotification::class,
			AfterCollectingFieldRules::class,
		],
	];

	/**
	 * Register any events for your application.
	 *
	 * @return void
	 */
	public function boot() {
		parent::boot();

		//
		$this->app['events']->listen(AfterCollectingFieldRules::class, function(AfterCollectingFieldRules $event) {
			$formHelper = $this->app['laravel-form-helper'];

			$ruler = $event->getRules();
			$fieldName = $formHelper->transformToDotSyntax($event->getField()->getName());
			if (strpos($fieldName, '.') === false) {
				return;
			}

			$prefix = preg_replace('#\.[^\.]+$#', '.', $fieldName);
			$rules = $ruler->getFieldRules();

			foreach ($rules as $i => &$rule) {
				if (preg_match('#^(required_if):(.+)$#', $rule, $match)) {
					$rule = $match[1] . ':' . $prefix . $match[2];
				}
				unset($rule);
			}

			$ruler->setFieldRules($rules);
		});
	}

}

```

**Comment by TsePakKwan** [comment]
@rudiedirkx  
Could you please make a full example for this case?
Collection data is post by dynamic(probably because of prototype + JS)

**Comment by rudiedirkx** [comment]
Oh, right, `getFieldRules()` isn't released yet. The newest release is behind master. I always use dev + patches, so you probably can't reproduce this. Sorry. Forget I mentioned anything.

I won't make a full example. If you're a Laravel developer, you have to know the packages you use, and know how to improve and use them. I only provide tips and snippets, not working code.

To summarize completely: You're right. Validation rules like `required_if` and `required_when` don't work inside subforms. There's no easy way to fix this. Patches/PRs are very welcome.
