### ISSUE TITLE
Accessing Request before instanciating a Form

### ISSUE THREAD

**Issue by angristan** [kristijanhusak/laravel-form-builder#544]
First of all, thank you for Form builder!

---

This works:

```php
public function storeUser(FormBuilder $formBuilder)
{
    $form = $formBuilder->create(UserForm::class);
        
    $request = $form->getRequest();
...
```

Now, is there a way to access my `Request` object **before** calling `$formBuilder->create()`? I want to call this method conditionally depending on the content of `Request->route('slug')`.

Or is there a way to pass `Request $request` to my controller and then instantiating my `Form` using `$request`?

**Comment by angristan** [comment]
For now I managed to do this:

```php

public function storeUser(FormBuilder $formBuilder)
{
    $tmpForm = $formBuilder->plain();
    $request = $tmpForm->getRequest();

    // Some conditions with $request
    $form = $formBuilder->create(...)
```

But it's not very pretty 😕

**Comment by rudiedirkx** [comment]
You can just type hint it in the action method, and Laravel's container adds it:

    public function storeUser(Request $request, FormBuilder $formBuilder)

Be sure to import it. See https://laravel.com/docs/5.8/requests#accessing-the-request

**Comment by angristan** [comment]
That's awesome! Thanks for helping out a newbie :+1:
