### ISSUE TITLE
Add a damn example in your doc ?

### ISSUE THREAD

**Issue by vince83110** [kristijanhusak/laravel-form-builder#546]
Is it possible to have an example in your doc how to create / update a model ?

I found the example how to create in "validation", but how to update ?

Is there any binding with your plugin ? Documentation is poor. 

This can work ? ($form is an instance of \Kris\LaravelFormBuilder\Form)

`$form->getModel()->save();`

Please advise ...

**Comment by kristijanhusak** [comment]
>  Documentation is poor.

Feel free to open up a PR and improve it. This is an open source project, which is not funded in any way.

you have example here how to store data http://kristijanhusak.github.io/laravel-form-builder/overview/validation.html

**Comment by vince83110** [comment]
With pleasure to open PR, I like to contribute to projects, yours is good. But it seems so different from Symfony Form Builder. My question is : is there any binding between Model and Request here ?

When I dump : 

`$form->getModel()`

I have or an empty Model, or the originate Model if I update. Thanks for advise.

**Comment by vince83110** [comment]
PR added, I hope I understood correctly your project.

**Comment by rudiedirkx** [comment]
There's no binding or automatic update like in Sf. You have to get the form values and update the model manually after validation:

    Post::create($form->getFieldValues());
    // or
    $post->update($form->getFieldValues());

Your PR is excellent.

**Comment by bobmulder** [comment]
Oof, it's kinda poor that the modal you can pass is not used for returning data (like Symfony does). Trying to dig into the library to make this happen...
