### ISSUE TITLE
[Question] Work with 2 models within same Form

### ISSUE THREAD

**Issue by LPABelgium** [kristijanhusak/laravel-form-builder#553]
Hi Kris,

Not an issue, just a question.

How to deal when we have to work with 2 Eloquent Models on the same Form ?
How to build the form (default values) ?

Both models have to be created / updated through the same form in the same controller (in my case user & its addresses)

Is it possible ?

Laravel : 5.8
Form Builder : 1.6.*

**Comment by bobmulder** [comment]
Got stuck because the model you pass is not used to parse data from the request to the model. Instead you can call `$form->getFieldValues()` (which will return an array). This is exactly what you don't want to do. You want your model (or ` *Data` class) to be filled with the data.

Related issue: #546

**Comment by LPABelgium** [comment]
@bobmulder  I think I found the solution, but need to get it a try. 
I think Kris have thought about it as "separate forms" that could be associated through [compose](http://kristijanhusak.github.io/laravel-form-builder/form/methods-and-properties.html)

Will try it now & let you know the result

**Comment by bobmulder** [comment]
Please let me know if this works! I doubt ;)

I am currently using https://github.com/barryvdh/laravel-form-bridge which fits well for me! Currently investigating if I can use Symfony Form without twig, but this library fits well enough for me.

**Comment by LPABelgium** [comment]
Depending what your needs are, but for me, it seems to be ok.
My case is : Member & Addresses models, Member could have many Addresses.

I created a MemberForm & a AddresseForm.
AddresseForm is included into MemberForm through "compose".
$request includes all fields' datas. But not separated. So you have to deal with this, not so bad.
Validation are for both (since AddresseForm is included into MemberForm).

For my (this) case, it's working. & Happy for you if you found your own solution ;)

**Comment by rudiedirkx** [comment]
@LPABelgium You can add 'form' type fields to your form, and an assoc array with 2 models for data. Or in your case, add a 'collection' type field 'addresses' to MemberForm. I think collection field fits perfectly.
