### ISSUE TITLE
Call to undefined function str_contains() using Laravel 6

### ISSUE THREAD

**Issue by bobmulder** [kristijanhusak/laravel-form-builder#556]
The following error is thrown when 'posting' my form:

> **Call to undefined function Kris\LaravelFormBuilder\Fields\str_contains()**

Inspecting the code, looks like it breaks when checking my validation rules:
```php
            ->add('company_name', 'text', [

                'rules' => 'required|ip'

            ])
```

I am using Laravel 6.0 (while I am using Laravel Form Builder 1.21.0). It seems that is the problem?

**Comment by bobmulder** [comment]
Laravel docs say that the `arr_` and `str_` helpers are moved to a separate package called `laravel/helpers`.

I've required the package to my application using `composer require laravel/helpers` which worked.

I suppose this library should be a dependency to this package?

**Comment by MatejKucera** [comment]
Making it dependent on laravel/helpers is one approach. 
The second (and in my opinion the better) is to change all str_ calls to Str helper (see https://laravel.com/docs/6.x/upgrade#helpers)

**Comment by mikeerickson** [comment]
We have already made this change in the version we are preparing for full Laravel 6 support (they are all using Str::xxx now)

**Comment by KNuwanBandara** [comment]
Try with using  "composer require laravel/helpers"
It have try it with Laravel 7
![image](https://user-images.githubusercontent.com/52135316/79053010-bd691180-7c57-11ea-9d90-1fefcca4223c.png)
