### ISSUE TITLE
Laravel Form Builder 2.x

### ISSUE THREAD

**Issue by mikeerickson** [kristijanhusak/laravel-form-builder#558]
I am in the process of preparing a new branch for laravel-form-builder which will be specific to Laravel 6.x moving forward.  

We will be maintaining the current 1.2 branch for issues related to Laravel <= 5.8, but moving forward, all new features will be applied to 2.x branch.

If you have issues related to Laravel 6, please continue to report them here, but know that they will only be applied to laravel-form-builder v2 branch

If you have specific questions or comments, please let us know.

@rudiedirkx @kristijanhusak

**Comment by GeoSot** [comment]
Hello @mikeerickson 
Can you make an estimation, on when we are going to see any update on laravel-form-builder v2 branch?

**Comment by rudiedirkx** [comment]
Laravel 6 is largely backward compatible with 5.x, isn't it? Why make a new branch? That seems like unnecessary extra work. Does it not work with Laravel 6?

**Comment by ChenRuihua** [comment]
need this  https://github.com/kristijanhusak/laravel-form-builder/issues/425  thank you

**Comment by rudiedirkx** [comment]
You can and should do that with custom template. You can override the entire form template, and customize 1 field, or override the specific field template.
