### ISSUE TITLE
Laravel 6 - issue with form errors

### ISSUE THREAD

**Issue by checkerschaf** [kristijanhusak/laravel-form-builder#561]
Hey,

using Laravel 6 there's an error when creating forms with errors. 
`Call to undefined function Kris\LaravelFormBuilder\Fields\str_contains() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Kris\\LaravelFormBuilder\\Fields\\str_contains() at /var/www/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Fields/FormField.php:554)`

It can easily be fixed by replacing it with the `Str::contains` helper.

**Comment by checkerschaf** [comment]
Just wanted to create a pull request addressing the fix and found out that it is already fixed in master. Could you please create a new release @kristijanhusak? Thanks in advance :)

**Comment by mikeerickson** [comment]
No release coming in the immediate future as we are preparing our 2.x release which will be for Laravel >= 6.  I should get it wrapped up this weekend.
