### ISSUE TITLE
[want help]Collection of child forms, set maximum/minimum child rule

### ISSUE THREAD

**Issue by TsePakKwan** [kristijanhusak/laravel-form-builder#562]
Hi, 

I have some question about Collection of child forms,
How can I set a rule maximum/minimum child on laravel-form-builder?
just like doc example at 
`http://kristijanhusak.github.io/laravel-form-builder/field/collection.html`

normally validator just like as below, but I don't know how to set it on laravel-form-builder
```
$validator = Validator::make($request->all(), [
    'tags.*' => 'max:5',
    'tags.*' => 'min:3',
    'tags.*.id' => 'required',
]);
```

tank you.

**Comment by rudiedirkx** [comment]
The child form's fields define its rules. Not the parent form. [See the docs on validation.](http://kristijanhusak.github.io/laravel-form-builder/overview/validation.html)

If they're somehow linked, you can pass data from the parent to the child form, and use that to define rules.
