### ISSUE TITLE
Multiple submit button with same name

### ISSUE THREAD

**Issue by R1Daneel** [kristijanhusak/laravel-form-builder#563]
Is there a way to have in the form multiple submit button with the same name but different value? My purpose is to have a form with two submit buttons associated with different actions. If the two submit buttons have the same value I can do something like this in the controller:
```
public function store(Request $request)
{
    switch ($request->input('buttonsName')) {
        case 'save':
            // Save model
            break;

        case 'delete':
            // Preview model
            break;
    }
}
```

**Comment by matthewkris** [comment]
Did you figure this out? I'm having the same issue.

**Comment by rudiedirkx** [comment]
The form builder can't do this. You should just add HTML `<button>`s to the form, and the values will be sent. The form won't read/validate/return them, but they are in `$request`, so the above `switch` should work.

**Comment by R1Daneel** [comment]
@rudiedirkx To send a value depending on the button clicked I should use some js code. Having two submit buttons with the same name make everything simpler

**Comment by matthewkris** [comment]
I ended up splitting the form and adding a link right to the blade template:

```
{!! form_start($form) !!}
{!! form_rest($form) !!}
<a class="btn btn-primary" href="{{ url()->previous() }}">Cancel</a>
{!! form_end($form) !!}
```

**Comment by R1Daneel** [comment]
@matthewkris with that solution the user is able to open the link into another tab which could be an undesired behavior like in my case.

**Comment by rudiedirkx** [comment]
Just use buttons. Browsers already work like this.

```
<button name="submit" value="do_this">Do this</button>
<button name="submit" value="do_that">Do that</button>
```

No need for JS. Be careful with the ENTER-submit though. That will take the first submit button's name & value.

----

@matthewkris I do that too, with almost all my forms. Usually I print the submit button and such links in a separate div:

```
form_start($form)
form_unless($form, ['submit'])

<div class="form-actions">
    form_row(form.submit)
    <return link>
    <other stuff>
</div>

form_end($form)
```
