### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by Anisi** [kristijanhusak/laravel-form-builder#564]
Hello
Running `php artisan package:discover --ansi` command without generating `APP_KEY` before that, causes this error:
`No application encryption key has been specified`
I realized that it is because of this code in the `FormBuilderServiceProvider`'s boot method:
```php
$form = $this->app['form'];

        $form->macro('customLabel', function($name, $value, $options = []) use ($form) {
            if (isset($options['for']) && $for = $options['for']) {
                unset($options['for']);
                return $form->label($for, $value, $options);
            }

            return $form->label($name, $value, $options);
        });

```
Why should this code be here?
The problem with auto-discover has been solved in the #449 issue, but there is the same problem by running this commands that disabling auto-discovery doesn't affect them:
```bash
php artisan cache:clear
php artisan view:clear
```

**Comment by rudiedirkx** [comment]
Macros are created in the service provider. Where else? It's weirder that it needs the app key.

Why would you not create an app key? This seems unimportant.
