### ISSUE TITLE
"step" float attribute in German locale rendered with comma

### ISSUE THREAD

**Issue by cweiske** [kristijanhusak/laravel-form-builder#565]
When configuring PHP to use the German locale with `setlocale(LC_ALL, 'de_DE.UTF-8');`, a `step` attribute for a `type=number` field gets rendered with a comma instead of a dot:

```
$this->add('name', 'number', ['attr' = ['step' => 0.1]]);
```

gets rendered as:

```
<input type="number" step="0,1">
```

This obviously breaks browsers, since only dots are allowed in that attribute.

The source of the problem is `FormHelper::prepareAttributes()`, which simply converts the option value to string, and PHP outputs a float `0.1` as string `0,1`.

----

A simple solution is to use a string attribute value:
```
$this->add('name', 'number', ['attr' = ['step' => "0.1"]]);
```

Is this the correct solution, or should the form builder should work under all locales with float attributes?

**Comment by rudiedirkx** [comment]
Your solution is correct. Attributes are strings, so to be sure, make them strings.

But it's also kind of a form builder bug. I wouldn't know how to fix it though. All attributes are cast to string somewhere. And every casting makes it `"0,1"`..?

**Comment by rudiedirkx** [comment]
`number_format($num, X, '.', '')` would do it. BUT how many decimals (X)? For which attributes? String attributes are safer =)
