### ISSUE TITLE
Provide a method indicating if a form was disabled

### ISSUE THREAD

**Issue by knnnrd** [kristijanhusak/laravel-form-builder#569]
Calling `\Kris\LaravelFormBuilder\Form::disableFields()` disables all the fields, but there is no way to tell if a form is completely disabled after the fact.

This would be useful to us because we re-use the forms on our "show" pages by disabling them. The "edit", "create" and "show" pages all share the same partials. Sometimes these disabled forms need some custom display logic only on the show page.

**Comment by rudiedirkx** [comment]
How would you use that?

`$form->getDisabledFields()` (array) or `$form->allFieldsDisabled()` (bool) or `$form->howManyFieldsDisabled()` (int)?

PRs welcome.

**Comment by knnnrd** [comment]
For our use case this would be best:
```php
\Kris\LaravelFormBuilder\Form::allFieldsDisabled: bool
```

When I have some spare time I will try to submit a PR but I can't make any promises when that will be.
