### ISSUE TITLE
Multiple error messages on 'choice' type

### ISSUE THREAD

**Issue by huglester** [kristijanhusak/laravel-form-builder#57]
For example I use this:

```php
            ->add('active', 'choice', [
                'choices' => [1 => __('btn_yes'), 0 => __('btn_no')],
                'selected' => true,
                'expanded' => true,
            ])
```

And get these:
The active field must be true or false.
The active field must be true or false.
The active field must be true or false.

Am I missing something?

**Comment by kristijanhusak** [comment]
No, you're not missing, I missed it. You get the error 3 times because each choice renders 1, and 1 is globally for all choices. I forgot to disable showing errors for each choice. Will fix it soon, thanks for reporting.

**Comment by huglester** [comment]
No problem. I am trying to integrate this form package into my workflow, and just try to solve problems when I meet them :)

Very much like it!

**Comment by kristijanhusak** [comment]
I fixed it, do a composer update :) 
These error messages might not work in some situations, because in background it's relying on Laravel validator, and for example validating arrays does not work as it should be. Regular fields should work fine :)

If you notice some other issues, please report.
