### ISSUE TITLE
something wrong with chinese label name.

### ISSUE THREAD

**Issue by ChenRuihua** [kristijanhusak/laravel-form-builder#570]
It works when I use English for label name.
![Snip20191224_4](https://user-images.githubusercontent.com/46486133/71416236-8ec02e80-269a-11ea-93e2-0128ac628d25.png)

But It will lost the label name when I use Chinese for the label name. 
please look at the picture.
![Snip20191224_3](https://user-images.githubusercontent.com/46486133/71416237-8f58c500-269a-11ea-94e3-7d9ed0948d24.png)

@kristijanhusak

**Comment by ChenRuihua** [comment]
fixed. set the label value will fix this problem.
![Snip20191224_5](https://user-images.githubusercontent.com/46486133/71417530-c8943380-26a0-11ea-9935-55ab67fb052e.png)

**Comment by rudiedirkx** [comment]
The machine name (the first argument) must be something simple that PHP understands. Only `a-z0-9_-` is best.
