### ISSUE TITLE
 dynamic value for cutom rule

### ISSUE THREAD

**Issue by capetrel** [kristijanhusak/laravel-form-builder#571]
Hi, i need to use a "digits_between" validation rule with dynamic data store in database. i had try the "model" and "data" key but i have an error after submiting the form. on create i got the data but after submit, the data are null. I try many solutions, i don't know is this an issue with laravel validation or with the form builder

**Comment by capetrel** [comment]
How stupid i am, ignore this issue, i passed the data to the formbuilder in the create method, but forgot to pass them in the store method.

**Comment by rudiedirkx** [comment]
That's often the souce of errors. They should be exactly the same. For collection validation too. And more.
