### ISSUE TITLE
How to add div row between fields and buttons

### ISSUE THREAD

**Issue by mikeerickson** [kristijanhusak/laravel-form-builder#58]
Assuming I have a setup like below, curious how to create a new 'row' between last field and buttons

<pre>
...
			->add('email', 'text', ['label' => 'EMail:'])

			->add('Save', 'submit', ['attr' => ['class' => 'btn btn-primary']])
			->add('Cancel', 'submit', ['attr' => ['class' => 'btn']]);
...

</pre>

**Comment by kristijanhusak** [comment]
You can do it only in views if you split the form by using `form_start`, `form_row`, and `form_end`. Then you can do anything in the between. There is no way to add some custom html through the form class.

**Comment by mikeerickson** [comment]
@kristijanhusak OK, thanks for reply.  Figured out a "better" way to do it via CSS so I am happier with it now :-)
