### ISSUE TITLE
What's the purpose of the `Form::exclude` method ?

### ISSUE THREAD

**Issue by yaquawa** [kristijanhusak/laravel-form-builder#581]
I didn't see any benefits that can get from the `Form::exclude` method.

By calling this method, the form won't render the fields in the exclude list, but it will still check the rules of the fields in the exclude list, which don't make any sense for me. Why not just using the `Form::remove` method instead ?

Can anyone explain me the usage of the exclude method?

**Comment by rudiedirkx** [comment]
I've never used it. I don't know it.. Don't think about it =) If it's not in the way, fuggetaboutit.
