### ISSUE TITLE
Child Form Validation Not Accounted for

### ISSUE THREAD

**Issue by zlanich** [kristijanhusak/laravel-form-builder#583]
If you apply rules inside a form class, then use it as a child form, the validation of the child forms does not run at all. I've tried using methods like `$parentForm->getField('child')->getForm()`, etc and haven't had full success in validating all nested forms (especially collections of child forms).

Is this known to be a supported feature?

**Comment by rudiedirkx** [comment]
Child forms should validate fine. They do for me. You can exactly see which fields/attributes will be validated (and accepted for `getFieldValues()`) with `$form->getAllAttributes()`. It should return something like

```
Array
(
    [0] => log
    [1] => translations.1.from
    [2] => translations.1.to
    [3] => translations.2.from
    [4] => translations.2.to
)
```

That's a form with a collection field with child forms.

Part of child form validation is kinda broken though. Validations that reference another field from a child form, won't take the child form namespace into account, so they might always pass or always fail. But the validation still runs.

**Comment by zlanich** [comment]
After some refactoring, this does appear to work. I'll look further into it, but before, I was getting one of two outcomes:
1. Validation wasn't running at all on children (may have had to do with my `empty_row` & `prefer_input` settings)
2. Validation was running, but resulting errors were coming back without the hierarchy, so the fields didn't know what errors belonged to what field. ie.
```
Array
(
    [0] => log
    [1] => from
    [2] => to
)
```
If this happens again, I'll add to this thread, but I "think" it's working now. 

Referencing some of my other issues, the most confusing part is how erratically the form behaves with different combinations of settings. A lot of times it doesn't throw an error with an incompatible combination of settings, but the form silently fails or does something really wild. I think it might be best to check for things like "if using `prototype` & `empty_row = false`  & `prefer_input = false`", throw an error that indicates that if you're using `empty_row = false` and using JS to add the first empty row, that  `prefer_input` has to be true. Otherwise, you get erratic behavior where the first collection item is completely ignored. Most of this stuff is not documented well or at all, so it's very difficult to dig through the code and understand how it's supposed to work. Thoughts?

**Comment by rudiedirkx** [comment]
I agree it's not documented well. I invite you to update the docs. It's fresh in your mind. Also a _Tips & tricks_ (or maybe better _Pitfalls_) docs page might help for such complicated settings. I'm not a fan of throwing config errors unless they're destructively incompatible, which these are not.

**Comment by zlanich** [comment]
I have no problem contributing to the docs, but I don't feel like I fully understand the inner workings of this library enough to do so yet. I've spent a TON of time digging through this lib and the previous author's dependency lib, and I'm still trying to wrap my head around the intended behavior in a lot of cases. For example, I have no idea what the actual intended purpose of `prefer_input` is, and didn't even know it existed until recently. I only have a general idea of what it seems to do in some scenarios.

This is (IMO) the only usable form lib for Laravel right now, and I intend on continuing to use it, and will likely contribute to it, but despite my ~10yrs of development experience, I may still need to talk more with those who have more experience with the lib before I start writing documentation for it 😃.

I'll keep playing with it, and after I'm done with the 2 projects I'm using it in right now, I should be able to step back and try to figure out what seems to be [un|under]documented and help out.
