### ISSUE TITLE
HTML Attributes Stripped on Collection

### ISSUE THREAD

**Issue by zlanich** [kristijanhusak/laravel-form-builder#584]
I'm noticing in at least one case, that some/all of my child form HTML attributes are getting stripped from the markup. Before/After shots & details:

Form Class:
![strike-child-form](https://user-images.githubusercontent.com/1522665/74080090-38227000-4a0e-11ea-870a-3483c98eb4a0.png)

Prototype Only:
<img width="1680" alt="attr-before" src="https://user-images.githubusercontent.com/1522665/74080071-1628ed80-4a0e-11ea-9601-ee8b3f3ceb8c.png">

After Saving and Rendering Collection:
<img width="1679" alt="attr-after" src="https://user-images.githubusercontent.com/1522665/74080068-15905700-4a0e-11ea-8448-c50c28d969cc.png">

I'm on v1.22.0
I've updated all of templates.
I've tried commenting out any collection/field-related class overrides I have.

UPDATE: Semi-False Alarm. It appears adding a `rules => 'max:3'` to the collection field completely messed up the form. My intent was to have a max of 3 children, but evidently that doesn't work. I'll leave this here/open until someone sees it in case this is not intended.

**Comment by rudiedirkx** [comment]
`max:3` on a collection breaks attributes from unrelated fields?? That still sounds kinda like a bug kinda.

Do you know about `class_append`? Use it instead of `class` to add custom classes, not overwrite all defaults.
