### ISSUE TITLE
Manipulate form output

### ISSUE THREAD

**Issue by louiscoetzee** [kristijanhusak/laravel-form-builder#589]
I am planning on using this in an upcoming project, I've read the docs but have failed to determine how I would be able to manipulate the output to build for example below: (how can I manipulate the html/bootstrap output to build a form like this?)

first_name | last_name (2fields)
id_number
country | province | city (3fields)
etc_field
etc_field

**Comment by rudiedirkx** [comment]
Print exclicit form start/end and fields in the page template, or overwrite the form template.

[View helpers in the docs.](http://kristijanhusak.github.io/laravel-form-builder/form/viewhelpers.html)

`$this->setFormOption('template', 'my/custom/form-template');` for a custom form template. Copy [`form.php`](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/views/form.php) for examle.
