### ISSUE TITLE
_token field is empty

### ISSUE THREAD

**Issue by thanhtung2693** [kristijanhusak/laravel-form-builder#590]
Hi,
I'm having an issue that my _token hidden input doesn't have value.
If I remove the package and use only laravelcollective/html, the _token field did have value. Seems like something's wrong with session.
My route is already used "web" middleware.

Laravel version: 6.12.

Thanks

Edit: Look like the issue comes from the customLabel macro from FormBuilderServiceProvider:87

**Comment by rudiedirkx** [comment]
> Edit: Look like the issue comes from the customLabel macro from FormBuilderServiceProvider:87

That makes little sense to me. Why do you think so? There's no token field in there. The html package prints the token field in the form start. You'll have to debug that.

**Comment by thanhtung2693** [comment]
Sorry but I've spent hours to debug but still don't know why when calling `$form = $this->app['form'];` (FormBuilderServiceProvider:85) :(, seems like this reset all session values.
When I remove that line along with customLabel macro, my form works as expected.

**Comment by rudiedirkx** [comment]
I don't get it either. Maybe it's a package conflict, or the service provider order, or the middleware other, etc. Is the `laravelcollective/html` service provider auto loaded? Before or after the form builder's service provider?

**Comment by thanhtung2693** [comment]
> I don't get it either. Maybe it's a package conflict, or the service provider order, or the middleware other, etc. Is the `laravelcollective/html` service provider auto loaded? Before or after the form builder's service provider?

Yeah look like HtmlServiceProvider run after FormBuilderServiceProvider
