### ISSUE TITLE
change rows in textarea 

### ISSUE THREAD

**Issue by thanhtungka91** [kristijanhusak/laravel-form-builder#595]
the form has a textarea but the rows default is 10 so i would like to know how to change row value?
```
->add('name', Field::TEXTAREA, [
                'label' => 'labelnbame',
                'rules' => 'required',

            ])
      
``

**Comment by rudiedirkx** [comment]
That's an attribute, so change it:

    ->add('name', Field::TEXTAREA, [
        'attr' => ['rows' => 4],
    ])
