### ISSUE TITLE
form_close helper and display/hide some parts of form

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#60]
@kristijanhusak 
I have MainForm and 4 form inside. I set it to view by form_row but...
one form is depends from some variable state. This form should be display or not. 
Unfortunately when I use form_close all not display earlier forms are printed.

I need print 

```
// pseudo code
form_row(form1);
from_row(form2);
if(foo==bar)
form_row(form3) ;
```
and of course have end form mark.

In controller I can remove form based on this variable. But it's impossible not print only?

**Comment by kristijanhusak** [comment]
form_end($form) by default calls first form_rest, and then closes the form. If you do not want to call form_rest, pass false as second param to form_end, like this:

form_end($form, false)

More info [here](https://github.com/kristijanhusak/laravel-form-builder/blob/master/README.md#usage-in-views)

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
Thanks,
how can I add field to child form from parent form or controller?

I need add some fields based in param from controller. Tried:
```
// in contorller
$form->getField('childForm')->add(); 
// in main form
$this->getField('childForm')->add('field','type');

```

I have error
```
Call to undefined method Kris\LaravelFormBuilder\Fields\ChildFormType::add()
```

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 

This should work:
```php
$form->getField('childForm')->getForm()->add();
```

I'm just not 100% sure if it will namespace it properly (add child_name[name]), so please check it, and if not working let me know.

**Comment by jaroslawziolkowski** [comment]
I tired from controller and from mainForm. No errors but also no display fields. When I debug object, field is added but probably .

I need call to method setAttributesList (main method) and
```
 this->add...
```

i  this method.

**Comment by kristijanhusak** [comment]
Thanks, I'll check it out and let you know when it's fixed.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
Did you removed template option in configuration?
I use 
```
$this->add('foo','text',[
'label'=>'bar',
'template'=>'fields.text_add'
]);
```
in resources/views/fields directory is text_add.php I also tried with text_add.blade.php but standard is template is used.

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 
I didn't removed it, it was just bugged for child forms. I fixed it now.
Also, i set up adding forms to child form, you can call any method on child form like on regular form, for example:

```php
$form->getField('child_form')->add('name', 'text');
```

Just do a composer update :)

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 
Did you manage to solve this? Can it be closed?

**Comment by jaroslawziolkowski** [comment]
Yes, it works. 

Thank you.
