### ISSUE TITLE
Customize protype Collection

### ISSUE THREAD

**Issue by Djomobil** [kristijanhusak/laravel-form-builder#603]
Hello, 

I'm using a subForm with a CollectionType

I'm trying to custom the prototype.
Can you give me the best way to do this ?

```php
->add('articles', 'collection', [
                'type' => 'form',
                'template' => 'orders.forms.articles',
                'options' => [    // these are options for a single type
                    'class' => ArticleForm::class,
                    'label' => false,
                ],
                'label' => false
            ]);
````

```php
class ArticleForm extends Form
{
    protected $resource = 'articles';

    public function buildForm()
    {
        parent::buildForm();

        $this
           //TODO: Multiple file or dropzone
            ->add('name', "text", [
                'rules' => 'required'
            ])
            ->add('type', 'select', [
                'choices' => ['Post', 'Page'],
                'empty_value' => '== Select Type ==',
            ])
            ->add('website_id', 'entity', [
                'class' => Website::class,
                'property' => 'url',
                'attr' => [
                    'class' => 'select2'
                ],
                'label' => 'Website'
            ])
            ->add('words', 'number', [
                'default_value' => 2000
            ])
            ->add('price', 'number', [
                'default_value' => 2000 * 0,2
            ]);
    }
}
```

Thank a lot,
Djomobil

**Comment by rudiedirkx** [comment]
What does "custom the prototype" mean? What are you trying to achieve? What doesn't work? What happens instead? Etc.

**Comment by Djomobil** [comment]
I would like customize de the render when i click **"+ Article"**

```php
<div class="card-body">
      <div class="collection-container" data-prototype="{{ form_row($form->articles->prototype()) }}">
           {!! form_row($form->articles) !!}
      </div>
</div>
```

i woud like replace this : 

```html
data-prototype="{{ form_row($form->articles->prototype()) }}
```

with custom i dont know how can i override this.
When i've 2 article the render isnot user friendly :

![View the render](https://i.ibb.co/F5sByDk/Capture-d-e-cran-2020-06-04-a-09-47-17.png)

**Comment by rudiedirkx** [comment]
You can override all templates. The form, the form field, the child form, all the child form's fields. The prototype is just 1 empty instance of the collection, so it uses all those fields. More info on overriding templates on https://kristijanhusak.github.io/laravel-form-builder/custom/templates.html

**Comment by Djomobil** [comment]
@rudiedirkx do you have an example for me ?

**Comment by rudiedirkx** [comment]
The default templates are the examples: [`src/views/`](https://github.com/kristijanhusak/laravel-form-builder/tree/master/src/views). Copy one (eg `child_form` or `collection`) to your app views, and tell the form or a field to use it (see docs).
