### ISSUE TITLE
Missing Laravel 8 tag

### ISSUE THREAD

**Issue by sgc-fireball** [kristijanhusak/laravel-form-builder#619]
Missing Laravel 8 tag
@see dev-master composer.json

**Comment by eballeste** [comment]
`composer require kris/laravel-form-builder:master`

**Comment by fredbradley** [comment]
Plus one for this - the above suggestion to use `master` is not ideal

**Comment by kristijanhusak** [comment]
Can someone confirm that master is fully compatible with laravel 8?

**Comment by bhcosta90** [comment]
> Can someone confirm that master is fully compatible with laravel 8?

I'm using laravel form builder in laravel 8, actually I don't have any problem and I use more resources (laravel collection a example)

**Comment by kristijanhusak** [comment]
1.40.0 Version released.
