### ISSUE TITLE
Child forms clickable labels for checkbox

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#62]
When you use child form to label for attribute is added name field. To checkbox also is addes id like name. So for child forms checkbox name is for example
```

<input type="checkbox" name="dataForm[approved] id="approved" />
<label for="dataform[approved]">Approved</label>
```
In id not exists array. In result after click on label checkbox is not selected.

It is possible to solve without javascript? (I know that in html, I mean form-builder)

**Comment by kristijanhusak** [comment]
Yes, there was a bug. I fixed it, do a composer update. Thanks for reporting.
