### ISSUE TITLE
Getting the value of a field when rendering. 

### ISSUE THREAD

**Issue by Nardusgc** [kristijanhusak/laravel-form-builder#622]
Hi, 

I was wondering if it is possible to get the value of a field when rendering, I have a custom template rendering my child forms, but depending on what the value of one of the fields in the child form is the wrapper class needs to change, but I am not sure how to get the values? 

Thank you

**Comment by rudiedirkx** [comment]
You want to set the class in the parent form class? That's where you know all the data, right? So use that. That's much easier than digging into the form's field objects.

Otherwise, use `$form->getField(name)` and `$field->getOption('value')`.
