### ISSUE TITLE
Displaying datetime-local value on modal from database

### ISSUE THREAD

**Issue by Arianis1** [kristijanhusak/laravel-form-builder#623]
Hello, 
I am having trouble displaying the date-time start and end from the database to a modal in mi views. 
This is my event click function, so far the title shows and if I change the type to text, the start and end date shows. 

```
 eventClick: function (event, calEvent) {
                    $('#updateModal').modal('show');
                    console.log(event)
                    $("#id").val(event.id);
                    $("#title").val(event.title);
                    $("#start").val(event.start.format('YYYY-MM-DD HH:mm:ss'));
                    $("#end").val(event.end.format('YYYY-MM-DD HH:mm:ss'));
```

This is the same format that is saved in the Database YYYY-MM-DD HH:mm:ss  

My Storing function is 

```
public function store(Request $request){
        $this->validate($request,[
            'title' => 'required',
            'start' => 'required',
            'end' =>'required',
        ]);

        $event = new Event();

        $event->title = $request->input('title');
        $event->start = $request->input('start');
        $event->end = $request->input('end');

        $event->save();

        return redirect('/fullcalendar')->with('success','Data Saved');
    }
```

My index function is 

```
public function index()
    {
        if(request()->ajax())
        {

            $start = (!empty($_GET["start"])) ? ($_GET["start"]) : ('');
            $end = (!empty($_GET["end"])) ? ($_GET["end"]) : ('');

            $data = Event::whereDate('start', '>=', $start)->whereDate('end',   '<=', $end)->get(['id','title','start', 'end']);
            return Response::json($data);


        }
        return view('calendar.index');
    }
```

**Comment by rudiedirkx** [comment]
This does not seem like a form builder problem. What's your form builder problem?

**Comment by Arianis1** [comment]
I don’t know how to use this site well, I thought I was asking a general
question. I am having problem displaying data from the data base into a
modal form. The values are stored as datetime-local and when I try to
retrieve them from the database, nothing shows up. If I change the type to
text, it shows up. I’m trying to show them as datetime-local so that I can
update them using the datetime-picker.
I understand if this isn’t a site to ask this type of questions, just saw a
similar problem and wanted to ask mine too.

Atleast, Thanks for responding

**Comment by rudiedirkx** [comment]
I don't think you're having a Laravel form builder problem, or even using Laravel. You might be better off at https://stackoverflow.com/ Don't forget all the details. Nobody knows what you're working on if you don't tell them.
