### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by adam-devapp** [kristijanhusak/laravel-form-builder#624]
I've been looking at examples such as:
https://github.com/kristijanhusak/laravel-form-builder/issues/176

I have the child form showing on the main form, but when submitting it complains of an array to string conversion. I can see my sub form is an array of data. Do I need to handle the processing of this separately in the controller? What is the best way to test/extract for child models, so I can have generic controller code.

On my form I have something like this:

```
                        $related_model = $this->getModel()->mysql()->findOrFail($connector_id);
                        $this->add('Repository Details', 'form', [
                            'class' => $this->getFormBuilder()->create(MySQLForm::class, ['model' => $related_model]),
                        ]);
                        break;
```

Along with the other parent fields i.e. 
```
            ->add('label', 'text', [
                'label' => 'Label',
                'rules' => 'required',
            ])
```

The edit and controller code is generic:

```

  public function edit($id, FormBuilder $formBuilder)
    {
        $model = $this->model->findOrFail($id);


        $form = $formBuilder->create(get_class($this->form), [
            'method' => 'PUT',
            'model' => $model,
            'data' => $model->toArray(),
            'url' => route($this->route . '.update', $id)
        ])->remove('save');

        return view($this->bladePath . '.edit', compact('form'))->with(['path' => $this->path, 'links' => $this->links, 'model' => $model, 'metadata' => $this->metadata, 'bladePath' => $this->bladePath, 'route' => $this->route, 'form_booleans' => $this->form_booleans]);
    }


    public function update(Request $request, $id)
    {
        $model = $this->model->findOrFail($id);
        $form = $this->formBuilder->create(get_class($this->form), [
            'model' => $model,
            'data' => $model->toArray(),
        ]);
        
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput($request->except('_token'));
        }
        $model->update($request->except('_token', '_method'));

        return Redirect::route($this->route . '.show', $id)->with('alert-success', 'Successfully updated');
    }

```

**Comment by adam-devapp** [comment]
If not automatic, was thinking something like this:

```


    public function update(Request $request, $id)
    {
        $model = $this->model->findOrFail($id);
        $form = $this->formBuilder->create(get_class($this->form), [
            'model' => $model,
            'data' => $model->toArray(),
        ]);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput($request->except('_token'));
        }

        $values = $request->except('_token', '_method');

        // Extract child data out of form
        $checkSubForm = $form->getFields();
        foreach ($checkSubForm as $label => $class) {
            if (get_class($class) === 'Kris\LaravelFormBuilder\Fields\ChildFormType') {
                $field = $form->getField($label);
                dd($field);

            }
        }

        // Allow main model to complete without trying to write child data
        foreach ($values as $key => $value) {
            if (is_array($value)) {
                unset($value[$key]);
            }
        }
        $model->update();

        return Redirect::route($this->route . '.show', $id)->with('alert-success', 'Successfully updated');
    }

```

Is this heading in the right direction, or there is a more automated way?

**Comment by rudiedirkx** [comment]
I don't know if it's relevant, but you really shouldn't name a field `Repository Details`. That should be a reliable machine name, like `repository_details`. You can give it a pretty label with the `label` option.

Where does the array to string conversion happen? I've no idea from your code...

Providing both `model` AND `data` also seems odd. You normally just do one. Assuming you're editing a model record, you should use `model`. Form fields will be auto filled/linked.

I've never had this problem, so I'm guessing you're doing something odd, but I don't see what yet.

**Comment by adam-devapp** [comment]
Thanks for the update. I've made some changes. I can see it is triggering the linked model via the relation.. But it doesn't seem to update it. The array relates to the related model, writing to the parent model.

```
_method | "PUT"
-- | --
_token | "xxxxx"
id | "2"
label | "Test"
connector_type_id | "1"
anonymise_feed | "0"
database_connection | "1"
data_repository_id | array:4 [▼   "id" => "2"   "data_repository_id" => ""   "database_query" => "TEST for now"   "assessment_query" => "" ]
```

Not sure why it is trying to write the related field to the parent model.

**Comment by adam-devapp** [comment]
From debugging, this is similar to:
https://github.com/kristijanhusak/laravel-form-builder/issues/378

The child form model isn't binding, and shows the parent model on debug. 

I am binding the model to the form prior to inserting on the form. The class is right, just not the model.
```
$related_model = $this->getModel()->connector()->first();
            $model_form = $this->formBuilder->create('App\Forms\DataRepositoryMySQLForm', ['model' => $related_model]);

            switch ($type_id) {
                    case 'MySQL':

                        $this->add('data_repository_mysql', 'form', [
                            'class' => $model_form,
                        ]);

```

**Comment by adam-devapp** [comment]
I've just done a work around in the controller to extract the child data out and handle that seperately. Works. Would be good for future extension releases if you can inject data into the child forms with the build() method, rather than using a Controller.

```
$checkSubForm = $form->getFields();
        foreach ($checkSubForm as $label => $class) {
            if (get_class($class) === 'Kris\LaravelFormBuilder\Fields\ChildFormType') {
                $field = $form->getField($label);
                $subValues = $request->input($field->getName());
                $childModel = $field->getOption('class');
                $childModel->getModel()->update($subValues);
            }
        }

        // Allow main model to complete without trying to write child data (which shows as array data)
        foreach ($values as $key => $value) {
            if (is_array($value)) {
                unset($values[$key]);
            }
        }

```

**Comment by rudiedirkx** [comment]
Wow what no!? That's not acceptable. I don't get it, yet, but that definitely looks like a bug.

Is the problem that the child form class has a wrong `$this->model` for collection items? Or only if it's a child form's child form, like in #378 ? Or something else? Explain it to me like I'm dumb, because I'm dumb.

**Comment by rudiedirkx** [comment]
Child forms in child forms seem to work fine for me (with newest/dev code, not a tag/release).

**Comment by rudiedirkx** [comment]
I remember this, and I don't get it either. It seems the `name` magic in [setupNamedModel()](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Form.php#L1116) messes up the value model for 'form' fields. What I did in my project is override the (base) form class, and empty `setupNamedModel()` to never do that 'name' magic ever.

There's 1 test that breaks, but nothing else, and that test is weird, so I really don't know why it exists.
