### ISSUE TITLE
 how to create a tag wrapper ?

### ISSUE THREAD

**Issue by Cepairda** [kristijanhusak/laravel-form-builder#625]
Hi ! Showed with comments where I need a wrapper

    public function buildForm()
    {
        $resource = $this->getModel();
        $characteristics = Characteristic::joinLocalization()->get();
        $categories = Category::joinLocalization()->with('ancestors')->get()->toFlatTree();
        $categoryChoices = to_select_options($categories);
        //$categoryIds = $resource->categories()->get()->keyBy('id')->keys();
        $controllerClass = get_class(request()->route()->controller);

        $this
            ->add('details[published]', 'select', [
                'label' => 'Опубликовано',
                'rules' => ['required'],
                'choices' => ['Нет', 'Да'],
                'selected' => $resource->getDetails('published'),
                'empty_value' => ' '
            ])
            ->add('details[category_id]', 'select', [
                'label' => 'Основная категория',
                'rules' => ['required'],
                'choices' => $categoryChoices,
                'selected' => $resource->getDetails('category_id'),
                'empty_value' => ' '
            ]);

           / /start - Wrap in div
            foreach ($characteristics as $characteristic) {
                $this
                    ->add('details[characteristics][' . $characteristic->id .'][use]', 'checkbox', [
                        'label' => $characteristic->getData('name'),
                        //'rules' => ['required'],
                        'checked' => $resource->getDetails('characteristics')[$characteristic->id]['use'] ?? null
                    ])
                    ->add('details[characteristics][' . $characteristic->id .'][filter]', 'checkbox', [
                        'label' => $characteristic->getData('name'),
                        //'rules' => ['required'],
                        'checked' => $resource->getDetails('characteristics')[$characteristic->id]['filter'] ?? null
                    ])
                    ->add('details[characteristics][' . $characteristic->id .'][sort]', 'text', [
                        'label' => $characteristic->getData('name'),
                        //'rules' => ['required'],
                        'value' => $resource->getDetails('characteristics')[$characteristic->id]['sort'] ?? null
                    ])
                    ->add('details[characteristics][' . $characteristic->id .'][id]', 'hidden', [
                        'label' => 'Name',
                        'rules' => ['required'],
                        'value' => $characteristic->id,
                    ]);
            }
            / /end - Wrap in div

            $this->add('submit', 'submit', [
                'label' => 'Сохранить'
            ])
            ->formOptions = [
                'method' => ($resource->id ? 'PUT' : 'POST'),
                'url' => ($resource->id
                    ? action([$controllerClass, 'update'], $resource->id)
                    : action([$controllerClass, 'store'])
                )
            ];
    }

**Comment by rudiedirkx** [comment]
1. I would use collections and child forms for a form this complex. Instead of all the `field[$index][subfield]`.
2. You can add all kinds of formatting by editing the form template. See the docs for [form builder templates](https://kristijanhusak.github.io/laravel-form-builder/custom/templates.html) and [form functions](https://kristijanhusak.github.io/laravel-form-builder/form/viewhelpers.html)

**Comment by Cepairda** [comment]
> 1. I would use collections and child forms for a form this complex. Instead of all the `field[$index][subfield]`.
> 2. You can add all kinds of formatting by editing the form template. See the docs for [form builder templates](https://kristijanhusak.github.io/laravel-form-builder/custom/templates.html) and [form functions](https://kristijanhusak.github.io/laravel-form-builder/form/viewhelpers.html)

I don't understand how to do it. There are no examples in the documentation.

**Comment by rudiedirkx** [comment]
There are examples for both parts. [This is about creating a `collection` of `form`s](https://kristijanhusak.github.io/laravel-form-builder/field/collection.html#collection-of-child-forms), and previous 2 links are to customize a form's html output. I always use the 2nd method.

First make the entire form with collections and forms. No templates. Just print the form with `form($form)` Then check if all the fields are there, and if submit still works. Use `$form->getFieldValues()` to get all the values, not `$request`.

Then you can customize/move/wrap the form's html. Use `form_start($form)` and `form_row($form->fieldname)` etc. See the docs.

**Comment by rudiedirkx** [comment]
If the docs are insufficient, but you figure it out anyway, you're very welcome to PR [`gh-pages`](https://github.com/kristijanhusak/laravel-form-builder/tree/gh-pages).

**Comment by Cepairda** [comment]
> Есть примеры для обеих частей. [Речь идет о создании a `collection`of `form`s](https://kristijanhusak.github.io/laravel-form-builder/field/collection.html#collection-of-child-forms) , а предыдущие 2 ссылки предназначены для настройки вывода html формы. Я всегда использую 2-й способ.
> 
> Сначала сделайте всю форму с коллекциями и формами. Нет шаблонов. Просто распечатайте форму с помощью `form($form)`Затем проверьте, все ли поля там, и если отправить все еще работает. Используйте `$form->getFieldValues()`для получения всех значений, а не `$request`.
> 
> Затем вы можете настроить / переместить / обернуть форму html. Использование `form_start($form)`и `form_row($form->fieldname)`т. Д. См. Документацию.
Need a structure like this. Wrap in div inside the loop

        foreach ($characteristics as $characteristic) {
        / /start - Wrap in div

            $this
                ->add('details[characteristics][' . $characteristic->id .'][use]', 'checkbox', [
                    'label' => $characteristic->getData('name'),
                    //'rules' => ['required'],
                    'checked' => $resource->getDetails('characteristics')[$characteristic->id]['use'] ?? null
                ])
                ->add('details[characteristics][' . $characteristic->id .'][filter]', 'checkbox', [
                    'label' => $characteristic->getData('name'),
                    //'rules' => ['required'],
                    'checked' => $resource->getDetails('characteristics')[$characteristic->id]['filter'] ?? null
                ])
                ->add('details[characteristics][' . $characteristic->id .'][sort]', 'text', [
                    'label' => $characteristic->getData('name'),
                    //'rules' => ['required'],
                    'value' => $resource->getDetails('characteristics')[$characteristic->id]['sort'] ?? null
                ])
                ->add('details[characteristics][' . $characteristic->id .'][id]', 'hidden', [
                    'label' => 'Name',
                    'rules' => ['required'],
                    'value' => $characteristic->id,
                ]);
              / /end - Wrap in div
        }

**Comment by rudiedirkx** [comment]
Right... Everything's in the docs. Try something. Don't just ask for help and expect someone else to do it.

**Comment by Cepairda** [comment]
I try, but it doesn't work. It is also not clear how to wrap in a table

**Comment by rudiedirkx** [comment]
You don't "wrap". You just type HTML and use the `form_*` functions to render the form fields:

```twig
{{ form_start(form) }}
<fieldset>
  {{ form_row(form.email) }}
  {{ form_row(form.password) }}
</fieldset>
<fieldset>
  {{ form_row(form.firstname) }}
  {{ form_row(form.lastname) }}
</fieldset>
<div class="actions">
  {{ form_row(form.submit) }}
</div>
{{ form_end(form) }}
```

(That's Twig, because I don't know how Blade works.)
