### ISSUE TITLE
bug in laravel 5.8 with version 1.22

### ISSUE THREAD

**Issue by mr-httdd** [kristijanhusak/laravel-form-builder#626]
This line causes an error when opening the form (`vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Form.php:51`)

since method "e" cannot handle array values (`vendor/laravel/framework/src/Illuminate/Support/helpers.php:607`)

**Comment by kristijanhusak** [comment]
Did you try newer version maybe?

**Comment by mr-httdd** [comment]
unfortunately, I haven't changed the version for more than six months, I can't say for sure, but after rebuilding the composer this week we noticed an error.

After a little digging, I noticed the difference between the assembly before and after, removed the attr, everything worked. Removal was a crutch, I wouldn't like to see this in my project

**Comment by mr-httdd** [comment]
composer

"php": "^7.4",
"kris/laravel-form-builder": "^1.22",
"laravel/framework": "5.8.*",

**Comment by kristijanhusak** [comment]
Are you able to test version 1.30.0 and see if it works?
We had some changes related to form attr here https://github.com/kristijanhusak/laravel-form-builder/commit/789189fb3d5e35f1b075dc1571605be8239e4ffb

**Comment by mr-httdd** [comment]
I can not install version 1.30.0, the composer gives an error about limiting laravel versions

**Comment by mr-httdd** [comment]
looked at your commit 789189f yes indeed these changes and give an error, check for yourself, the e method gets the attribute as an array

`    protected function attributeElement($key, $value)
    {
        // For numeric keys we will assume that the value is a boolean attribute
        // where the presence of the attribute represents a true value and the
        // absence represents a false value.
        // This will convert HTML attributes such as "required" to a correct
        // form instead of using incorrect numerics.
        if (is_numeric($key)) {
            return $value;
        }

        // Treat boolean attributes as HTML properties
        if (is_bool($value) && $key !== 'value') {
            return $value ? $key : '';
        }

        if (is_array($value) && $key === 'class') {
            return 'class="' . implode(' ', $value) . '"';
        }

        if (! is_null($value)) {
            return $key . '="' . e($value, false) . '"';
        }
    }`

просмотрите обработку vendor/laravelcollective/html/src/HtmlBuilder.php:442

**Comment by mr-httdd** [comment]
using method Form::open (provider/laravelcollective/html/src/FormBuilder.php:136)

from which buildFormOptionsForFormBuilder method is not available

it looks like i'm not using your package correctly

**Comment by kristijanhusak** [comment]
Can you check in your `composer.lock` to see which exact version of form-builder you are using?

**Comment by mr-httdd** [comment]
composer.lock = "1.40.0"

**Comment by kristijanhusak** [comment]
Yeah that's the problem. Your version is too big. Use fixed version `1.22`.

**Comment by mr-httdd** [comment]
Thank you so much
