### ISSUE TITLE
choice/select disableb

### ISSUE THREAD

**Issue by Cepairda** [kristijanhusak/laravel-form-builder#627]
How to make disabled conveniently? There is something similar as selected ?

            $this->add('relations[App\Category]', 'choice', [
                'multiple' => true,
                'label' => 'Категории',
                'choices' => $categoryChoices,
                'selected' => [8, 37, 5],
                'disabled' => [4], // ???
                'attr' => [
                    'class' => 'select2bs4 form-control',
                ],
            ]);

**Comment by rudiedirkx** [comment]
'choice' fields make sub fields (the checkboxes) and those can have attributes like normal fields. If you `dump($this->getField('relations[App\Category]'))` after the `add()`, you can see that structure.

**Comment by rudiedirkx** [comment]
Or look at the [`ChoiceType`](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/ChoiceType.php#L99) class to see what options exists.

**Comment by Cepairda** [comment]
> Or look at the [`ChoiceType`](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/ChoiceType.php#L99) class to see what options exists.

I don't see there how to make the Disabled field?

**Comment by rudiedirkx** [comment]
It's not possible with options. You have to add/change attributes after the field was added.

**Comment by Cepairda** [comment]
> It's not possible with options. You have to add/change attributes after the field was added.

please show an example how to do it?

**Comment by rudiedirkx** [comment]
> If you dump($this->getField('relations[App\Category]')) after the add(), you can see that structure.

And then look at the objects and their options and their methods. That's how you learn a package, not from someone else doing that for you.

**Comment by Cepairda** [comment]
> > Если вы `dump($this->getField('relations[App\Category]'))`после `add()`, вы можете увидеть эту структуру.
> 
> А затем посмотрите на объекты, их варианты и методы. Вот как вы изучаете пакет, а не у кого-то, кто делает это за вас.

Why the documentation does not contain how to make the field disabled ?

**Comment by rudiedirkx** [comment]
> Why the documentation does not contain how to make the field disabled ?

Because docs are always incomplete. When you figure it out, you can [make a PR for the docs](https://github.com/kristijanhusak/laravel-form-builder/tree/gh-pages) to help others.
