### ISSUE TITLE
Grouping fields

### ISSUE THREAD

**Issue by mertasan** [kristijanhusak/laravel-form-builder#629]
How can I do the template below with using a  `buildForm()`? 

I know, I can do it using a template. However, I want to do this dynamically on PHP side.

Thanks.

```html
<div class="form-group row">
    <div class="col-lg-4">
        <input>
    </div>
    <div class="col-lg-4">
        <input>
    </div>
</div>
<div class="form-group row">
    <div class="col-lg-4">
        <input>
    </div>
    <div class="col-lg-4">
        <input>
    </div>
</div>
```

![fields](https://user-images.githubusercontent.com/13007665/100046722-cfcc4000-2e21-11eb-8c27-6df63291e75b.png)

**Comment by rudiedirkx** [comment]
All is said in #582. There are infinitely many ways to group fields, and only 1 works for you. That's why you have template powers. Or make a view helper function. Or a view helper template. Or whatever works for you. The form builder can never do this good enough.
