### ISSUE TITLE
multipart data and collection

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#63]
I tried in child form, and normal form. Works same.

When you add field type file, form has
```
 enctype="multipart/form-data"
```
attribute. But if you add file type in collection it not works.

**Comment by kristijanhusak** [comment]
Yes, you are right. I'll fix it soon. Thanks for reporting.

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 
It's fixed. Do a composer update. If it's ok, please close the issue.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
Thank you, reliable as always.
