### ISSUE TITLE
Problem creating a form

### ISSUE THREAD

**Issue by davidperezsantos** [kristijanhusak/laravel-form-builder#633]
When I am creating the form with Laravel 8 it shows me this error:

```
TypeError
Argument 3 passed to Kris\LaravelFormBuilder\FormHelper::__construct() must be of the type array, null given, called in D:\aplicaciones\login\vendor\kris\laravel-form-builder\src\Kris\LaravelFormBuilder\FormBuilderServiceProvider.php on line 65
```

Please I need help immediately

This is what i have done

```
<?php

namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class UserForm extends Form
{
    public function buildForm()
    {
        $this->add('"name', 'text')
             ->add('email', 'email')
             ->add('password', 'password"');
    }
}


 public function create(FormBuilder $FormBuilder)
    {
        $form = $FormBuilder::create(App\Forms\UserForm::class, [
          'method' => 'POST',
          'url' => route('userStore',$this->GetLocaleLanguage())
        ]);

        return view('users.form', compact('form'));
    }
```

**Comment by rudiedirkx** [comment]
Don't do `$FormBuilder::create(...`. That's calling `create()` statically. You want the normal method: `$FormBuilder->create(...`

**Comment by davidperezsantos** [comment]
I keep getting the same error modifying the $ FormBuilder::create(... by the $ FormBuilder->create(..., I don't know what else to show to see the error

***FORM***

<?php

namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class UserForm extends Form
{
    public function buildForm()
    {
        $this->add('"name', 'text')
             ->add('email', 'email')
             ->add('password', 'password"');
    }
}

***CONTROLLERS****
public function create(FormBuilder $FormBuilder)
    {
        $form = $FormBuilder->create(App\Forms\UserForm::class, [
          'method' => 'POST',
          'url' => route('userStore',$this->GetLocaleLanguage())
        ]);

        return view('users.form', compact('form'));
    }


Please I need help immediately

**Comment by rudiedirkx** [comment]
Argument 3 is the form configuration, so that doesn't seem to exist.

    $configuration = $app['config']->get('laravel-form-builder');
    return new FormHelper($app['view'], $app['translator'], $configuration);

Did you publish the package? Do you have a `config/laravel-form-builder.php` file? Does it return an array?
