### ISSUE TITLE
Collection of custom fields

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#64]
Is it possible add support custom fields to collections?

**Comment by kristijanhusak** [comment]
Yes, it's possible, I just tested it. Did you try and had some problems?

**Comment by jaroslawziolkowski** [comment]
My mistake, it works.

What do you think about add new file. To presentation earlier uploaded files?

When you build form to edit something and have upload field. You need also show loaded earlier field with possible add link to remove.

**Comment by kristijanhusak** [comment]
I'm not sure I understand what you need. Please give some example.

If you need to add dynamically some data to collection, you can do it like it is explained [here](https://github.com/kristijanhusak/laravel-form-builder#prototype).

Also, since data binding is done automatically, it will print row for each data. You can customize it like this in view:

```html
@foreach ($form->collectionField->getChildren() as $collectionField)
    <div class="field-container">
        {!! form_row($collectionField) !!}
        <button type="button" class="delete-row">Delete this row</button>
    </div>
@endforeach
```

Hope I helped.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak Probably it's well but:

1. I have form build dynamically and I can't add each row by form_row in view.
2. When I have collection of file type I see 1,2,3 file field. I need 1 file field and list added earlier files. As you know add value to html file input is impossible.

I need result:

```
<label>Files</label>
<ul>
<li>File one <a href="delete">remove</a></li>
<li>File two <a href="delete">remove</a></li>
<li>File ... <a href="delete">remove</a></li>
</ul>
<input type="file" name="files" />
```

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 
You can do something like this:

Form:
```php
<?php

class FileForm extends Form
{
    public function buildForm()
    {
        $this->add('files', 'file', [
            'attr' => ['multiple' => true]
        ]);
    }
}
```

Controller:

```php
<?php

class FileController extends Controller
{
    public function editAction($id)
    {
        $model = Files::find($id);
        $form = $formBuilder->create('App\Forms\FileForm', [
            'model' => $model
        ]);

        return view('view', compact('form'));
    }
}

```

```html
{!! form_start($form) !!}
<label>Files</label>
<ul>
@foreach ($form->getModel()->files as $file)
    <li>{{ $file->name }} <a href="delete">Remove</a></li>
@endforeach
</ul>
{!! form_row($form->files) !!}
{!! form_end($form) !!}
```

**Comment by jaroslawziolkowski** [comment]
Not exactly. I have child form and all child is display by form_row. In this child form are fields text and files type.

Fields are generate dynamically based on url parameters.

In real fields list and types is get from database. I don't know how many, every time. Best solution is form_row for all child form. 
But in this case I can't use your construction in view.

**Comment by kristijanhusak** [comment]
I'm not sure why you can't. It's possible to do the same thing with child forms like this:

```php
form_row($form->childForm->childFormField)
```

Try giving me an example, it's hard to understand because you are really working with complex forms.

**Comment by jaroslawziolkowski** [comment]
Because I need display:

```
form_row($form->childForm)
```
not
```
form_row($form->childForm->childFormField)
```
I can't use separate call form_row for each field. Or you mean use this construct not in my view but in fiie template.

BTW. What template is use for file input, "text"?

**Comment by kristijanhusak** [comment]
I understand. Well you can use custom template like this:
```php
$this->add('image', 'file', [
    'template' => 'fields.img'  // resources/views/fields/img.blade.php
]);
```

Yes, the template is `text`, because it's `<input type="file">`

**Comment by jaroslawziolkowski** [comment]
So, 
I have code
```
$this->add($name,'file',['template'=>'fields.file','label'=>'MyLabel']);
```
in rerosurces/views/fields/file.blade.php is content
```
I'm new  template
```
result is standard file field.

Form main form it works fine. Form child not.

I'm not sure it's important but my main form is in app/Forms and childs forms are in app/Forms/Product directory (of course has well namespace)

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
Now template works well. Please let me know, what variable should I use in field template to get values bind form model? In page view: 
```
$form->getModel()->field
```
in template $this->getModel() not work.

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 
Model is not passed to the fields, only to the main form, because it's not used by default. You can pass it via options like this:
```php
public function buildForm()
{
    $this->add('name', 'text', [
        'model' => $this->getModel()
    ]);
}
```
and in views:
```
$options['model']->field
```

**Comment by jaroslawziolkowski** [comment]
Yes, but option I set in child form. Model I can get in main form. I need set model from main form to child form...

**Comment by kristijanhusak** [comment]
Child form will automatically pull model from main form when created, or you can pass it to the child form like this:
```
class MainForm extends Form {
    public function buildForm()
    {
        $this->add('child_form', 'form', [
            'class' => 'App\Forms\Products',
           'formOptions' => [ 'model' => $modelToPass ],
        ]);
    }
}

class ChildForm extends Form {
    public function BuildForm()
    {
         $this->add('field', 'text', [
             'model' => $this->getModel()
        ]);
    }
}
```

**Comment by jaroslawziolkowski** [comment]
Thanks for your explain. It works. But FYI: if you want use ``` $name ``` to get model value you need do it in form class, because in view (when you use child) name is string with form prefix. For example 
``` childForm[fieldName] ```

**Comment by kristijanhusak** [comment]
You can use `real_name` in views to get name without `[]`, so something like this:
```php
$realName = array_get($options, 'real_name', $name);
$model->{$realName};
```
`real_name` is set only for child forms, thats why it's needed to use `array_get()`.
