### ISSUE TITLE
getFieldValues + disabled fields

### ISSUE THREAD

**Issue by rudiedirkx** [kristijanhusak/laravel-form-builder#645]
`getFieldValues()` ignores disabled fields (which the browser doesn't send), and accepts `null` as its value. It should completely ignore input for disabled fields, and not include them in the output, just like for `static` fields.

PR later.

**Comment by michael-networking** [comment]
One workaround is to just readonly instead of disabled for the field.

**Comment by var2611** [comment]
> `getFieldValues()` ignores disabled fields (which the browser doesn't send), and accepts `null` as its value. It should completely ignore input for disabled fields, and not include them in the output, just like for `static` fields.
> 
> PR later.

Here solution to achive readonly.

->add('amount', Field::TEXT, [
'attr' => ['readonly class' => 'form-control-plaintext'],
'rules' => 'required|max:25',
'value' => $this->getModel()->amount
])

**Comment by rudiedirkx** [comment]
Fixed in e600ea0daed5925adec9cfda0df1a2d0df5d6200
