### ISSUE TITLE
Allow using Illuminate\Validation\Rule

### ISSUE THREAD

**Issue by koichirose** [kristijanhusak/laravel-form-builder#649]
We're currently limited to using validation rules that have a corresponding method in https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/RulesParser.php

Would it be possible to allow using Laravel's validation rules (with `Illuminate\Validation\Rule`) or callable functions in general?
This would also allow for a cleaner syntax instead of using strings.

For example, I'm currently writing this:
```
'rules' => ['required', 'in:'.join(',', $ids)],
```

But I could be writing this:
```
'rules' => ['required', Rule::in($ids)],
```

I looked around and we could check if `$rule` is a callable function here: https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/RulesParser.php#L48 but then I kind of got lost with attributes and I'm not sure how to proceed.

Any help?

**Comment by Eloar** [comment]
Did you consider using form request validation?
https://laravel.com/docs/5.5/validation#form-request-validation

**Comment by koichirose** [comment]
Yes, that's what I'm using now, but I'm mixing Form Request Validation with Laravel Form Builder validation.
It's not a big issue, but it would be nicer to only use Laravel Form Builder validation.

**Comment by rudiedirkx** [comment]
> We're currently limited to using validation rules that have a corresponding method in RulesParser.php

Why? You can use any rule. `RulesParser` is only for converting some Laravel rules into HTML5 validation.

Validating `'rules' => ['required', Rule::in($ids)],` should work fine?

**Comment by koichirose** [comment]
@rudiedirkx it actually works.
I'm not sure what I was doing wrong then, it's been months and I don't remember.

Thank you, closing this!
