### ISSUE TITLE
Hidden Field

### ISSUE THREAD

**Issue by willycornelissen** [kristijanhusak/laravel-form-builder#65]
I was trying to create a hidden field in a form:

public function buildForm()
    {
        $this
            ->setUrl('admin/provacionistas')
            ->add('nome', 'text', 'Nome:)
            ->add('escola_id','hidden',['value' => '1'])

But it did not work:

            <input class="form-control" id="escola_id" name="escola_id" type="hidden">

Somehow, the value tag is not there. 
Is there another way to set a hidden variable in a form?

**Comment by aktiWeb** [comment]
Looks not bad, should work...
Please check all quotes! In your example i miss one after "Nome:"

**Comment by kristijanhusak** [comment]
3rd parameter to `add()` method needs to be array, and to set value you need to use `default_value`. Here's working solution:

```php
public function buildForm()
{
    $this
        ->setUrl('admin/provacionistas')
        ->add('home', 'text', ['label' => 'Nome:'])
        ->add('escola_id', 'hidden', ['default_value' => '1']);
````

**Comment by kristijanhusak** [comment]
I'm closing this since it's probably resolved.
