### ISSUE TITLE
How to add data attribute to form element

### ISSUE THREAD

**Issue by MusheAbdulHakim** [kristijanhusak/laravel-form-builder#654]
I want a form input like this.
`<input data-toggle="touchspin" type="text" >`

I am new to this package but i haven't seen anything related to this in the docs.

**Comment by Eloar** [comment]
use `attr` option for field, like that
```
->add ('tst', 'text', [
    'attr' => [
        'data-toggle' => 'touchspin'
   ]
])
```

**Comment by MusheAbdulHakim** [comment]
Thanks
