### ISSUE TITLE
Readme tutorial seems outdated

### ISSUE THREAD

**Issue by Jepacor** [kristijanhusak/laravel-form-builder#655]
Hello, I am currently trying to set up a form with this package from the first time, and while it seems to do something according to my debug bar, I am unable to display it. Specifically, it seems I have problems with the blade template that is suggested :
![image](https://user-images.githubusercontent.com/54215241/145404176-b45f4d2c-e01a-4572-bab9-7aeff3298495.png)

When pasting this code, I get a "View [App] not found" error : 
![image](https://user-images.githubusercontent.com/54215241/145404440-f2576a37-993d-4af0-8de8-dc92b0931138.png)

By googling around, I think I understand that this "app.php" was something in the older versions of Laravel, and a lot of the solutions online instructed to change it to "layouts.app", or "layouts.master". (In fact, the doc I found outside of the github has been updated to suggest just that : https://kristijanhusak.github.io/laravel-form-builder/overview/quick-start.html ) 

Yet it seems this might have been depreciated as well, as I still get the same error.

Is there something I am missing ? Am I supposed to make the App view myself ? If so, do I need to put something special in it ? I apologize if I am in fact missing something simple, as I am still a beginner to Laravel.

**Comment by Jepacor** [comment]
I found how to fix it on my end. From my understanding, the "app.php" was generated by the Laravel UI component, which used to be included, but now isn't, so the fix was to install the component, create the auth system with the command "php artisan ui vue --auth" and install it. That created a layouts.app which seems to have been the correct view to extend.

I'm honestly unsure if this is _the_ way to make it work or if any auth solution works, or if it's not even an auth solution but just a fitting blade template that was needed, so I'm not comfortable fixing the readme myself, but I still think this should be looked at.

**Comment by Eloar** [comment]
You just should extend your own layout file. It is not necessary to extend any layout file. In my case layout is `default.blade.php`, located in layouts location. So my directive is:
```
@extends('layouts.default')
```
