### ISSUE TITLE
Buttons collection

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#66]
How can I make buttons collection where values from model will be buttons labels?

When I set buttons collection as result I see buttons and for every button label is field name.

**Comment by kristijanhusak** [comment]
By default button type is using a label for name, so this is in template:
```php
<?= Form::button($options['label'], $options['attr']) ?>
```
There are several solutions:

1) Publish views and update button template to something like this:
```php
<?php if ($options['default_value']): ?>
<?= Form::button($options['default_value'], $options['attr']) ?>
<?php else: ?>
<?= Form::button($options['label'], $options['attr']) ?>
<?php endif; ?>
```

2) Create custom button type:

Template: `fields.custom_button`
```php
<?= Form::button($options['default_value'], $options['attr']) ?>
```

Field Class:
```php
use Kris\LaravelFormBuilder\Fields\FormField;

class CustomButton extends FormField {
    public function getTemplate()
    {
        return 'fields.custom_button';
    }
}
```

Form Class:
```php
class MyForm extends Form
{
    public function buildForm()
    {
        // This can be added also in published configuration in config/laravel-form-builder.php
        $this->addCustomField('custom_button', 'App\Forms\Fields\CustomButton');
        $this->add('buttons', 'collection', [
            'type' => 'custom_button',
            'property' => 'name'   // This is pulled from model value , [ ['name' => 'button1'], ['name' => 'button2'])
       ]);
    }
}
```

I would probably go with 1st solution because it's much simpler.

**Comment by jaroslawziolkowski** [comment]
Thank you, I knew that I should change template but not what parameter use as label.

Maybe you can set to documentation all standard variables available in templates? Probably it will be useful for more people.

**Comment by kristijanhusak** [comment]
Yeah I planned to do that, just didn't have time. Will do it when i catch up.
