### ISSUE TITLE
i need new function for add div tag in my form

### ISSUE THREAD

**Issue by esadeghi942** [kristijanhusak/laravel-form-builder#666]
hi thank you for your help
i changed main library and add row class in form tag and use col-* class in wapper option but  in some where i need to add this query in form builder

    $this->addTag('div', class="w-100",$innerText);

to push other inputs to next line or add some title in my form
Is it possible?

**Comment by matthewkris** [comment]
Look into the static field type. This allows you to add any static html to your form.
