### ISSUE TITLE
datetime-local from model

### ISSUE THREAD

**Issue by nikkiii** [kristijanhusak/laravel-form-builder#67]
When using the datetime-local type and importing values from a model, it sets the field value to something like `2015-04-23 19:29:00` instead of the required `2015-04-23T19:29:00`, probably a simple fix. If I can find where it populates values off models, I'll attempt to fix it and create a pull request.

This seems to be an issue that might be out of your control, though.

**Comment by kristijanhusak** [comment]
I'm not sure, but I think that datetime-local input type always puts value depending on the locale on the client, similar to `type="date"`, and it can not be changed. Never really used it because of the bad support http://caniuse.com/#search=datetime

**Comment by nikkiii** [comment]
In the W3 reference it lists the value as the required format I state in the initial issue: http://www.w3.org/TR/html-markup/input.datetime-local.html#input.datetime-local.attrs.value

The application I'm using it for doesn't particularly need good support for Safari/Opera, so I guess I'm stuck on this one. A workaround is using Javascript to automatically change the format on load, as it seems like this package simply converts it to an array, which will use Carbon's default toString, and I don't think there's a way to override that just for this.

**Comment by kristijanhusak** [comment]
You can use [Accessors](http://laravel.com/docs/5.0/eloquent#accessors-and-mutators) to retrieve right format from model. Something like this:
```php
public function getPublishedAtAttribute()
{
    return $this->publishedAt->format('YY-MM-DD') .'T'.$this->publishedAt->format('HH:MM:SS');
}
```
I didn't tested the code above, but something like that should work out.

**Comment by kristijanhusak** [comment]
@nikkiii did you manage to set it up?

**Comment by nikkiii** [comment]
I just used Javascript to reformat it for now. I just thought of a new solution though, you can set Carbon's default date format right before rendering the form to the required format.

This is done by the following code:

```php
Carbon::setToStringFormat('Y-m-d\Th:m:s');
```

I'll close this since it's more of a "won't fix" for now, but it may be possible to override the date format for forms with the builder in the future.

**Comment by kristijanhusak** [comment]
Yes, package is using laravels form model binding when possible. It does custom binding only for collections and multiple choices fields.
