### ISSUE TITLE
Dymanic form field generation - prototype validation problem

### ISSUE THREAD

**Issue by mojbenzcar** [kristijanhusak/laravel-form-builder#68]
https://github.com/kristijanhusak/laravel-form-builder#prototype 
After validation if validation fails only default form visible. All fields generated by javasript Add More button not regenerating. Is there any solution ?

**Comment by kristijanhusak** [comment]
No, it's not possible to handle that kind of issue, because fields were added by js, and not retreived after failed validation.

**Comment by kristijanhusak** [comment]
@mojbenzcar 
This is fixed in the latest release (1.4.10). It collects old input like other fields, so all collection entries should be returned.

**Comment by mojbenzcar** [comment]
@kristijanhusak Thank you :+1: )
