### ISSUE TITLE
v1.50 breaks field type collection

### ISSUE THREAD

**Issue by fureszk** [kristijanhusak/laravel-form-builder#685]
Sorry for not being more precise, but I get the following error message every time I try to use field of type "collection". Works just fine in v1.40.

`Argument 2 passed to Kris\LaravelFormBuilder\Fields\CollectionType::formatInputIntoModels() must be of the type array, null given, called in /var/www/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/Fields/CollectionType.php on line 104`

**Comment by rudiedirkx** [comment]
It's only `null` if there's no input from the database. Are you building the form correctly? Make sure the field value is always an array or collection. Usually that's implicit, from the form's `model`. Your value is apparently `null`, which is odd. Make sure you build the form on the GET page the same as for validation on the POST page, with the same `model`.

**Comment by rudiedirkx** [comment]
I released 1.51 where this scenario is fixed, but you're still doing something wrong.

**Comment by fureszk** [comment]
Wow, that was pretty quick and pretty rude. I will separate an example to prove you wrong.

**Comment by fureszk** [comment]
In the meantime, would you please let me know how it is possible that what I do incorrectly (by your opinion) works perfectly with 1.40 but not with 1.50?

**Comment by rudiedirkx** [comment]
It was wrong in 1.40 too, but it didn't break then. Sometimes bug fixes break existing code. I don't know the exact change between 1.40 and 1.50, and I don't even know if my assumption is right, but the only way I know the field value is `null` is if you're doing something wrong. Do you build the POST form the exact same way as the GET form?, with the same `model` and data and options etc?
