### ISSUE TITLE
Please change CHANGELOG and Releases

### ISSUE THREAD

**Issue by ukeloop** [kristijanhusak/laravel-form-builder#688]
Please change CHANGELOG and Releases. We can't check CHANGELOG when the package is upgraded.

**Comment by rudiedirkx** [comment]
CHANGELOG hasn't been updated in forever. That's not useful anymore. I don't know what "Releases" is. You can always use Github's tag diff to see changed code between releases. For example from 1.40 to 1.51.1: https://github.com/kristijanhusak/laravel-form-builder/compare/1.40.0...1.51.1

**Comment by ukeloop** [comment]
Many people don't want to see the commit log when minor updates are made to the library.

Often check https://github.com/kristijanhusak/laravel-form-builder/releases

**Comment by rudiedirkx** [comment]
That's understandable. But CHANGELOG isn't useful anymore. Are you going to write up all the releases since 1.20? I'm not.

I thought Releases and Tags were the same.... I'll create Releases for 1.50 and 1.51.
