### ISSUE TITLE
Readonly option or field type

### ISSUE THREAD

**Issue by hackel** [kristijanhusak/laravel-form-builder#69]
I often have forms where I want to display a read-only field for reference only.  It would be nice if there was a read-only option or specific field type that would just display the value without an actual input field.  I think an option might be preferable so that it can be used on any field type.

I know there are custom field types, and that is what I am about to create for my current project, but I am suggesting a more general solution.

**Comment by kristijanhusak** [comment]
You could maybe use regular input with **readonly** property, and do some styling with css to remove borders and stuff. Anyway, thanks for idea, i'll look into it.

**Comment by kristijanhusak** [comment]
@hackel 
This field type is added in the latest release (1.4.10), type `static`. Check the docs in [this section](https://github.com/kristijanhusak/laravel-form-builder#field-customization) for more info.

**Comment by hackel** [comment]
Brilliant, keeps getting better and better!
