### ISSUE TITLE
Select option for null values

### ISSUE THREAD

**Issue by nicja** [kristijanhusak/laravel-form-builder#695]
When creating a Select form element, how can I add an option for null values? For example I want to select all model instances for which a certain field is null.

Is this possible?

**Comment by rudiedirkx** [comment]
Isn't that what Laravel's default enabled `ConvertEmptyStringsToNull` middleware does? And `SelectType` option `empty_value` (see `views/select.php`).

**Comment by nicja** [comment]
From what I can tell you can use an empty value to either ignore the field or use it to filter where the field is null. I want both of those options. Not sure if that is possible?

**Comment by rudiedirkx** [comment]
HTML forms can't send `null`. They also can't send numbers or empty arrays etc. They can send empty strings, and you can decide what to do with that. That's not up to the form builder, but the dev. I usually don't filter if it's an empty string, and have explicit values `-1` and `-2` mean something specific, like filter on empty, or filter on non-empty. Not the form builder's job.
