### ISSUE TITLE
Feature request: Add conditional field

### ISSUE THREAD

**Issue by mithublue** [kristijanhusak/laravel-form-builder#697]
Hi, 
The form is very promising but I am missing a feature in it. That is conditional field. Which means a field's appearance will be dependent to another field's input given by the user.

Would it be possible ?

**Comment by rudiedirkx** [comment]
What do you mean "a field's appearance"? The appearance happens before input, doesn't it?

Do you mean interactive/javascript? This package doesn't do that. More details and PR always welcome though.

**Comment by mithublue** [comment]
For example there is a checkbox A and textarea B. If, A is checked, then B will be visible. It means B is dependent on input of A.

**Comment by rudiedirkx** [comment]
Visible = javascript and css. That's not what this package does. This package just adds the fields and validates them. Custom visibility logic is custom. Just add some JS and CSS after the form is printed.
