### ISSUE TITLE
Compatibility Laravel 9 ?

### ISSUE THREAD

**Issue by martin-lechene** [kristijanhusak/laravel-form-builder#703]
### Compatibility Laravel 9 ?

Holà, 

The package is available for Laravel 8 or 9 ? 

Thank's for your request

**Comment by ukeloop** [comment]
It works in laravel 5.6|^6|^7|^8|^9.

https://github.com/kristijanhusak/laravel-form-builder/blob/ab692f092718458683548dc660b959402f2db573/composer.json#L14-L16

**Comment by martin-lechene** [comment]
Perfect and thanks for info :) !
