### ISSUE TITLE
How to procedurally create form (without class)

### ISSUE THREAD

**Issue by mikeerickson** [kristijanhusak/laravel-form-builder#71]
I have a need to procedurally create the form class

$form = FormBuilder::create(properties);

Is this possible, and if so, is there an example somewhere?

**Comment by mikeerickson** [comment]
Well, looks like the FormBuild::plain method will do what I want (I believe)....

**Comment by kristijanhusak** [comment]
Yes, plain form is used for instantiating empty form which can be used to add fields procedurally. You can add/mofify/remove fields from any form after instantiation.

**Comment by mikeerickson** [comment]
Thx for reply, got it all figured out and implemented as I want it (for now)

**Comment by kristijanhusak** [comment]
Ok, closing this. If you run to problem, open another issue.
