### ISSUE TITLE
Collection of templated form

### ISSUE THREAD

**Issue by zaartix** [kristijanhusak/laravel-form-builder#714]
intro. Thanks for this component, after using symfony it is much easier to use laravel with your component

I have a form named EmploymentSingleForm. It is a collection with prototype feature, to multiply it.
![image](https://github.com/kristijanhusak/laravel-form-builder/assets/503348/6d7d224a-2b74-40d1-89ba-d2a0c987d49e)

But there is some text placements, like on the picture.

In case of single form i may just use template like this:
`<p>Some text before form_row</p>
{!! form_row($form->country) !!}
`

But EmploymentSingleForm used as collection, so tpl looks like this:
```
<div class="collection_wrapper" id="employment_wrapper" data-prototype="{{ form_row($form->employment->prototype()) }}">
 {!! form_row($form->employment) !!}
</div>
```

Is it any way to make template for child of collection?

for example make some component in views/form/component/employment.blade.php
with template like this
`<p>Some text before form_row</p>
{!! form_row($form->country) !!}
`
and render prototype and each item of collection using  that component

**Comment by zaartix** [comment]
hm, it is works simplier that i thought :)

`
$this->add('employment','collection',[
            'type' => 'form',
            'label' => false,
            'options' => [
                'class' => EmploymentSingleForm::class,
                'label' => false,
                'template' => 'form.single.employment',
            ],
        ]);
`
`
<fieldset class="p-4 mb-4 border bg-white">
    <p>Some text before form_row</p>
    {!! form_row($options['children']['country']) !!}
</fieldset>
`

**Comment by rudiedirkx** [comment]
You could also use `static` fields maybe:

```php
$this->add('some_text', 'static', [
    'value' => 'Some text before form row',
]);
```

See [StaticType.php](https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/StaticType.php) for options.
