### ISSUE TITLE
Error: count(): Argument #1 ($value) must be of type Countable|array, Mekongdelta\Slug\Models\Slug given

### ISSUE THREAD

**Issue by minhkhoablieu** [kristijanhusak/laravel-form-builder#716]
Hi. I'm having a problem with ONE TO ONE (Polymorphic). It shows error "count(): Argument 1 ($value) must be of type Countable|array, Mekongdelta\Slug\Models\Slug given" like image bellow.

![image](https://github.com/kristijanhusak/laravel-form-builder/assets/12608657/7c342775-58db-48bb-a577-cf5712af61c4)

**This is my database structure.**
posts
- id - integer
- name - string
 
slugs
- id - integer
- url - string
- sluggable_id - integer
- sluggable_type - string

**This is my buildForm**
![image](https://github.com/kristijanhusak/laravel-form-builder/assets/12608657/7deea3d1-7456-4d7b-8b4f-2dd93e9443d4)

**Trait sluggable and model Post**
![image](https://github.com/kristijanhusak/laravel-form-builder/assets/12608657/c4a524cc-ffa0-4d87-851a-8136dd3c2c9d)

**My environment**
PHP 8.2
Laravel 10.25
"kris/laravel-form-builder": "dev-master",

I don't know where I made a mistake or am missing something, can you help me? 
Sorry for my English.
Thank you very much,

**Comment by rudiedirkx** [comment]
How do you build/create the form? In the controller probably. Do you pass it an existing `model`?

The form builder tries to get the field's value for filling the collection items. That value has to be a countable (array, collection, etc). Your `Post` model of `Sluggable` trait probably has a `slug` getter or relationship that doesn't return a countable.

Several options:

- Rename field `slug` to something that isn't auto-filled from the form `model`
- Explicitly pass the collection field a countable value (`'value`' => $this->model->slugs_items` or something)

**Comment by rudiedirkx** [comment]
If it's a one-to-one relationship, why do you use the `collection` field? Collection is for lists, like if 1 post can have more than 1 slugs.

**Comment by minhkhoablieu** [comment]
> If it's a one-to-one relationship, why do you use the `collection` field? Collection is for lists, like if 1 post can have more than 1 slugs.

Yes, it's a 1-1 relationship, because product has slug, page also has slug, blah blah, So I want to use [Polymorphic Relationships](https://laravel.com/docs/10.x/eloquent-relationships#polymorphic-relationships) to save slugs into a separate table..

**Comment by minhkhoablieu** [comment]
> But if it's a 1-1, why use a collection? Collections are for 1-n. Just use a `text` field, or a child `form` with a `text` field. Collections are for a post's multiple tags, or a user's multiple billing addresses, etc.

oh my. I got it. Thank you
