### ISSUE TITLE
At least one "choice" checkboxes required

### ISSUE THREAD

**Issue by Marcone-Santos1** [kristijanhusak/laravel-form-builder#722]
I have code similar to this:

```php
$options = [
    'choices' => ['en' => 'English', 'fr' => 'French'],
    'choice_options' => [
        'wrapper' => ['class' => 'choice-wrapper'],
        'label_attr' => ['class' => 'label-class'],
    ],
    'expanded' => true,
    'multiple' => true,
    "rules" => "required"
];

$this->plainForm->add('test', 'choice', $options);
```

![image](https://github.com/kristijanhusak/laravel-form-builder/assets/98716688/ba08dfb4-635c-4cb3-bb70-b708a1e22450)

all checkboxes are becoming mandatory, but with ChoiceType's radio, select, required works normally, what would be the ideal correction/code?

Sorry, but I already looked at most of the "issues" and didn't find anything similar

**Comment by ukeloop** [comment]
I think it is possible that the `name` of the cheackbox is not `test[]` due to some factor

**Comment by rudiedirkx** [comment]
`choice` type is broken. It copies all attributes to all children. `ParentType` is weird. We should fix or retire `choice`, but who has the time.

I use https://packagist.org/packages/rdx/laravel-form-builder-extras instead. It defines types `radios`, `checkboxes`, `multiselect`. If you want a normal select, use `select`.
