### ISSUE TITLE
Support for Laravel 11

### ISSUE THREAD

**Issue by michaelLoeffelmann** [kristijanhusak/laravel-form-builder#723]
Are there plans for Laravel 11 support?

**Comment by rudiedirkx** [comment]
#721 but it needs some work. I could merge without working tests, buttt I don't know if it actually works in L11. If you know how phpunit works, you could fix the tests. With 1 codebase for all versions plz.

**Comment by noge075** [comment]
So what is the final conclusion about this? We should use the fork or do you have plans to continue? Thanks for your work!

**Comment by rudiedirkx** [comment]
Someone has to test the Laravel 11 branch. It'd be nice if someone fixed the tests, so Github can test automatically, but nobody seems willing/able. So someone has to test it for real. You can temprarily add it from Github locally, like @laravel-shift said in https://github.com/kristijanhusak/laravel-form-builder/pull/721#issuecomment-1967333796

**Comment by hooman-mirghasemi** [comment]
@rudiedirkx 
check my  [comment](https://github.com/kristijanhusak/laravel-form-builder/pull/721#issuecomment-2067790343)
