### ISSUE TITLE
Form model binding with a collection of child forms

### ISSUE THREAD

**Issue by hackel** [kristijanhusak/laravel-form-builder#73]
I've created a form that is bound to a model, and that works fine.  The form contains a collection of child forms, corresponding to a BelongsToMany relationship in my DB.  When I render the form, each instance of the child form is being filled with the data from the last instance.  E.g.:
```php
$model = [contacts =>
    [name=>name1],
    [name=>name2],
    [name=>name3]
];

$this->add('contacts', 'collection', [
    'label' => false,
    'type'  => 'form',
    'prototype' => true,
    'options' => [
        'label' => 'Contacts',
        'class' => 'ContactForm',
    ],
])

// Is rendered:
form[contacts][0][name] = 'name3';
form[contacts][1][name] = 'name3';
form[contacts][2][name] = 'name3';
```
The relationship itself is working fine, $form->contacts returns the correct data from the DB, and saving the data works just fine as well.  It's just on retrieving it that I am seeing this issue.

This might be related to another issue which I found which I will report after this.  I haven't had time to dig into the code enough to figure out how the form builder is tying into the Illuminate/Html form model binding, but I suspect that is where the issue lies.  Any assistance would be appreciated!

**Comment by kristijanhusak** [comment]
Thanks for reporting. I think i know what's the problem, but not sure. Will check it out tomorrow and let you know.

**Comment by kristijanhusak** [comment]
@hackel I fixed it, do a composer update. Test it out, and if it's fine, please close the issue. Thanks.

**Comment by hackel** [comment]
Yes, this is fixed now.  Thanks for your excellent work!
