### ISSUE TITLE
Child form default_value

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#80]
I try make hidden field with default value in child form.

it child form is added empty field
```php
<?php
$this->add('branch','hidden',['default_value'=>$branch]);
```

in main form

```php
<?php
$this->add('branch','hidden',['default_value'=>$branch]);
```
is added with value. ``` $branch```` in both forms has same value.

**Comment by kristijanhusak** [comment]
You're right. Pushing fix soon.

**Comment by kristijanhusak** [comment]
Ok, fixed. Do a composer update (version 1.4.13). Thanks for reporting.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak Thanks
