### ISSUE TITLE
Many to Many Relationship

### ISSUE THREAD

**Issue by MeeDNite** [kristijanhusak/laravel-form-builder#81]
Hi,
Could you please give us some more Doc about how to set up a child form for Many to Many relationships?

Regards

**Comment by kristijanhusak** [comment]
Hi,

Well, that really depends on the use case. Sometimes many to many is used for simple forms, and sometimes they're complex. What kind of form structure do you need?

**Comment by MeeDNite** [comment]
Thanks for your reply.
I have a Customer Model, a Profile Model and they are in many to many relationship.
Profile table has "Extra fields" for customers (such as address, telephone, etc) and in pivot table I have a value field to hold the profile value.

my first solution was to create a CustomerProfileForm class, and dynamically "add" fields from Profiles db table to it. then add it as a child form to CustomerForm.

The problem is that I cant find default values for each profile.

**Comment by kristijanhusak** [comment]
I don't think you need many to many relationship here. It's enough one to one if you will have only 1 Profile entry per customer, or eventually one to many if you need more entries for some reason. What do you think?

**Comment by MeeDNite** [comment]
in Profiles table looks like this:

![Profiles Table](https://avindemo.ir/milad/profiles.jpg)

pivot table customer_profile: 

![Profiles Table](https://avindemo.ir/milad/customer_profile.jpg)

Which I think is correct.
(I think the name "profile" is confusing)

**Comment by kristijanhusak** [comment]
I'm a bit confused with these data in the tables. Are you trying to create some type of dynamic forms?

**Comment by MeeDNite** [comment]
Yes. I can create the form.

```php
public function buildForm()
    {

        foreach($this->profile->published()->get() as $profile){
            $data=$profile->atbs;
            if($profile->type=='choice'){
                $data['choices'] = $profile->ops;
            }

            //Just in case label isn't set
            $data['label'] = (isset($profile->atbs['label'])) ? $profile->atbs['label'] : ucfirst($profile->name).':';
            // The problem is here! I cant inject either Customer nor Profile to find the value!
            // $data['default_value'] = ??

            $this->add(
                $profile->name,
                $profile->type,
                $data
            );
        }
        parent::buildForm();
    }
```
But in Child form I tried to inject Customer and Profile Classes to find "Value" field of pivot table.

**Comment by kristijanhusak** [comment]
Just create many to many relationship on Profile model: Something like this:
```php
class Profile extends Model {

    public function customer()
    {
        return $this->belongsToMany('App\Customer', 'customer_profile', 'profile_id', 'customer_id');
    }
}
```

And in form call data like this:
```
$this->profile->with('customer')->published()->get()
```

You should have customer data available. Check more in this section of docs:
http://laravel.com/docs/5.0/eloquent#relationships

**Comment by MeeDNite** [comment]
I have done this already.
$profile->customer will return "a collection of all customers related to this customer"
![22](https://cloud.githubusercontent.com/assets/3420425/7272810/0342a43e-e903-11e4-852c-c69fd0335fe1.JPG)

![33](https://cloud.githubusercontent.com/assets/3420425/7272829/230fba40-e903-11e4-9f01-59cb089a9eb9.JPG)

**Comment by MeeDNite** [comment]
In Parent form, I have Customer object (thanks to model binding)

controller:
```php
$customer = $this->customer->findOrFail($id);

		$form = $formBuilder->create('App\Club\Customers\Forms\CustomerForm', [
			'method' => 'PATCH',
			'url' => route('admin.customers.customers.update', $customer->id),
			'model' => $customer,
		]);
```
parent form:
```php
public function buildForm()
    {
        $this
            ->add('first_name', 'text', [
                'label' => 'First Name:',
            ])
            ->add('last_name', 'text', [
                'label' => 'Last Name:',
            ])->add('group_id', 'choice', [
                'label' => 'Group:',
                'choices' => $this->getGroupsList(),
                'empty_value' => '==== Parent ====',
                'multiple' => false
            ])->add('profiles', 'form', [
                //here I can use $this->model to get Customer data.
                // but how to pass it to CustomerProfileForm??
                'class' => $this->formBuilder->create('App\Club\Customers\Forms\CustomerProfileForm'),
            ]);
        parent::buildForm();
    }
```

here I can use $this->model to get Customer data.
but how to pass it to CustomerProfileForm??

**Comment by kristijanhusak** [comment]
Same model should be available on `CustomerProfileForm`. Just try dumping `$this->model` in the CustomerProfileForm `buildForm` method and see if it works.

**Comment by MeeDNite** [comment]
$this->model in CustomerProfileForm is null.
But I managed to pass Customer object to CustomerProfileForm from CustomerForm (parent form) like this:
```php
public function buildForm()
    {
        $this
            ->add('first_name', 'text', [
                'label' => 'First Name:',
            ])
            ->add('last_name', 'text', [
                'label' => 'Last Name:',
            ])->add('group_id', 'choice', [
                'label' => 'Group:',
                'choices' => $this->getGroupsList(),
                'empty_value' => '==== Parent ====',
                'multiple' => false
            ])->add('profile', 'form', [
                'class' => $this->formBuilder->create('App\Club\Customers\Forms\CustomerProfileForm', null, ['customer'=>$this->getModel()]),
            ]);
        parent::buildForm();
    }
```
and use it in CustomerProfileForm like this:
(notice that I used the relationship in foreach loop.)
```php
public function buildForm()
    {

        foreach($this->data['customer']->profiles as $profile){
            $data=$profile->atbs;
            if($profile->type=='choice'){
                $data['choices'] = $profile->ops;
                //here!
                $data['selected'] = $profile->pivot->value;
            } else {
                // and here!
                $data['default_value'] = $profile->pivot->value;
            }

            //Just in case label isn't set
            $data['label'] = (isset($profile->atbs['label'])) ? $profile->atbs['label'] : ucfirst($profile->name).':';

            $this->add(
                $profile->name,
                $profile->type,
                $data
            );
        }
        parent::buildForm();
    }
```

**Comment by MeeDNite** [comment]
Thanks for your Answers :)

**Comment by kristijanhusak** [comment]
Yeah that is also a one solution to this, but model should be available in child forms. I'll check it out anyway.

**Comment by MeeDNite** [comment]
Thanks.
If you needed help on this, Im here.

**Comment by kristijanhusak** [comment]
I just checked it out, the model is null because `buildForm` is called only once, and after that call i'm binding parent model to child one,  without recalling build form. Solution for your problem is just to pass model to the child form like this:
```php
->add('profile', 'form', [
     'class' => $this->formBuilder->create('App\Club\Customers\Forms\CustomerProfileForm', [
        'model' => $this->model
    ]
]);
```

You can do it also this way, maybe a bit cleaner:
```php
->add('profile', 'form', [
     'class' => 'App\Club\Customers\Forms\CustomerProfileForm', 
     'formOptions' => [ 'model' => $this->model ]
]);
```
