### ISSUE TITLE
Suggestion: Form field helper

### ISSUE THREAD

**Issue by FourStacks** [kristijanhusak/laravel-form-builder#82]
Hello

First up, thanks very much indeed for this package - it's already proved hugely useful in my current project and has allowed me to pull off things like user editable forms which I thought were going to be a complete pain to implement.  Awesome work!

One thing that I've thought might be nice to have is helper text for each form field.  For instance if a field requires some explanation it would be nice to be able to have a the field label followed up a block level helper text (either above or below the field itself).  Bootstrap offer support for this sort of thing: http://getbootstrap.com/css/#forms

Just wondered if you had any plans to implement something like this as part of the package core or whether you think that's more of an edge feature that's better implemented by individual devs via template modification?

**Comment by kristijanhusak** [comment]
Hi,

Thanks, I'm glad it works out for you :)

I haven't planned to implement that, because I totally forgot about that option. Will definitely look into it and probably add it as a core feature. Will let you know when it's implemented.

**Comment by FourStacks** [comment]
Great stuff, many thanks!

**Comment by kristijanhusak** [comment]
I added this functionality in latest release(1.4.20). Do a composer update.
You can see example of usage in this section https://github.com/kristijanhusak/laravel-form-builder#field-customization , option `help_block`. If you find any problems with it, please let me know. Thanks for idea.
