### ISSUE TITLE
Repeated field HTML rendering issue

### ISSUE THREAD

**Issue by FourStacks** [kristijanhusak/laravel-form-builder#83]
Hi

There seems to be an issue with the way that repeated fields are rendered.  Basically it would appear that the wrapper closing tags are not being rendered which results in incomplete css.  I've created a gist showing the output from both a single repeat field and two consecutive repeated fields:

https://gist.github.com/FourStacks/ec0903061b63a5fb321a

These were produced with the following form class:

    public function buildForm()
    {
        $this
            ->add('email', 'repeated',[
                'type' => 'email',
                'first_options' => [
                    'label' => 'Email'
                ],
                'second_options' => [
                    'label' => 'Confirm your email'
                ]
            ]);
            ->add('password','repeated', [
                'type' => 'password',
                'first_options' => [
                   'label' => 'Choose a password',
               ],
               'second_options' => [
                   'label' => 'Confirm your password'
              ]
           ]);
    }

The code above is a stripped down version of my actual form for debugging purposes. I haven't made any template changes.  And I'm rendering the form in int's entirety in the view rather than breaking it up in any way.

Sorry I've not managed to find the root cause of this yet but thought I'd mention it first while I'm looking into it.

**Comment by kristijanhusak** [comment]
Hi,

Thanks for reporting. I'll look into it.

**Comment by kristijanhusak** [comment]
I fixed it in latest version (1.4.20), do a composer update. Thanks for reporting.
