### ISSUE TITLE
Repeated form's help text also renders on parent.

### ISSUE THREAD

**Issue by tormit** [kristijanhusak/laravel-form-builder#86]
```php
   $form->add(
                'password',
                'repeated',
                [
                    'first_name' => 'password',
                    'second_name' => 'password_confirmation',
                    'first_options' => [
                        'label' => 'Password',
                        'help_block' => [
                            'text' => 'You don\'t have to fill this field.'
                        ]
                    ],
                    'second_options' => [
                        'label' => 'Confirm password'
                    ],
                ]
            )
```

I would expect help text to be rendered only to the first subelement, but it's also rendered in repeated.php

**Comment by kristijanhusak** [comment]
Thanks for reporting, I'll look into it.

**Comment by kristijanhusak** [comment]
I fixed it, pull the latest dev version.

**Comment by kristijanhusak** [comment]
@tormit 
Is it working?

**Comment by tormit** [comment]
No. It does not.

I removed help block from from repeated template at all.

And I got simplified Foundation5 help block for text field.
```php
<?php if ($options['help_block']['text']): ?>
	<small class="label secondary">
	    <?= $options['help_block']['text'] ?>
	</small>
<?php endif; ?>
```
This HTML is rendered at the first field, but also at the end of repeated field.

**Comment by kristijanhusak** [comment]
Are you sure you got the latest version, and republished the views?

It wasn't working because `help_block` was not put inside `if ($showField)` block. I tested locally and it works fine.

**Comment by tormit** [comment]
Yeah, I might have forgotten to synchronize text field template. Still, I can't see how it's related to text field, because it seems to be repeated widget's issue. I remind, that I removed help block from repeated field's template at all and it's still displaying it at the end on repeated field.
I'll revisit this issue tomorrow.

**Comment by tormit** [comment]
I updated text field template and now it works. Thank you.
