### ISSUE TITLE
Submit button wrapper

### ISSUE THREAD

**Issue by msonowal** [kristijanhusak/laravel-form-builder#89]
How to specify wrappers for submit button?
here is my form code

<?php namespace App\Forms;
use Kris\LaravelFormBuilder\Form;
use App\Models\Publication;

class NewspaperForm extends Form
{
    public function buildForm()
    {
        $publications = Publication::lists('name', 'id');
        $centers = Center::lists('name', 'id');        

        $this->add('publication_id', 'select', [
               'choices' => $publications,
               'empty_value' => '==== Select Publication ===',
               'label' => 'Publication',
               'attr' => ['required']
            ]);
        $this->add('edition_name', 'text', ['attr' => ['required'] ]);
    }
}

and I am using this in the controller to pass into the views

$form = $formBuilder->create('App\Forms\NewspaperForm', [
            'method' => 'POST',
            'url' => route($this->content.'store'),
            'class' => 'form-vertical'
        ])->add('save', 'submit', [                
                'attr' => ['class' => 'btn btn-primary']
            ]
       );
this generates :
<button class="btn btn-primary" type="submit">Save</button>
and creates the save button , so i need a wrapper to fix the position and other issues
i.e I want something like
<div class="form-group">
<button class="btn btn-primary" type="submit">Save</button>
</div>

**Comment by kristijanhusak** [comment]
I added it in the latest release (1.4.21). Do a composer update, and define wrapper options for your button, because by default it's set to false so it does not break BC.

```
->add('save', 'submit', [
    'wrapper' => ['class' => 'btn-wrapper'],
    'attr' => ['class' => 'btn btn-primary']
]);
```
Will create something like this:
```html
<div class="btn-wrapper">
    <button type="submit" class="btn btn-primary">Save</button>
</div>
```

**Comment by dileepmaurya** [comment]
thanks @kristijanhusak its work for me.

**Comment by kristijanhusak** [comment]
Ok, great.
