### ISSUE TITLE
Radio/Checkbox Ids

### ISSUE THREAD

**Issue by FourStacks** [kristijanhusak/laravel-form-builder#96]
Hi @kristijanhusak 

Just wondered if you had any thoughts on the following issue.  So when a group of radio/checkbox elements is created, the id is generated using a combination of choice (basically the label) and the choice key.  In instances where you have choices such as:

    [
        'approve' => "Approve this user's account",
        'decline' => "Decline this user's account"
    ]

we end up with improperly formatted HTML where the ID attribute (and the corresponding 'for' attribute on the label) have white space in them e.g. id="Approve this user's account_approve".  I'm not overly concerned by the invalid HTML but it does make like difficult when trying to select these elements via jquery or in integration/acceptance tests.

Unless I'm missing an option to explicitly set the ID for each choice for the choice field then I was wondering if perhaps it would be better to set the id/for attributes to something more sensible (and valid).

Given that the key for each choice should be unique it should be enough to just use the key as the id/for?  If I'm missing something obvious there though then how about instead adding a method to the ChoiceType class that sanitises the choice label for use in the id.  Something like:

    protected function sanitizeChoiceId($string) {
        //Lower case everything
        $string = strtolower($string);
        //Make alphanumeric (removes all other characters)
        $string = preg_replace("/[^a-z0-9_\s-]/", "", $string);
        //Clean up multiple dashes or whitespaces
        $string = preg_replace("/[\s-]+/", " ", $string);
        //Convert whitespaces and dash to underscore
        $string = preg_replace("/[\s-]/", "-", $string);
        return $string;
    }

Then in buildCheckableChildren method you do something like:

    foreach ((array)$this->options['choices'] as $key => $choice) {
            $id = $this->sanitizeChoiceId($choice) . '_' . $key;

What do you reckon?  Happy to submit a PR if you think it's worth having.  If not I can just change it up for my project via the publishable vendor files.

**Comment by FourStacks** [comment]
Uh, ignore that last bit about changing it only in my own project via vendor assets - that change would need to be made in the core.

**Comment by kristijanhusak** [comment]
Hi @FourStacks ,

Wow, didn't even think about problem like that. Will fix it soon, so it will be transformed to something like this:
```
Approve this user's account => approve_this_users_account
```

**Comment by FourStacks** [comment]
Ha!  No worries - you've done an amazing job with it all in all so there's bound to be a few that slip through the net!

You want to handle this yourself or shall I submit a PR?  Got a version that I've messed with locally so wouldn't be much work to PR it.

**Comment by kristijanhusak** [comment]
I'll handle it myself, you've done enough already only for noticing it :). Will be up soon :)

**Comment by FourStacks** [comment]
No problem, thanks Kris!

**Comment by kristijanhusak** [comment]
@FourStacks 
I fixed it in latest release (1.4.26). Id does not use the label any more, it takes field name. So for example:
```
$this->add('action', 'choice', [
    'choices' => [
        'approve' => "Approve this user's account",
        'decline' => "Decline this user's account"
    ]
]);
```
Produces something like this:
```html
<div class="form-group">
    <label for="action[]" class="control-label">Action</label>

    <input id="action_approve" name="action[]" type="checkbox" value="approve">
    <label class="control-label" for="action_approve">Approve This User's Account</label>

    <input id="action_decline" name="action[]" type="checkbox" value="decline">
    <label class="control-label" for="action_decline">Decline This User's Account</label>

</div>
```
Thanks for reporting.

**Comment by FourStacks** [comment]
Great work - much nicer solution, thanks for fixing it so quickly!

**Comment by kristijanhusak** [comment]
No problem ;)
