### ISSUE TITLE
FormBuilder private attributes

### ISSUE THREAD

**Issue by SamiErrighi** [kristijanhusak/laravel-form-builder#97]
Hi,
I try to add some logic to your FormBuilder Class but that's difficult to extend this class because both container and formHelper attributes are privates.
It will be great if you can change it in protected instead

**Comment by kristijanhusak** [comment]
Hi,
Sure, will update it. Probably slipped through because of phpstorm's initialize field.
Will let you know when it's done. Thanks for reporting.

**Comment by kristijanhusak** [comment]
@SamiErrighi 
I fixed this on the `dev` version for now. Will be tagged to stable release soon.

**Comment by kristijanhusak** [comment]
It's fixed in version 1.5.0. Closing.
