### ISSUE TITLE
add FormRepository

### ISSUE THREAD

**Issue by SamiErrighi** [kristijanhusak/laravel-form-builder#99]
Hi,
So I played with the laravel Form Builder and this is really amazing .
But when I'm using the collection type  I have to set the data 'choices' with an Eloquent model like this:

    public function buildForm()
    {
        $this
            ->add('tags', 'collection', [
                'type' => 'choice',
                'options' => [
                    'expanded' => true,
                    'multiple' => true,
                    'choices' => Tag::all()->lists('name', 'id'),
                    'label' => false,
                ]
            ])
        ;
    }
I think that will be better if we can use a Repository Form to manage relationships.
This way that will be easier to test a form or  fetch any data we want like symfony did .

And that's will be great to implement an interface for the buildForm method.

What do you think about that ?

**Comment by kristijanhusak** [comment]
Hi,
I'm not sure what you mean by Repository Form, how it should work?

You can inject anything trough the constructor in Form class, and use it. something like this:
```php
class TagsRepository {
	protected $tag;

	public function __construct(Tag $tag)
	{
		$this->tag = $tag;
	}

	public function getSelectData()
	{
		return $this->tag->all()->lists('name', 'id');
	}
}


class TagsForm extends Form {

	protected $tags;

	public function __construct(TagsRepository $tags)
	{
		$this->tags = $tags;
	}	


	public function buildForm()
	{
		$this->add('tags', 'collection', [
			'type' => 'choice',
			'options' => [
				'choices' => $this->tags->getSelectData()
			]
		]);
	}

```
As far as I know, Symfony does not handle setting choices automatically in any way.
Can you give me some examples?

**Comment by SamiErrighi** [comment]
HI,
Here a little example:

In symfony you can have the Entity type :
```
$builder->add('users', 'entity', array(
    'class' => 'AcmeHelloBundle:User',
    'property' => 'username',
));
```
If you don't use a query builder by default He will fetch all data from database.
Well if we want a custom query we can inject our Repository like you did in your example but when you work with belongs to or many to many relationship maybe we should have default data to display in the form  field no ?

You can find more examples here http://symfony.com/doc/master/reference/forms/types/entity.html

**Comment by kristijanhusak** [comment]
Hi,
Yeah, it's a good idea. I'll work on implementing this. Thanks for the idea.

**Comment by kristijanhusak** [comment]
@SamiErrighi 
This field type is added in the latest releaset (1.5.1). Check in [this](https://github.com/kristijanhusak/laravel-form-builder#field-customization) section in the docs by name `categories`.

I plan to reorganize docs soon, so it will be easier to find. Thanks again for the idea.
